#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "../include/min-regex.h"

int correct  = 0;
int question = 0;

static bool is_match(const char* regex_str, const char* match_str, const int option);
static void is_valid(const int line, const char* regex_str, const char* match_str, const bool answer);
static void is_partial_valid(const int line, const char* regex_str, const char* match_str, const bool answer, const bool is_forward, const bool is_short);

// マッチ関数/*{{{*/
static bool is_match(const char* regex_str, const char* match_str, const int option) {
  char simple_regex[200];
  int current = 0;
  simplify_regex(regex_str, 0, strlen(regex_str), simple_regex, &current, 200);
  simple_regex[current] = '\0';
  MIN_REGEX_NODE node[200];
  regex_to_all_node(simple_regex, node, 200);
  MIN_REGEX_MATCH match[200];

  int step;
  if      (option == 0) step = exact_match(            match_str, node, match, 200);
  else if (option == 1) step = forward_shortest_match( match_str, node, match, 200);
  else if (option == 2) step = forward_longest_match(  match_str, node, match, 200);
  else if (option == 3) step = backward_shortest_match(match_str, node, match, 200);
  else if (option == 4) step = backward_longest_match( match_str, node, match, 200);
  else assert(0);

  bool ret;
  if (step > 0) {
    ret = true;
  } else {
    ret = false;
  }

  return ret;
}
/*}}}*/
// exactチェック関数/*{{{*/
static void is_valid(const int line, const char* regex_str, const char* match_str, const bool answer) {
  question++;
  bool trial = is_match(regex_str, match_str, 0); // 0はexact match
  if (trial == answer) {
    // fprintf(stderr, "LINE:%04d [\x1b[32mO\x1b[39m] %15s       \"%s\"\n"                , line, regex_str, match_str);
    correct++;
  }
  if (trial != answer) {
    fprintf(stderr, "LINE:%04d [\x1b[31mX\x1b[39m] \x1b[41m%15s       \"%s\"\x1b[49m", line, regex_str, match_str);
    if (answer) fprintf(stderr, "  SHOULD BE MIN_REGEX_MATCH BUT RESULT IS UNMIN_REGEX_MATCH.\n");
    else        fprintf(stderr, "  SHOULD BE UNMIN_REGEX_MATCH BUT RESULT IS MIN_REGEX_MATCH.\n");
  }
}/*}}}*/
// partialチェック関数/*{{{*/
static void is_partial_valid(const int line, const char* regex_str, const char* match_str, const bool answer, const bool is_forward, const bool is_short) {
  question++;
  const char *partial;
  bool trial;

  if        ( is_forward &&  is_short) {
    partial = "forward  shortest";
    trial = is_match(regex_str, match_str, 1);
  } else if ( is_forward && !is_short) {
    partial = "forward  longest ";
    trial = is_match(regex_str, match_str, 2);
  } else if (!is_forward &&  is_short) {
    partial = "backward shortest";
    trial = is_match(regex_str, match_str, 3);
  } else if (!is_forward && !is_short) {
    partial = "backward longest ";
    trial = is_match(regex_str, match_str, 4);
  } else {
    assert(0);
  }

  if (trial == answer) {
    // fprintf(stderr, "LINE:%04d [\x1b[32mO\x1b[39m] (%s) %15s       \"%s\"\n"              , line, partial, regex_str, match_str);
    correct++;
  }
  if (trial != answer) {
    fprintf(stderr, "LINE:%04d [\x1b[31mX\x1b[39m] (%s) \x1b[41m%15s       \"%s\"\x1b[49m", line, partial, regex_str, match_str);
    if (answer) fprintf(stderr, "  SHOULD BE MIN_REGEX_MATCH BUT RESULT IS UNMIN_REGEX_MATCH.\n");
    else        fprintf(stderr, "  SHOULD BE UNMIN_REGEX_MATCH BUT RESULT IS MIN_REGEX_MATCH.\n");
  }
}/*}}}*/

int main(void) {
  // 単純な正規表現を徹底的にチェック
  is_valid(__LINE__, ""             , ""    , false);/*{{{*/
  is_valid(__LINE__, "@"            , ""    , true );
  is_valid(__LINE__, "a"            , ""    , false);
  is_valid(__LINE__, "(@|@)"        , ""    , true );
  is_valid(__LINE__, "(a|@)"        , ""    , true );
  is_valid(__LINE__, "(@|a)"        , ""    , true );
  is_valid(__LINE__, "(a|a)"        , ""    , false);

  is_valid(__LINE__, "@*"           , ""    , true );
  is_valid(__LINE__, "a*"           , ""    , true );
  is_valid(__LINE__, "(@|@)*"       , ""    , true );
  is_valid(__LINE__, "(a|@)*"       , ""    , true );
  is_valid(__LINE__, "(@|a)*"       , ""    , true );
  is_valid(__LINE__, "(a|a)*"       , ""    , true );

  is_valid(__LINE__, "@@"           , ""    , true );
  is_valid(__LINE__, "@a"           , ""    , false);
  is_valid(__LINE__, "a@"           , ""    , false);
  is_valid(__LINE__, "aa"           , ""    , false);
  is_valid(__LINE__, "ab"           , ""    , false);
  is_valid(__LINE__, "(@|@)(@|@)"   , ""    , true );
  is_valid(__LINE__, "(@|@)(a|@)"   , ""    , true );
  is_valid(__LINE__, "(@|@)(@|a)"   , ""    , true );
  is_valid(__LINE__, "(@|@)(a|a)"   , ""    , false);
  is_valid(__LINE__, "(a|@)(@|@)"   , ""    , true );
  is_valid(__LINE__, "(a|@)(a|@)"   , ""    , true );
  is_valid(__LINE__, "(a|@)(@|a)"   , ""    , true );
  is_valid(__LINE__, "(a|@)(a|a)"   , ""    , false);
  is_valid(__LINE__, "(@|a)(@|@)"   , ""    , true );
  is_valid(__LINE__, "(@|a)(a|@)"   , ""    , true );
  is_valid(__LINE__, "(@|a)(@|a)"   , ""    , true );
  is_valid(__LINE__, "(@|a)(a|a)"   , ""    , false);
  is_valid(__LINE__, "(a|a)(@|@)"   , ""    , false);
  is_valid(__LINE__, "(a|a)(a|@)"   , ""    , false);
  is_valid(__LINE__, "(a|a)(@|a)"   , ""    , false);
  is_valid(__LINE__, "(a|a)(a|a)"   , ""    , false);

  is_valid(__LINE__, "@*@"          , ""    , true );
  is_valid(__LINE__, "@*a"          , ""    , false);
  is_valid(__LINE__, "a*@"          , ""    , true );
  is_valid(__LINE__, "a*a"          , ""    , false);
  is_valid(__LINE__, "a*b"          , ""    , false);
  is_valid(__LINE__, "(@|@)*(@|@)"  , ""    , true );
  is_valid(__LINE__, "(@|@)*(a|@)"  , ""    , true );
  is_valid(__LINE__, "(@|@)*(@|a)"  , ""    , true );
  is_valid(__LINE__, "(@|@)*(a|a)"  , ""    , false);
  is_valid(__LINE__, "(a|@)*(@|@)"  , ""    , true );
  is_valid(__LINE__, "(a|@)*(a|@)"  , ""    , true );
  is_valid(__LINE__, "(a|@)*(@|a)"  , ""    , true );
  is_valid(__LINE__, "(a|@)*(a|a)"  , ""    , false);
  is_valid(__LINE__, "(@|a)*(@|@)"  , ""    , true );
  is_valid(__LINE__, "(@|a)*(a|@)"  , ""    , true );
  is_valid(__LINE__, "(@|a)*(@|a)"  , ""    , true );
  is_valid(__LINE__, "(@|a)*(a|a)"  , ""    , false);
  is_valid(__LINE__, "(a|a)*(@|@)"  , ""    , true );
  is_valid(__LINE__, "(a|a)*(a|@)"  , ""    , true );
  is_valid(__LINE__, "(a|a)*(@|a)"  , ""    , true );
  is_valid(__LINE__, "(a|a)*(a|a)"  , ""    , false);

  is_valid(__LINE__, "@@*"          , ""    , true );
  is_valid(__LINE__, "@a*"          , ""    , true );
  is_valid(__LINE__, "a@*"          , ""    , false);
  is_valid(__LINE__, "aa*"          , ""    , false);
  is_valid(__LINE__, "ab*"          , ""    , false);
  is_valid(__LINE__, "(@|@)(@|@)*"  , ""    , true );
  is_valid(__LINE__, "(@|@)(a|@)*"  , ""    , true );
  is_valid(__LINE__, "(@|@)(@|a)*"  , ""    , true );
  is_valid(__LINE__, "(@|@)(a|a)*"  , ""    , true );
  is_valid(__LINE__, "(a|@)(@|@)*"  , ""    , true );
  is_valid(__LINE__, "(a|@)(a|@)*"  , ""    , true );
  is_valid(__LINE__, "(a|@)(@|a)*"  , ""    , true );
  is_valid(__LINE__, "(a|@)(a|a)*"  , ""    , true );
  is_valid(__LINE__, "(@|a)(@|@)*"  , ""    , true );
  is_valid(__LINE__, "(@|a)(a|@)*"  , ""    , true );
  is_valid(__LINE__, "(@|a)(@|a)*"  , ""    , true );
  is_valid(__LINE__, "(@|a)(a|a)*"  , ""    , true );
  is_valid(__LINE__, "(a|a)(@|@)*"  , ""    , false);
  is_valid(__LINE__, "(a|a)(a|@)*"  , ""    , false);
  is_valid(__LINE__, "(a|a)(@|a)*"  , ""    , false);
  is_valid(__LINE__, "(a|a)(a|a)*"  , ""    , false);

  is_valid(__LINE__, "@*@*"         , ""    , true );
  is_valid(__LINE__, "@*a*"         , ""    , true );
  is_valid(__LINE__, "a*@*"         , ""    , true );
  is_valid(__LINE__, "a*a*"         , ""    , true );
  is_valid(__LINE__, "a*b*"         , ""    , true );
  is_valid(__LINE__, "(@|@)*(@|@)*" , ""    , true );
  is_valid(__LINE__, "(@|@)*(a|@)*" , ""    , true );
  is_valid(__LINE__, "(@|@)*(@|a)*" , ""    , true );
  is_valid(__LINE__, "(@|@)*(a|a)*" , ""    , true );
  is_valid(__LINE__, "(a|@)*(@|@)*" , ""    , true );
  is_valid(__LINE__, "(a|@)*(a|@)*" , ""    , true );
  is_valid(__LINE__, "(a|@)*(@|a)*" , ""    , true );
  is_valid(__LINE__, "(a|@)*(a|a)*" , ""    , true );
  is_valid(__LINE__, "(@|a)*(@|@)*" , ""    , true );
  is_valid(__LINE__, "(@|a)*(a|@)*" , ""    , true );
  is_valid(__LINE__, "(@|a)*(@|a)*" , ""    , true );
  is_valid(__LINE__, "(@|a)*(a|a)*" , ""    , true );
  is_valid(__LINE__, "(a|a)*(@|@)*" , ""    , true );
  is_valid(__LINE__, "(a|a)*(a|@)*" , ""    , true );
  is_valid(__LINE__, "(a|a)*(@|a)*" , ""    , true );
  is_valid(__LINE__, "(a|a)*(a|a)*" , ""    , true );/*}}}*/
  is_valid(__LINE__, ""             , "a"   , false);/*{{{*/
  is_valid(__LINE__, "@"            , "a"   , false);
  is_valid(__LINE__, "a"            , "a"   , true );
  is_valid(__LINE__, "(@|@)"        , "a"   , false);
  is_valid(__LINE__, "(a|@)"        , "a"   , true );
  is_valid(__LINE__, "(@|a)"        , "a"   , true );
  is_valid(__LINE__, "(a|a)"        , "a"   , true );

  is_valid(__LINE__, "@*"           , "a"   , false);
  is_valid(__LINE__, "a*"           , "a"   , true );
  is_valid(__LINE__, "(@|@)*"       , "a"   , false);
  is_valid(__LINE__, "(a|@)*"       , "a"   , true );
  is_valid(__LINE__, "(@|a)*"       , "a"   , true );
  is_valid(__LINE__, "(a|a)*"       , "a"   , true );

  is_valid(__LINE__, "@@"           , "a"   , false);
  is_valid(__LINE__, "@a"           , "a"   , true );
  is_valid(__LINE__, "a@"           , "a"   , true );
  is_valid(__LINE__, "aa"           , "a"   , false);
  is_valid(__LINE__, "ab"           , "a"   , false);
  is_valid(__LINE__, "(@|@)(@|@)"   , "a"   , false);
  is_valid(__LINE__, "(@|@)(a|@)"   , "a"   , true );
  is_valid(__LINE__, "(@|@)(@|a)"   , "a"   , true );
  is_valid(__LINE__, "(@|@)(a|a)"   , "a"   , true );
  is_valid(__LINE__, "(a|@)(@|@)"   , "a"   , true );
  is_valid(__LINE__, "(a|@)(a|@)"   , "a"   , true );
  is_valid(__LINE__, "(a|@)(@|a)"   , "a"   , true );
  is_valid(__LINE__, "(a|@)(a|a)"   , "a"   , true );
  is_valid(__LINE__, "(@|a)(@|@)"   , "a"   , true );
  is_valid(__LINE__, "(@|a)(a|@)"   , "a"   , true );
  is_valid(__LINE__, "(@|a)(@|a)"   , "a"   , true );
  is_valid(__LINE__, "(@|a)(a|a)"   , "a"   , true );
  is_valid(__LINE__, "(a|a)(@|@)"   , "a"   , true );
  is_valid(__LINE__, "(a|a)(a|@)"   , "a"   , true );
  is_valid(__LINE__, "(a|a)(@|a)"   , "a"   , true );
  is_valid(__LINE__, "(a|a)(a|a)"   , "a"   , false);

  is_valid(__LINE__, "@*@"          , "a"   , false);
  is_valid(__LINE__, "@*a"          , "a"   , true );
  is_valid(__LINE__, "a*@"          , "a"   , true );
  is_valid(__LINE__, "a*a"          , "a"   , true );
  is_valid(__LINE__, "a*b"          , "a"   , false);
  is_valid(__LINE__, "(@|@)*(@|@)"  , "a"   , false);
  is_valid(__LINE__, "(@|@)*(a|@)"  , "a"   , true );
  is_valid(__LINE__, "(@|@)*(@|a)"  , "a"   , true );
  is_valid(__LINE__, "(@|@)*(a|a)"  , "a"   , true );
  is_valid(__LINE__, "(a|@)*(@|@)"  , "a"   , true );
  is_valid(__LINE__, "(a|@)*(a|@)"  , "a"   , true );
  is_valid(__LINE__, "(a|@)*(@|a)"  , "a"   , true );
  is_valid(__LINE__, "(a|@)*(a|a)"  , "a"   , true );
  is_valid(__LINE__, "(@|a)*(@|@)"  , "a"   , true );
  is_valid(__LINE__, "(@|a)*(a|@)"  , "a"   , true );
  is_valid(__LINE__, "(@|a)*(@|a)"  , "a"   , true );
  is_valid(__LINE__, "(@|a)*(a|a)"  , "a"   , true );
  is_valid(__LINE__, "(a|a)*(@|@)"  , "a"   , true );
  is_valid(__LINE__, "(a|a)*(a|@)"  , "a"   , true );
  is_valid(__LINE__, "(a|a)*(@|a)"  , "a"   , true );
  is_valid(__LINE__, "(a|a)*(a|a)"  , "a"   , true );

  is_valid(__LINE__, "@@*"          , "a"   , false);
  is_valid(__LINE__, "@a*"          , "a"   , true );
  is_valid(__LINE__, "a@*"          , "a"   , true );
  is_valid(__LINE__, "aa*"          , "a"   , true );
  is_valid(__LINE__, "ab*"          , "a"   , true );
  is_valid(__LINE__, "(@|@)(@|@)*"  , "a"   , false);
  is_valid(__LINE__, "(@|@)(a|@)*"  , "a"   , true );
  is_valid(__LINE__, "(@|@)(@|a)*"  , "a"   , true );
  is_valid(__LINE__, "(@|@)(a|a)*"  , "a"   , true );
  is_valid(__LINE__, "(a|@)(@|@)*"  , "a"   , true );
  is_valid(__LINE__, "(a|@)(a|@)*"  , "a"   , true );
  is_valid(__LINE__, "(a|@)(@|a)*"  , "a"   , true );
  is_valid(__LINE__, "(a|@)(a|a)*"  , "a"   , true );
  is_valid(__LINE__, "(@|a)(@|@)*"  , "a"   , true );
  is_valid(__LINE__, "(@|a)(a|@)*"  , "a"   , true );
  is_valid(__LINE__, "(@|a)(@|a)*"  , "a"   , true );
  is_valid(__LINE__, "(@|a)(a|a)*"  , "a"   , true );
  is_valid(__LINE__, "(a|a)(@|@)*"  , "a"   , true );
  is_valid(__LINE__, "(a|a)(a|@)*"  , "a"   , true );
  is_valid(__LINE__, "(a|a)(@|a)*"  , "a"   , true );
  is_valid(__LINE__, "(a|a)(a|a)*"  , "a"   , true );
  is_valid(__LINE__, "@*@*"         , "a"   , false);
  is_valid(__LINE__, "@*a*"         , "a"   , true );
  is_valid(__LINE__, "a*@*"         , "a"   , true );
  is_valid(__LINE__, "a*a*"         , "a"   , true );
  is_valid(__LINE__, "a*b*"         , "a"   , true );
  is_valid(__LINE__, "(@|@)*(@|@)*" , "a"   , false);
  is_valid(__LINE__, "(@|@)*(a|@)*" , "a"   , true );
  is_valid(__LINE__, "(@|@)*(@|a)*" , "a"   , true );
  is_valid(__LINE__, "(@|@)*(a|a)*" , "a"   , true );
  is_valid(__LINE__, "(a|@)*(@|@)*" , "a"   , true );
  is_valid(__LINE__, "(a|@)*(a|@)*" , "a"   , true );
  is_valid(__LINE__, "(a|@)*(@|a)*" , "a"   , true );
  is_valid(__LINE__, "(a|@)*(a|a)*" , "a"   , true );
  is_valid(__LINE__, "(@|a)*(@|@)*" , "a"   , true );
  is_valid(__LINE__, "(@|a)*(a|@)*" , "a"   , true );
  is_valid(__LINE__, "(@|a)*(@|a)*" , "a"   , true );
  is_valid(__LINE__, "(@|a)*(a|a)*" , "a"   , true );
  is_valid(__LINE__, "(a|a)*(@|@)*" , "a"   , true );
  is_valid(__LINE__, "(a|a)*(a|@)*" , "a"   , true );
  is_valid(__LINE__, "(a|a)*(@|a)*" , "a"   , true );
  is_valid(__LINE__, "(a|a)*(a|a)*" , "a"   , true );/*}}}*/
  is_valid(__LINE__, ""             , "b"   , false);/*{{{*/
  is_valid(__LINE__, "@"            , "b"   , false);
  is_valid(__LINE__, "a"            , "b"   , false);
  is_valid(__LINE__, "(@|@)"        , "b"   , false);
  is_valid(__LINE__, "(a|@)"        , "b"   , false);
  is_valid(__LINE__, "(@|a)"        , "b"   , false);
  is_valid(__LINE__, "(a|a)"        , "b"   , false);

  is_valid(__LINE__, "@*"           , "b"   , false);
  is_valid(__LINE__, "a*"           , "b"   , false);
  is_valid(__LINE__, "(@|@)*"       , "b"   , false);
  is_valid(__LINE__, "(a|@)*"       , "b"   , false);
  is_valid(__LINE__, "(@|a)*"       , "b"   , false);
  is_valid(__LINE__, "(a|a)*"       , "b"   , false);

  is_valid(__LINE__, "@@"           , "b"   , false);
  is_valid(__LINE__, "@a"           , "b"   , false);
  is_valid(__LINE__, "a@"           , "b"   , false);
  is_valid(__LINE__, "aa"           , "b"   , false);
  is_valid(__LINE__, "ab"           , "b"   , false);
  is_valid(__LINE__, "(@|@)(@|@)"   , "b"   , false);
  is_valid(__LINE__, "(@|@)(a|@)"   , "b"   , false);
  is_valid(__LINE__, "(@|@)(@|a)"   , "b"   , false);
  is_valid(__LINE__, "(@|@)(a|a)"   , "b"   , false);
  is_valid(__LINE__, "(a|@)(@|@)"   , "b"   , false);
  is_valid(__LINE__, "(a|@)(a|@)"   , "b"   , false);
  is_valid(__LINE__, "(a|@)(@|a)"   , "b"   , false);
  is_valid(__LINE__, "(a|@)(a|a)"   , "b"   , false);
  is_valid(__LINE__, "(@|a)(@|@)"   , "b"   , false);
  is_valid(__LINE__, "(@|a)(a|@)"   , "b"   , false);
  is_valid(__LINE__, "(@|a)(@|a)"   , "b"   , false);
  is_valid(__LINE__, "(@|a)(a|a)"   , "b"   , false);
  is_valid(__LINE__, "(a|a)(@|@)"   , "b"   , false);
  is_valid(__LINE__, "(a|a)(a|@)"   , "b"   , false);
  is_valid(__LINE__, "(a|a)(@|a)"   , "b"   , false);
  is_valid(__LINE__, "(a|a)(a|a)"   , "b"   , false);

  is_valid(__LINE__, "@*@"          , "b"   , false);
  is_valid(__LINE__, "@*a"          , "b"   , false);
  is_valid(__LINE__, "a*@"          , "b"   , false);
  is_valid(__LINE__, "a*a"          , "b"   , false);
  is_valid(__LINE__, "a*b"          , "b"   , true );
  is_valid(__LINE__, "(@|@)*(@|@)"  , "b"   , false);
  is_valid(__LINE__, "(@|@)*(a|@)"  , "b"   , false);
  is_valid(__LINE__, "(@|@)*(@|a)"  , "b"   , false);
  is_valid(__LINE__, "(@|@)*(a|a)"  , "b"   , false);
  is_valid(__LINE__, "(a|@)*(@|@)"  , "b"   , false);
  is_valid(__LINE__, "(a|@)*(a|@)"  , "b"   , false);
  is_valid(__LINE__, "(a|@)*(@|a)"  , "b"   , false);
  is_valid(__LINE__, "(a|@)*(a|a)"  , "b"   , false);
  is_valid(__LINE__, "(@|a)*(@|@)"  , "b"   , false);
  is_valid(__LINE__, "(@|a)*(a|@)"  , "b"   , false);
  is_valid(__LINE__, "(@|a)*(@|a)"  , "b"   , false);
  is_valid(__LINE__, "(@|a)*(a|a)"  , "b"   , false);
  is_valid(__LINE__, "(a|a)*(@|@)"  , "b"   , false);
  is_valid(__LINE__, "(a|a)*(a|@)"  , "b"   , false);
  is_valid(__LINE__, "(a|a)*(@|a)"  , "b"   , false);
  is_valid(__LINE__, "(a|a)*(a|a)"  , "b"   , false);

  is_valid(__LINE__, "@@*"          , "b"   , false);
  is_valid(__LINE__, "@a*"          , "b"   , false);
  is_valid(__LINE__, "a@*"          , "b"   , false);
  is_valid(__LINE__, "aa*"          , "b"   , false);
  is_valid(__LINE__, "ab*"          , "b"   , false);
  is_valid(__LINE__, "(@|@)(@|@)*"  , "b"   , false);
  is_valid(__LINE__, "(@|@)(a|@)*"  , "b"   , false);
  is_valid(__LINE__, "(@|@)(@|a)*"  , "b"   , false);
  is_valid(__LINE__, "(@|@)(a|a)*"  , "b"   , false);
  is_valid(__LINE__, "(a|@)(@|@)*"  , "b"   , false);
  is_valid(__LINE__, "(a|@)(a|@)*"  , "b"   , false);
  is_valid(__LINE__, "(a|@)(@|a)*"  , "b"   , false);
  is_valid(__LINE__, "(a|@)(a|a)*"  , "b"   , false);
  is_valid(__LINE__, "(@|a)(@|@)*"  , "b"   , false);
  is_valid(__LINE__, "(@|a)(a|@)*"  , "b"   , false);
  is_valid(__LINE__, "(@|a)(@|a)*"  , "b"   , false);
  is_valid(__LINE__, "(@|a)(a|a)*"  , "b"   , false);
  is_valid(__LINE__, "(a|a)(@|@)*"  , "b"   , false);
  is_valid(__LINE__, "(a|a)(a|@)*"  , "b"   , false);
  is_valid(__LINE__, "(a|a)(@|a)*"  , "b"   , false);
  is_valid(__LINE__, "(a|a)(a|a)*"  , "b"   , false);

  is_valid(__LINE__, "@*@*"         , "b"   , false);
  is_valid(__LINE__, "@*a*"         , "b"   , false);
  is_valid(__LINE__, "a*@*"         , "b"   , false);
  is_valid(__LINE__, "a*a*"         , "b"   , false);
  is_valid(__LINE__, "a*b*"         , "b"   , true );
  is_valid(__LINE__, "(@|@)*(@|@)*" , "b"   , false);
  is_valid(__LINE__, "(@|@)*(a|@)*" , "b"   , false);
  is_valid(__LINE__, "(@|@)*(@|a)*" , "b"   , false);
  is_valid(__LINE__, "(@|@)*(a|a)*" , "b"   , false);
  is_valid(__LINE__, "(a|@)*(@|@)*" , "b"   , false);
  is_valid(__LINE__, "(a|@)*(a|@)*" , "b"   , false);
  is_valid(__LINE__, "(a|@)*(@|a)*" , "b"   , false);
  is_valid(__LINE__, "(a|@)*(a|a)*" , "b"   , false);
  is_valid(__LINE__, "(@|a)*(@|@)*" , "b"   , false);
  is_valid(__LINE__, "(@|a)*(a|@)*" , "b"   , false);
  is_valid(__LINE__, "(@|a)*(@|a)*" , "b"   , false);
  is_valid(__LINE__, "(@|a)*(a|a)*" , "b"   , false);
  is_valid(__LINE__, "(a|a)*(@|@)*" , "b"   , false);
  is_valid(__LINE__, "(a|a)*(a|@)*" , "b"   , false);
  is_valid(__LINE__, "(a|a)*(@|a)*" , "b"   , false);
  is_valid(__LINE__, "(a|a)*(a|a)*" , "b"   , false);/*}}}*/
  is_valid(__LINE__, ""             , "aa"  , false);/*{{{*/
  is_valid(__LINE__, "@"            , "aa"  , false);
  is_valid(__LINE__, "a"            , "aa"  , false);
  is_valid(__LINE__, "(@|@)"        , "aa"  , false);
  is_valid(__LINE__, "(a|@)"        , "aa"  , false);
  is_valid(__LINE__, "(@|a)"        , "aa"  , false);
  is_valid(__LINE__, "(a|a)"        , "aa"  , false);

  is_valid(__LINE__, "@*"           , "aa"  , false);
  is_valid(__LINE__, "a*"           , "aa"  , true );
  is_valid(__LINE__, "(@|@)*"       , "aa"  , false);
  is_valid(__LINE__, "(a|@)*"       , "aa"  , true );
  is_valid(__LINE__, "(@|a)*"       , "aa"  , true );
  is_valid(__LINE__, "(a|a)*"       , "aa"  , true );

  is_valid(__LINE__, "@@"           , "aa"  , false);
  is_valid(__LINE__, "@a"           , "aa"  , false);
  is_valid(__LINE__, "a@"           , "aa"  , false);
  is_valid(__LINE__, "aa"           , "aa"  , true );
  is_valid(__LINE__, "ab"           , "aa"  , false);
  is_valid(__LINE__, "(@|@)(@|@)"   , "aa"  , false);
  is_valid(__LINE__, "(@|@)(a|@)"   , "aa"  , false);
  is_valid(__LINE__, "(@|@)(@|a)"   , "aa"  , false);
  is_valid(__LINE__, "(@|@)(a|a)"   , "aa"  , false);
  is_valid(__LINE__, "(a|@)(@|@)"   , "aa"  , false);
  is_valid(__LINE__, "(a|@)(a|@)"   , "aa"  , true );
  is_valid(__LINE__, "(a|@)(@|a)"   , "aa"  , true );
  is_valid(__LINE__, "(a|@)(a|a)"   , "aa"  , true );
  is_valid(__LINE__, "(@|a)(@|@)"   , "aa"  , false);
  is_valid(__LINE__, "(@|a)(a|@)"   , "aa"  , true );
  is_valid(__LINE__, "(@|a)(@|a)"   , "aa"  , true );
  is_valid(__LINE__, "(@|a)(a|a)"   , "aa"  , true );
  is_valid(__LINE__, "(a|a)(@|@)"   , "aa"  , false);
  is_valid(__LINE__, "(a|a)(a|@)"   , "aa"  , true );
  is_valid(__LINE__, "(a|a)(@|a)"   , "aa"  , true );
  is_valid(__LINE__, "(a|a)(a|a)"   , "aa"  , true );

  is_valid(__LINE__, "@*@"          , "aa"  , false);
  is_valid(__LINE__, "@*a"          , "aa"  , false);
  is_valid(__LINE__, "a*@"          , "aa"  , true );
  is_valid(__LINE__, "a*a"          , "aa"  , true );
  is_valid(__LINE__, "a*b"          , "aa"  , false);
  is_valid(__LINE__, "(@|@)*(@|@)"  , "aa"  , false);
  is_valid(__LINE__, "(@|@)*(a|@)"  , "aa"  , false);
  is_valid(__LINE__, "(@|@)*(@|a)"  , "aa"  , false);
  is_valid(__LINE__, "(@|@)*(a|a)"  , "aa"  , false);
  is_valid(__LINE__, "(a|@)*(@|@)"  , "aa"  , true );
  is_valid(__LINE__, "(a|@)*(a|@)"  , "aa"  , true );
  is_valid(__LINE__, "(a|@)*(@|a)"  , "aa"  , true );
  is_valid(__LINE__, "(a|@)*(a|a)"  , "aa"  , true );
  is_valid(__LINE__, "(@|a)*(@|@)"  , "aa"  , true );
  is_valid(__LINE__, "(@|a)*(a|@)"  , "aa"  , true );
  is_valid(__LINE__, "(@|a)*(@|a)"  , "aa"  , true );
  is_valid(__LINE__, "(@|a)*(a|a)"  , "aa"  , true );
  is_valid(__LINE__, "(a|a)*(@|@)"  , "aa"  , true );
  is_valid(__LINE__, "(a|a)*(a|@)"  , "aa"  , true );
  is_valid(__LINE__, "(a|a)*(@|a)"  , "aa"  , true );
  is_valid(__LINE__, "(a|a)*(a|a)"  , "aa"  , true );

  is_valid(__LINE__, "@@*"          , "aa"  , false);
  is_valid(__LINE__, "@a*"          , "aa"  , true );
  is_valid(__LINE__, "a@*"          , "aa"  , false);
  is_valid(__LINE__, "aa*"          , "aa"  , true );
  is_valid(__LINE__, "ab*"          , "aa"  , false);
  is_valid(__LINE__, "(@|@)(@|@)*"  , "aa"  , false);
  is_valid(__LINE__, "(@|@)(a|@)*"  , "aa"  , true );
  is_valid(__LINE__, "(@|@)(@|a)*"  , "aa"  , true );
  is_valid(__LINE__, "(@|@)(a|a)*"  , "aa"  , true );
  is_valid(__LINE__, "(a|@)(@|@)*"  , "aa"  , false);
  is_valid(__LINE__, "(a|@)(a|@)*"  , "aa"  , true );
  is_valid(__LINE__, "(a|@)(@|a)*"  , "aa"  , true );
  is_valid(__LINE__, "(a|@)(a|a)*"  , "aa"  , true );
  is_valid(__LINE__, "(@|a)(@|@)*"  , "aa"  , false);
  is_valid(__LINE__, "(@|a)(a|@)*"  , "aa"  , true );
  is_valid(__LINE__, "(@|a)(@|a)*"  , "aa"  , true );
  is_valid(__LINE__, "(@|a)(a|a)*"  , "aa"  , true );
  is_valid(__LINE__, "(a|a)(@|@)*"  , "aa"  , false);
  is_valid(__LINE__, "(a|a)(a|@)*"  , "aa"  , true );
  is_valid(__LINE__, "(a|a)(@|a)*"  , "aa"  , true );
  is_valid(__LINE__, "(a|a)(a|a)*"  , "aa"  , true );

  is_valid(__LINE__, "@*@*"         , "aa"  , false);
  is_valid(__LINE__, "@*a*"         , "aa"  , true );
  is_valid(__LINE__, "a*@*"         , "aa"  , true );
  is_valid(__LINE__, "a*a*"         , "aa"  , true );
  is_valid(__LINE__, "a*b*"         , "aa"  , true );
  is_valid(__LINE__, "(@|@)*(@|@)*" , "aa"  , false);
  is_valid(__LINE__, "(@|@)*(a|@)*" , "aa"  , true );
  is_valid(__LINE__, "(@|@)*(@|a)*" , "aa"  , true );
  is_valid(__LINE__, "(@|@)*(a|a)*" , "aa"  , true );
  is_valid(__LINE__, "(a|@)*(@|@)*" , "aa"  , true );
  is_valid(__LINE__, "(a|@)*(a|@)*" , "aa"  , true );
  is_valid(__LINE__, "(a|@)*(@|a)*" , "aa"  , true );
  is_valid(__LINE__, "(a|@)*(a|a)*" , "aa"  , true );
  is_valid(__LINE__, "(@|a)*(@|@)*" , "aa"  , true );
  is_valid(__LINE__, "(@|a)*(a|@)*" , "aa"  , true );
  is_valid(__LINE__, "(@|a)*(@|a)*" , "aa"  , true );
  is_valid(__LINE__, "(@|a)*(a|a)*" , "aa"  , true );
  is_valid(__LINE__, "(a|a)*(@|@)*" , "aa"  , true );
  is_valid(__LINE__, "(a|a)*(a|@)*" , "aa"  , true );
  is_valid(__LINE__, "(a|a)*(@|a)*" , "aa"  , true );
  is_valid(__LINE__, "(a|a)*(a|a)*" , "aa"  , true );/*}}}*/
  is_valid(__LINE__, ""             , "aaa" , false);/*{{{*/
  is_valid(__LINE__, "@"            , "aaa" , false);
  is_valid(__LINE__, "a"            , "aaa" , false);
  is_valid(__LINE__, "(@|@)"        , "aaa" , false);
  is_valid(__LINE__, "(a|@)"        , "aaa" , false);
  is_valid(__LINE__, "(@|a)"        , "aaa" , false);
  is_valid(__LINE__, "(a|a)"        , "aaa" , false);

  is_valid(__LINE__, "@*"           , "aaa" , false);
  is_valid(__LINE__, "a*"           , "aaa" , true );
  is_valid(__LINE__, "(@|@)*"       , "aaa" , false);
  is_valid(__LINE__, "(a|@)*"       , "aaa" , true );
  is_valid(__LINE__, "(@|a)*"       , "aaa" , true );
  is_valid(__LINE__, "(a|a)*"       , "aaa" , true );

  is_valid(__LINE__, "@@"           , "aaa" , false);
  is_valid(__LINE__, "@a"           , "aaa" , false);
  is_valid(__LINE__, "a@"           , "aaa" , false);
  is_valid(__LINE__, "aa"           , "aaa" , false);
  is_valid(__LINE__, "ab"           , "aaa" , false);
  is_valid(__LINE__, "(@|@)(@|@)"   , "aaa" , false);
  is_valid(__LINE__, "(@|@)(a|@)"   , "aaa" , false);
  is_valid(__LINE__, "(@|@)(@|a)"   , "aaa" , false);
  is_valid(__LINE__, "(@|@)(a|a)"   , "aaa" , false);
  is_valid(__LINE__, "(a|@)(@|@)"   , "aaa" , false);
  is_valid(__LINE__, "(a|@)(a|@)"   , "aaa" , false);
  is_valid(__LINE__, "(a|@)(@|a)"   , "aaa" , false);
  is_valid(__LINE__, "(a|@)(a|a)"   , "aaa" , false);
  is_valid(__LINE__, "(@|a)(@|@)"   , "aaa" , false);
  is_valid(__LINE__, "(@|a)(a|@)"   , "aaa" , false);
  is_valid(__LINE__, "(@|a)(@|a)"   , "aaa" , false);
  is_valid(__LINE__, "(@|a)(a|a)"   , "aaa" , false);
  is_valid(__LINE__, "(a|a)(@|@)"   , "aaa" , false);
  is_valid(__LINE__, "(a|a)(a|@)"   , "aaa" , false);
  is_valid(__LINE__, "(a|a)(@|a)"   , "aaa" , false);
  is_valid(__LINE__, "(a|a)(a|a)"   , "aaa" , false);

  is_valid(__LINE__, "@*@"          , "aaa" , false);
  is_valid(__LINE__, "@*a"          , "aaa" , false);
  is_valid(__LINE__, "a*@"          , "aaa" , true );
  is_valid(__LINE__, "a*a"          , "aaa" , true );
  is_valid(__LINE__, "a*b"          , "aaa" , false);
  is_valid(__LINE__, "(@|@)*(@|@)"  , "aaa" , false);
  is_valid(__LINE__, "(@|@)*(a|@)"  , "aaa" , false);
  is_valid(__LINE__, "(@|@)*(@|a)"  , "aaa" , false);
  is_valid(__LINE__, "(@|@)*(a|a)"  , "aaa" , false);
  is_valid(__LINE__, "(a|@)*(@|@)"  , "aaa" , true );
  is_valid(__LINE__, "(a|@)*(a|@)"  , "aaa" , true );
  is_valid(__LINE__, "(a|@)*(@|a)"  , "aaa" , true );
  is_valid(__LINE__, "(a|@)*(a|a)"  , "aaa" , true );
  is_valid(__LINE__, "(@|a)*(@|@)"  , "aaa" , true );
  is_valid(__LINE__, "(@|a)*(a|@)"  , "aaa" , true );
  is_valid(__LINE__, "(@|a)*(@|a)"  , "aaa" , true );
  is_valid(__LINE__, "(@|a)*(a|a)"  , "aaa" , true );
  is_valid(__LINE__, "(a|a)*(@|@)"  , "aaa" , true );
  is_valid(__LINE__, "(a|a)*(a|@)"  , "aaa" , true );
  is_valid(__LINE__, "(a|a)*(@|a)"  , "aaa" , true );
  is_valid(__LINE__, "(a|a)*(a|a)"  , "aaa" , true );

  is_valid(__LINE__, "@@*"          , "aaa" , false);
  is_valid(__LINE__, "@a*"          , "aaa" , true );
  is_valid(__LINE__, "a@*"          , "aaa" , false);
  is_valid(__LINE__, "aa*"          , "aaa" , true );
  is_valid(__LINE__, "ab*"          , "aaa" , false);
  is_valid(__LINE__, "(@|@)(@|@)*"  , "aaa" , false);
  is_valid(__LINE__, "(@|@)(a|@)*"  , "aaa" , true );
  is_valid(__LINE__, "(@|@)(@|a)*"  , "aaa" , true );
  is_valid(__LINE__, "(@|@)(a|a)*"  , "aaa" , true );
  is_valid(__LINE__, "(a|@)(@|@)*"  , "aaa" , false);
  is_valid(__LINE__, "(a|@)(a|@)*"  , "aaa" , true );
  is_valid(__LINE__, "(a|@)(@|a)*"  , "aaa" , true );
  is_valid(__LINE__, "(a|@)(a|a)*"  , "aaa" , true );
  is_valid(__LINE__, "(@|a)(@|@)*"  , "aaa" , false);
  is_valid(__LINE__, "(@|a)(a|@)*"  , "aaa" , true );
  is_valid(__LINE__, "(@|a)(@|a)*"  , "aaa" , true );
  is_valid(__LINE__, "(@|a)(a|a)*"  , "aaa" , true );
  is_valid(__LINE__, "(a|a)(@|@)*"  , "aaa" , false);
  is_valid(__LINE__, "(a|a)(a|@)*"  , "aaa" , true );
  is_valid(__LINE__, "(a|a)(@|a)*"  , "aaa" , true );
  is_valid(__LINE__, "(a|a)(a|a)*"  , "aaa" , true );

  is_valid(__LINE__, "@*@*"         , "aaa" , false);
  is_valid(__LINE__, "@*a*"         , "aaa" , true );
  is_valid(__LINE__, "a*@*"         , "aaa" , true );
  is_valid(__LINE__, "a*a*"         , "aaa" , true );
  is_valid(__LINE__, "a*b*"         , "aaa" , true );
  is_valid(__LINE__, "(@|@)*(@|@)*" , "aaa" , false);
  is_valid(__LINE__, "(@|@)*(a|@)*" , "aaa" , true );
  is_valid(__LINE__, "(@|@)*(@|a)*" , "aaa" , true );
  is_valid(__LINE__, "(@|@)*(a|a)*" , "aaa" , true );
  is_valid(__LINE__, "(a|@)*(@|@)*" , "aaa" , true );
  is_valid(__LINE__, "(a|@)*(a|@)*" , "aaa" , true );
  is_valid(__LINE__, "(a|@)*(@|a)*" , "aaa" , true );
  is_valid(__LINE__, "(a|@)*(a|a)*" , "aaa" , true );
  is_valid(__LINE__, "(@|a)*(@|@)*" , "aaa" , true );
  is_valid(__LINE__, "(@|a)*(a|@)*" , "aaa" , true );
  is_valid(__LINE__, "(@|a)*(@|a)*" , "aaa" , true );
  is_valid(__LINE__, "(@|a)*(a|a)*" , "aaa" , true );
  is_valid(__LINE__, "(a|a)*(@|@)*" , "aaa" , true );
  is_valid(__LINE__, "(a|a)*(a|@)*" , "aaa" , true );
  is_valid(__LINE__, "(a|a)*(@|a)*" , "aaa" , true );
  is_valid(__LINE__, "(a|a)*(a|a)*" , "aaa" , true );/*}}}*/
  is_valid(__LINE__, ""             , "ab"  , false);/*{{{*/
  is_valid(__LINE__, "@"            , "ab"  , false);
  is_valid(__LINE__, "a"            , "ab"  , false);
  is_valid(__LINE__, "(@|@)"        , "ab"  , false);
  is_valid(__LINE__, "(a|@)"        , "ab"  , false);
  is_valid(__LINE__, "(@|a)"        , "ab"  , false);
  is_valid(__LINE__, "(a|a)"        , "ab"  , false);

  is_valid(__LINE__, "@*"           , "ab"  , false);
  is_valid(__LINE__, "a*"           , "ab"  , false);
  is_valid(__LINE__, "(@|@)*"       , "ab"  , false);
  is_valid(__LINE__, "(a|@)*"       , "ab"  , false);
  is_valid(__LINE__, "(@|a)*"       , "ab"  , false);
  is_valid(__LINE__, "(a|a)*"       , "ab"  , false);

  is_valid(__LINE__, "@@"           , "ab"  , false);
  is_valid(__LINE__, "@a"           , "ab"  , false);
  is_valid(__LINE__, "a@"           , "ab"  , false);
  is_valid(__LINE__, "aa"           , "ab"  , false);
  is_valid(__LINE__, "ab"           , "ab"  , true );
  is_valid(__LINE__, "(@|@)(@|@)"   , "ab"  , false);
  is_valid(__LINE__, "(@|@)(a|@)"   , "ab"  , false);
  is_valid(__LINE__, "(@|@)(@|a)"   , "ab"  , false);
  is_valid(__LINE__, "(@|@)(a|a)"   , "ab"  , false);
  is_valid(__LINE__, "(a|@)(@|@)"   , "ab"  , false);
  is_valid(__LINE__, "(a|@)(a|@)"   , "ab"  , false);
  is_valid(__LINE__, "(a|@)(@|a)"   , "ab"  , false);
  is_valid(__LINE__, "(a|@)(a|a)"   , "ab"  , false);
  is_valid(__LINE__, "(@|a)(@|@)"   , "ab"  , false);
  is_valid(__LINE__, "(@|a)(a|@)"   , "ab"  , false);
  is_valid(__LINE__, "(@|a)(@|a)"   , "ab"  , false);
  is_valid(__LINE__, "(@|a)(a|a)"   , "ab"  , false);
  is_valid(__LINE__, "(a|a)(@|@)"   , "ab"  , false);
  is_valid(__LINE__, "(a|a)(a|@)"   , "ab"  , false);
  is_valid(__LINE__, "(a|a)(@|a)"   , "ab"  , false);
  is_valid(__LINE__, "(a|a)(a|a)"   , "ab"  , false);

  is_valid(__LINE__, "@*@"          , "ab"  , false);
  is_valid(__LINE__, "@*a"          , "ab"  , false);
  is_valid(__LINE__, "a*@"          , "ab"  , false);
  is_valid(__LINE__, "a*a"          , "ab"  , false);
  is_valid(__LINE__, "a*b"          , "ab"  , true );
  is_valid(__LINE__, "(@|@)*(@|@)"  , "ab"  , false);
  is_valid(__LINE__, "(@|@)*(a|@)"  , "ab"  , false);
  is_valid(__LINE__, "(@|@)*(@|a)"  , "ab"  , false);
  is_valid(__LINE__, "(@|@)*(a|a)"  , "ab"  , false);
  is_valid(__LINE__, "(a|@)*(@|@)"  , "ab"  , false);
  is_valid(__LINE__, "(a|@)*(a|@)"  , "ab"  , false);
  is_valid(__LINE__, "(a|@)*(@|a)"  , "ab"  , false);
  is_valid(__LINE__, "(a|@)*(a|a)"  , "ab"  , false);
  is_valid(__LINE__, "(@|a)*(@|@)"  , "ab"  , false);
  is_valid(__LINE__, "(@|a)*(a|@)"  , "ab"  , false);
  is_valid(__LINE__, "(@|a)*(@|a)"  , "ab"  , false);
  is_valid(__LINE__, "(@|a)*(a|a)"  , "ab"  , false);
  is_valid(__LINE__, "(a|a)*(@|@)"  , "ab"  , false);
  is_valid(__LINE__, "(a|a)*(a|@)"  , "ab"  , false);
  is_valid(__LINE__, "(a|a)*(@|a)"  , "ab"  , false);
  is_valid(__LINE__, "(a|a)*(a|a)"  , "ab"  , false);

  is_valid(__LINE__, "@@*"          , "ab"  , false);
  is_valid(__LINE__, "@a*"          , "ab"  , false);
  is_valid(__LINE__, "a@*"          , "ab"  , false);
  is_valid(__LINE__, "aa*"          , "ab"  , false);
  is_valid(__LINE__, "ab*"          , "ab"  , true );
  is_valid(__LINE__, "(@|@)(@|@)*"  , "ab"  , false);
  is_valid(__LINE__, "(@|@)(a|@)*"  , "ab"  , false);
  is_valid(__LINE__, "(@|@)(@|a)*"  , "ab"  , false);
  is_valid(__LINE__, "(@|@)(a|a)*"  , "ab"  , false);
  is_valid(__LINE__, "(a|@)(@|@)*"  , "ab"  , false);
  is_valid(__LINE__, "(a|@)(a|@)*"  , "ab"  , false);
  is_valid(__LINE__, "(a|@)(@|a)*"  , "ab"  , false);
  is_valid(__LINE__, "(a|@)(a|a)*"  , "ab"  , false);
  is_valid(__LINE__, "(@|a)(@|@)*"  , "ab"  , false);
  is_valid(__LINE__, "(@|a)(a|@)*"  , "ab"  , false);
  is_valid(__LINE__, "(@|a)(@|a)*"  , "ab"  , false);
  is_valid(__LINE__, "(@|a)(a|a)*"  , "ab"  , false);
  is_valid(__LINE__, "(a|a)(@|@)*"  , "ab"  , false);
  is_valid(__LINE__, "(a|a)(a|@)*"  , "ab"  , false);
  is_valid(__LINE__, "(a|a)(@|a)*"  , "ab"  , false);
  is_valid(__LINE__, "(a|a)(a|a)*"  , "ab"  , false);

  is_valid(__LINE__, "@*@*"         , "ab"  , false);
  is_valid(__LINE__, "@*a*"         , "ab"  , false);
  is_valid(__LINE__, "a*@*"         , "ab"  , false);
  is_valid(__LINE__, "a*a*"         , "ab"  , false);
  is_valid(__LINE__, "a*b*"         , "ab"  , true );
  is_valid(__LINE__, "(@|@)*(@|@)*" , "ab"  , false);
  is_valid(__LINE__, "(@|@)*(a|@)*" , "ab"  , false);
  is_valid(__LINE__, "(@|@)*(@|a)*" , "ab"  , false);
  is_valid(__LINE__, "(@|@)*(a|a)*" , "ab"  , false);
  is_valid(__LINE__, "(a|@)*(@|@)*" , "ab"  , false);
  is_valid(__LINE__, "(a|@)*(a|@)*" , "ab"  , false);
  is_valid(__LINE__, "(a|@)*(@|a)*" , "ab"  , false);
  is_valid(__LINE__, "(a|@)*(a|a)*" , "ab"  , false);
  is_valid(__LINE__, "(@|a)*(@|@)*" , "ab"  , false);
  is_valid(__LINE__, "(@|a)*(a|@)*" , "ab"  , false);
  is_valid(__LINE__, "(@|a)*(@|a)*" , "ab"  , false);
  is_valid(__LINE__, "(@|a)*(a|a)*" , "ab"  , false);
  is_valid(__LINE__, "(a|a)*(@|@)*" , "ab"  , false);
  is_valid(__LINE__, "(a|a)*(a|@)*" , "ab"  , false);
  is_valid(__LINE__, "(a|a)*(@|a)*" , "ab"  , false);
  is_valid(__LINE__, "(a|a)*(a|a)*" , "ab"  , false);/*}}}*/
  is_valid(__LINE__, ""             , "ba"  , false);/*{{{*/
  is_valid(__LINE__, "@"            , "ba"  , false);
  is_valid(__LINE__, "a"            , "ba"  , false);
  is_valid(__LINE__, "(@|@)"        , "ba"  , false);
  is_valid(__LINE__, "(a|@)"        , "ba"  , false);
  is_valid(__LINE__, "(@|a)"        , "ba"  , false);
  is_valid(__LINE__, "(a|a)"        , "ba"  , false);

  is_valid(__LINE__, "@*"           , "ba"  , false);
  is_valid(__LINE__, "a*"           , "ba"  , false);
  is_valid(__LINE__, "(@|@)*"       , "ba"  , false);
  is_valid(__LINE__, "(a|@)*"       , "ba"  , false);
  is_valid(__LINE__, "(@|a)*"       , "ba"  , false);
  is_valid(__LINE__, "(a|a)*"       , "ba"  , false);

  is_valid(__LINE__, "@@"           , "ba"  , false);
  is_valid(__LINE__, "@a"           , "ba"  , false);
  is_valid(__LINE__, "a@"           , "ba"  , false);
  is_valid(__LINE__, "aa"           , "ba"  , false);
  is_valid(__LINE__, "ab"           , "ba"  , false);
  is_valid(__LINE__, "(@|@)(@|@)"   , "ba"  , false);
  is_valid(__LINE__, "(@|@)(a|@)"   , "ba"  , false);
  is_valid(__LINE__, "(@|@)(@|a)"   , "ba"  , false);
  is_valid(__LINE__, "(@|@)(a|a)"   , "ba"  , false);
  is_valid(__LINE__, "(a|@)(@|@)"   , "ba"  , false);
  is_valid(__LINE__, "(a|@)(a|@)"   , "ba"  , false);
  is_valid(__LINE__, "(a|@)(@|a)"   , "ba"  , false);
  is_valid(__LINE__, "(a|@)(a|a)"   , "ba"  , false);
  is_valid(__LINE__, "(@|a)(@|@)"   , "ba"  , false);
  is_valid(__LINE__, "(@|a)(a|@)"   , "ba"  , false);
  is_valid(__LINE__, "(@|a)(@|a)"   , "ba"  , false);
  is_valid(__LINE__, "(@|a)(a|a)"   , "ba"  , false);
  is_valid(__LINE__, "(a|a)(@|@)"   , "ba"  , false);
  is_valid(__LINE__, "(a|a)(a|@)"   , "ba"  , false);
  is_valid(__LINE__, "(a|a)(@|a)"   , "ba"  , false);
  is_valid(__LINE__, "(a|a)(a|a)"   , "ba"  , false);

  is_valid(__LINE__, "@*@"          , "ba"  , false);
  is_valid(__LINE__, "@*a"          , "ba"  , false);
  is_valid(__LINE__, "a*@"          , "ba"  , false);
  is_valid(__LINE__, "a*a"          , "ba"  , false);
  is_valid(__LINE__, "a*b"          , "ba"  , false);
  is_valid(__LINE__, "(@|@)*(@|@)"  , "ba"  , false);
  is_valid(__LINE__, "(@|@)*(a|@)"  , "ba"  , false);
  is_valid(__LINE__, "(@|@)*(@|a)"  , "ba"  , false);
  is_valid(__LINE__, "(@|@)*(a|a)"  , "ba"  , false);
  is_valid(__LINE__, "(a|@)*(@|@)"  , "ba"  , false);
  is_valid(__LINE__, "(a|@)*(a|@)"  , "ba"  , false);
  is_valid(__LINE__, "(a|@)*(@|a)"  , "ba"  , false);
  is_valid(__LINE__, "(a|@)*(a|a)"  , "ba"  , false);
  is_valid(__LINE__, "(@|a)*(@|@)"  , "ba"  , false);
  is_valid(__LINE__, "(@|a)*(a|@)"  , "ba"  , false);
  is_valid(__LINE__, "(@|a)*(@|a)"  , "ba"  , false);
  is_valid(__LINE__, "(@|a)*(a|a)"  , "ba"  , false);
  is_valid(__LINE__, "(a|a)*(@|@)"  , "ba"  , false);
  is_valid(__LINE__, "(a|a)*(a|@)"  , "ba"  , false);
  is_valid(__LINE__, "(a|a)*(@|a)"  , "ba"  , false);
  is_valid(__LINE__, "(a|a)*(a|a)"  , "ba"  , false);

  is_valid(__LINE__, "@@*"          , "ba"  , false);
  is_valid(__LINE__, "@a*"          , "ba"  , false);
  is_valid(__LINE__, "a@*"          , "ba"  , false);
  is_valid(__LINE__, "aa*"          , "ba"  , false);
  is_valid(__LINE__, "ab*"          , "ba"  , false);
  is_valid(__LINE__, "(@|@)(@|@)*"  , "ba"  , false);
  is_valid(__LINE__, "(@|@)(a|@)*"  , "ba"  , false);
  is_valid(__LINE__, "(@|@)(@|a)*"  , "ba"  , false);
  is_valid(__LINE__, "(@|@)(a|a)*"  , "ba"  , false);
  is_valid(__LINE__, "(a|@)(@|@)*"  , "ba"  , false);
  is_valid(__LINE__, "(a|@)(a|@)*"  , "ba"  , false);
  is_valid(__LINE__, "(a|@)(@|a)*"  , "ba"  , false);
  is_valid(__LINE__, "(a|@)(a|a)*"  , "ba"  , false);
  is_valid(__LINE__, "(@|a)(@|@)*"  , "ba"  , false);
  is_valid(__LINE__, "(@|a)(a|@)*"  , "ba"  , false);
  is_valid(__LINE__, "(@|a)(@|a)*"  , "ba"  , false);
  is_valid(__LINE__, "(@|a)(a|a)*"  , "ba"  , false);
  is_valid(__LINE__, "(a|a)(@|@)*"  , "ba"  , false);
  is_valid(__LINE__, "(a|a)(a|@)*"  , "ba"  , false);
  is_valid(__LINE__, "(a|a)(@|a)*"  , "ba"  , false);
  is_valid(__LINE__, "(a|a)(a|a)*"  , "ba"  , false);

  is_valid(__LINE__, "@*@*"         , "ba"  , false);
  is_valid(__LINE__, "@*a*"         , "ba"  , false);
  is_valid(__LINE__, "a*@*"         , "ba"  , false);
  is_valid(__LINE__, "a*a*"         , "ba"  , false);
  is_valid(__LINE__, "a*b*"         , "ba"  , false);
  is_valid(__LINE__, "(@|@)*(@|@)*" , "ba"  , false);
  is_valid(__LINE__, "(@|@)*(a|@)*" , "ba"  , false);
  is_valid(__LINE__, "(@|@)*(@|a)*" , "ba"  , false);
  is_valid(__LINE__, "(@|@)*(a|a)*" , "ba"  , false);
  is_valid(__LINE__, "(a|@)*(@|@)*" , "ba"  , false);
  is_valid(__LINE__, "(a|@)*(a|@)*" , "ba"  , false);
  is_valid(__LINE__, "(a|@)*(@|a)*" , "ba"  , false);
  is_valid(__LINE__, "(a|@)*(a|a)*" , "ba"  , false);
  is_valid(__LINE__, "(@|a)*(@|@)*" , "ba"  , false);
  is_valid(__LINE__, "(@|a)*(a|@)*" , "ba"  , false);
  is_valid(__LINE__, "(@|a)*(@|a)*" , "ba"  , false);
  is_valid(__LINE__, "(@|a)*(a|a)*" , "ba"  , false);
  is_valid(__LINE__, "(a|a)*(@|@)*" , "ba"  , false);
  is_valid(__LINE__, "(a|a)*(a|@)*" , "ba"  , false);
  is_valid(__LINE__, "(a|a)*(@|a)*" , "ba"  , false);
  is_valid(__LINE__, "(a|a)*(a|a)*" , "ba"  , false);/*}}}*/

  // エスケープシーケンス
  is_valid(__LINE__,  "\\\\", "a"     , false);/*{{{*/
  is_valid(__LINE__,  "\\\\", "aa"    , false);
  is_valid(__LINE__,  "\\\\", "aaa"   , false);
  is_valid(__LINE__,  "\\\\", "ab"    , false);
  is_valid(__LINE__,  "\\\\", "aba"   , false);
  is_valid(__LINE__,  "\\\\", "\\\\"  , false);
  is_valid(__LINE__,  "\\\\", "\\("   , false);
  is_valid(__LINE__,  "\\\\", "\\)"   , false);
  is_valid(__LINE__,  "\\\\", "\\|"   , false);
  is_valid(__LINE__,  "\\\\", "\\*"   , false);
  is_valid(__LINE__,  "\\\\", "\\@"   , false);
  is_valid(__LINE__,  "\\\\", "a\\\\" , false);
  is_valid(__LINE__,  "\\\\", "a\\("  , false);
  is_valid(__LINE__,  "\\\\", "a\\)"  , false);
  is_valid(__LINE__,  "\\\\", "a\\|"  , false);
  is_valid(__LINE__,  "\\\\", "a\\*"  , false);
  is_valid(__LINE__,  "\\\\", "a\\@"  , false);
  is_valid(__LINE__,  "\\\\", "\\(a"  , false);
  is_valid(__LINE__,  "\\\\", "\\)a"  , false);
  is_valid(__LINE__,  "\\\\", "\\|a"  , false);
  is_valid(__LINE__,  "\\\\", "\\*a"  , false);
  is_valid(__LINE__,  "\\\\", "\\@a"  , false);
  is_valid(__LINE__,  "\\\\", "\\"    , true );
  is_valid(__LINE__,  "\\\\", "("     , false);
  is_valid(__LINE__,  "\\\\", ")"     , false);
  is_valid(__LINE__,  "\\\\", "|"     , false);
  is_valid(__LINE__,  "\\\\", "*"     , false);
  is_valid(__LINE__,  "\\\\", "@"     , false);
  is_valid(__LINE__,  "\\\\", "a\\"   , false);
  is_valid(__LINE__,  "\\\\", "a("    , false);
  is_valid(__LINE__,  "\\\\", "a)"    , false);
  is_valid(__LINE__,  "\\\\", "a|"    , false);
  is_valid(__LINE__,  "\\\\", "a*"    , false);
  is_valid(__LINE__,  "\\\\", "a@"    , false);
  is_valid(__LINE__,  "\\\\", "(a"    , false);
  is_valid(__LINE__,  "\\\\", ")a"    , false);
  is_valid(__LINE__,  "\\\\", "|a"    , false);
  is_valid(__LINE__,  "\\\\", "*a"    , false);
  is_valid(__LINE__,  "\\\\", "@a"    , false);

  is_valid(__LINE__, "a\\\\", "a"     , false);
  is_valid(__LINE__, "a\\\\", "aa"    , false);
  is_valid(__LINE__, "a\\\\", "aaa"   , false);
  is_valid(__LINE__, "a\\\\", "ab"    , false);
  is_valid(__LINE__, "a\\\\", "aba"   , false);
  is_valid(__LINE__, "a\\\\", "\\\\"  , false);
  is_valid(__LINE__, "a\\\\", "\\("   , false);
  is_valid(__LINE__, "a\\\\", "\\)"   , false);
  is_valid(__LINE__, "a\\\\", "\\|"   , false);
  is_valid(__LINE__, "a\\\\", "\\*"   , false);
  is_valid(__LINE__, "a\\\\", "\\@"   , false);
  is_valid(__LINE__, "a\\\\", "a\\\\" , false);
  is_valid(__LINE__, "a\\\\", "a\\("  , false);
  is_valid(__LINE__, "a\\\\", "a\\)"  , false);
  is_valid(__LINE__, "a\\\\", "a\\|"  , false);
  is_valid(__LINE__, "a\\\\", "a\\*"  , false);
  is_valid(__LINE__, "a\\\\", "a\\@"  , false);
  is_valid(__LINE__, "a\\\\", "\\\\a" , false);
  is_valid(__LINE__, "a\\\\", "\\(a"  , false);
  is_valid(__LINE__, "a\\\\", "\\)a"  , false);
  is_valid(__LINE__, "a\\\\", "\\|a"  , false);
  is_valid(__LINE__, "a\\\\", "\\*a"  , false);
  is_valid(__LINE__, "a\\\\", "\\@a"  , false);
  is_valid(__LINE__, "a\\\\", "\\"    , false);
  is_valid(__LINE__, "a\\\\", "("     , false);
  is_valid(__LINE__, "a\\\\", ")"     , false);
  is_valid(__LINE__, "a\\\\", "|"     , false);
  is_valid(__LINE__, "a\\\\", "*"     , false);
  is_valid(__LINE__, "a\\\\", "@"     , false);
  is_valid(__LINE__, "a\\\\", "a\\"   , true );
  is_valid(__LINE__, "a\\\\", "a("    , false);
  is_valid(__LINE__, "a\\\\", "a)"    , false);
  is_valid(__LINE__, "a\\\\", "a|"    , false);
  is_valid(__LINE__, "a\\\\", "a*"    , false);
  is_valid(__LINE__, "a\\\\", "a@"    , false);
  is_valid(__LINE__, "a\\\\", "\\a"   , false);
  is_valid(__LINE__, "a\\\\", "(a"    , false);
  is_valid(__LINE__, "a\\\\", ")a"    , false);
  is_valid(__LINE__, "a\\\\", "|a"    , false);
  is_valid(__LINE__, "a\\\\", "*a"    , false);
  is_valid(__LINE__, "a\\\\", "@a"    , false);

  is_valid(__LINE__, "\\\\a", "a"     , false);
  is_valid(__LINE__, "\\\\a", "aa"    , false);
  is_valid(__LINE__, "\\\\a", "aaa"   , false);
  is_valid(__LINE__, "\\\\a", "ab"    , false);
  is_valid(__LINE__, "\\\\a", "aba"   , false);
  is_valid(__LINE__, "\\\\a", "\\\\"  , false);
  is_valid(__LINE__, "\\\\a", "\\("   , false);
  is_valid(__LINE__, "\\\\a", "\\)"   , false);
  is_valid(__LINE__, "\\\\a", "\\|"   , false);
  is_valid(__LINE__, "\\\\a", "\\*"   , false);
  is_valid(__LINE__, "\\\\a", "\\@"   , false);
  is_valid(__LINE__, "\\\\a", "a\\\\" , false);
  is_valid(__LINE__, "\\\\a", "a\\("  , false);
  is_valid(__LINE__, "\\\\a", "a\\)"  , false);
  is_valid(__LINE__, "\\\\a", "a\\|"  , false);
  is_valid(__LINE__, "\\\\a", "a\\*"  , false);
  is_valid(__LINE__, "\\\\a", "a\\@"  , false);
  is_valid(__LINE__, "\\\\a", "\\\\a" , false);
  is_valid(__LINE__, "\\\\a", "\\(a"  , false);
  is_valid(__LINE__, "\\\\a", "\\)a"  , false);
  is_valid(__LINE__, "\\\\a", "\\|a"  , false);
  is_valid(__LINE__, "\\\\a", "\\*a"  , false);
  is_valid(__LINE__, "\\\\a", "@a"    , false);
  is_valid(__LINE__, "\\\\a", "\\"    , false);
  is_valid(__LINE__, "\\\\a", "("     , false);
  is_valid(__LINE__, "\\\\a", ")"     , false);
  is_valid(__LINE__, "\\\\a", "|"     , false);
  is_valid(__LINE__, "\\\\a", "*"     , false);
  is_valid(__LINE__, "\\\\a", "@"     , false);
  is_valid(__LINE__, "\\\\a", "a\\"   , false);
  is_valid(__LINE__, "\\\\a", "a("    , false);
  is_valid(__LINE__, "\\\\a", "a)"    , false);
  is_valid(__LINE__, "\\\\a", "a|"    , false);
  is_valid(__LINE__, "\\\\a", "a*"    , false);
  is_valid(__LINE__, "\\\\a", "a@"    , false);
  is_valid(__LINE__, "\\\\a", "\\a"   , true );
  is_valid(__LINE__, "\\\\a", "(a"    , false);
  is_valid(__LINE__, "\\\\a", ")a"    , false);
  is_valid(__LINE__, "\\\\a", "|a"    , false);
  is_valid(__LINE__, "\\\\a", "*a"    , false);
  is_valid(__LINE__, "\\\\a", "@a"    , false);/*}}}*/
  is_valid(__LINE__,  "\\(" , "a"     , false);/*{{{*/
  is_valid(__LINE__,  "\\(" , "aa"    , false);
  is_valid(__LINE__,  "\\(" , "aaa"   , false);
  is_valid(__LINE__,  "\\(" , "ab"    , false);
  is_valid(__LINE__,  "\\(" , "aba"   , false);
  is_valid(__LINE__,  "\\(" , "\\\\"  , false);
  is_valid(__LINE__,  "\\(" , "\\("   , false);
  is_valid(__LINE__,  "\\(" , "\\)"   , false);
  is_valid(__LINE__,  "\\(" , "\\|"   , false);
  is_valid(__LINE__,  "\\(" , "\\*"   , false);
  is_valid(__LINE__,  "\\(" , "\\@"   , false);
  is_valid(__LINE__,  "\\(" , "a\\\\" , false);
  is_valid(__LINE__,  "\\(" , "a\\("  , false);
  is_valid(__LINE__,  "\\(" , "a\\)"  , false);
  is_valid(__LINE__,  "\\(" , "a\\|"  , false);
  is_valid(__LINE__,  "\\(" , "a\\*"  , false);
  is_valid(__LINE__,  "\\(" , "a\\@"  , false);
  is_valid(__LINE__,  "\\(" , "\\\\a" , false);
  is_valid(__LINE__,  "\\(" , "\\(a"  , false);
  is_valid(__LINE__,  "\\(" , "\\)a"  , false);
  is_valid(__LINE__,  "\\(" , "\\|a"  , false);
  is_valid(__LINE__,  "\\(" , "\\*a"  , false);
  is_valid(__LINE__,  "\\(" , "\\@a"  , false);
  is_valid(__LINE__,  "\\(" , "\\"    , false);
  is_valid(__LINE__,  "\\(" , "("     , true );
  is_valid(__LINE__,  "\\(" , ")"     , false);
  is_valid(__LINE__,  "\\(" , "|"     , false);
  is_valid(__LINE__,  "\\(" , "*"     , false);
  is_valid(__LINE__,  "\\(" , "@"     , false);
  is_valid(__LINE__,  "\\(" , "a\\"   , false);
  is_valid(__LINE__,  "\\(" , "a("    , false);
  is_valid(__LINE__,  "\\(" , "a)"    , false);
  is_valid(__LINE__,  "\\(" , "a|"    , false);
  is_valid(__LINE__,  "\\(" , "a*"    , false);
  is_valid(__LINE__,  "\\(" , "a@"    , false);
  is_valid(__LINE__,  "\\(" , "\\a"   , false);
  is_valid(__LINE__,  "\\(" , "(a"    , false);
  is_valid(__LINE__,  "\\(" , ")a"    , false);
  is_valid(__LINE__,  "\\(" , "|a"    , false);
  is_valid(__LINE__,  "\\(" , "*a"    , false);
  is_valid(__LINE__,  "\\(" , "@a"    , false);

  is_valid(__LINE__, "a\\(" , "a"     , false);
  is_valid(__LINE__, "a\\(" , "aa"    , false);
  is_valid(__LINE__, "a\\(" , "aaa"   , false);
  is_valid(__LINE__, "a\\(" , "ab"    , false);
  is_valid(__LINE__, "a\\(" , "aba"   , false);
  is_valid(__LINE__, "a\\(" , "\\\\"  , false);
  is_valid(__LINE__, "a\\(" , "\\("   , false);
  is_valid(__LINE__, "a\\(" , "\\)"   , false);
  is_valid(__LINE__, "a\\(" , "\\|"   , false);
  is_valid(__LINE__, "a\\(" , "\\*"   , false);
  is_valid(__LINE__, "a\\(" , "\\@"   , false);
  is_valid(__LINE__, "a\\(" , "a\\\\" , false);
  is_valid(__LINE__, "a\\(" , "a\\("  , false);
  is_valid(__LINE__, "a\\(" , "a\\)"  , false);
  is_valid(__LINE__, "a\\(" , "a\\|"  , false);
  is_valid(__LINE__, "a\\(" , "a\\*"  , false);
  is_valid(__LINE__, "a\\(" , "a\\@"  , false);
  is_valid(__LINE__, "a\\(" , "\\\\a" , false);
  is_valid(__LINE__, "a\\(" , "\\(a"  , false);
  is_valid(__LINE__, "a\\(" , "\\)a"  , false);
  is_valid(__LINE__, "a\\(" , "\\|a"  , false);
  is_valid(__LINE__, "a\\(" , "\\*a"  , false);
  is_valid(__LINE__, "a\\(" , "\\@a"  , false);
  is_valid(__LINE__, "a\\(" , "\\"    , false);
  is_valid(__LINE__, "a\\(" , "("     , false);
  is_valid(__LINE__, "a\\(" , ")"     , false);
  is_valid(__LINE__, "a\\(" , "|"     , false);
  is_valid(__LINE__, "a\\(" , "*"     , false);
  is_valid(__LINE__, "a\\(" , "@"     , false);
  is_valid(__LINE__, "a\\(" , "a\\"   , false);
  is_valid(__LINE__, "a\\(" , "a("    , true );
  is_valid(__LINE__, "a\\(" , "a)"    , false);
  is_valid(__LINE__, "a\\(" , "a|"    , false);
  is_valid(__LINE__, "a\\(" , "a*"    , false);
  is_valid(__LINE__, "a\\(" , "a@"    , false);
  is_valid(__LINE__, "a\\(" , "\\a"   , false);
  is_valid(__LINE__, "a\\(" , "(a"    , false);
  is_valid(__LINE__, "a\\(" , ")a"    , false);
  is_valid(__LINE__, "a\\(" , "|a"    , false);
  is_valid(__LINE__, "a\\(" , "*a"    , false);
  is_valid(__LINE__, "a\\(" , "@a"    , false);

  is_valid(__LINE__, "\\(a" , "a"     , false);
  is_valid(__LINE__, "\\(a" , "aa"    , false);
  is_valid(__LINE__, "\\(a" , "aaa"   , false);
  is_valid(__LINE__, "\\(a" , "ab"    , false);
  is_valid(__LINE__, "\\(a" , "aba"   , false);
  is_valid(__LINE__, "\\(a" , "\\\\"  , false);
  is_valid(__LINE__, "\\(a" , "\\("   , false);
  is_valid(__LINE__, "\\(a" , "\\)"   , false);
  is_valid(__LINE__, "\\(a" , "\\|"   , false);
  is_valid(__LINE__, "\\(a" , "\\*"   , false);
  is_valid(__LINE__, "\\(a" , "\\@"   , false);
  is_valid(__LINE__, "\\(a" , "a\\\\" , false);
  is_valid(__LINE__, "\\(a" , "a\\("  , false);
  is_valid(__LINE__, "\\(a" , "a\\)"  , false);
  is_valid(__LINE__, "\\(a" , "a\\|"  , false);
  is_valid(__LINE__, "\\(a" , "a\\*"  , false);
  is_valid(__LINE__, "\\(a" , "a\\@"  , false);
  is_valid(__LINE__, "\\(a" , "\\\\a" , false);
  is_valid(__LINE__, "\\(a" , "\\(a"  , false);
  is_valid(__LINE__, "\\(a" , "\\)a"  , false);
  is_valid(__LINE__, "\\(a" , "\\|a"  , false);
  is_valid(__LINE__, "\\(a" , "\\*a"  , false);
  is_valid(__LINE__, "\\(a" , "\\@a"  , false);
  is_valid(__LINE__, "\\(a" , "\\"    , false);
  is_valid(__LINE__, "\\(a" , "("     , false);
  is_valid(__LINE__, "\\(a" , ")"     , false);
  is_valid(__LINE__, "\\(a" , "|"     , false);
  is_valid(__LINE__, "\\(a" , "*"     , false);
  is_valid(__LINE__, "\\(a" , "@"     , false);
  is_valid(__LINE__, "\\(a" , "a\\"   , false);
  is_valid(__LINE__, "\\(a" , "a("    , false);
  is_valid(__LINE__, "\\(a" , "a)"    , false);
  is_valid(__LINE__, "\\(a" , "a|"    , false);
  is_valid(__LINE__, "\\(a" , "a*"    , false);
  is_valid(__LINE__, "\\(a" , "a@"    , false);
  is_valid(__LINE__, "\\(a" , "\\a"   , false);
  is_valid(__LINE__, "\\(a" , "(a"    , true );
  is_valid(__LINE__, "\\(a" , ")a"    , false);
  is_valid(__LINE__, "\\(a" , "|a"    , false);
  is_valid(__LINE__, "\\(a" , "*a"    , false);
  is_valid(__LINE__, "\\(a" , "@a"    , false);/*}}}*/
  is_valid(__LINE__,  "\\)" , "a"     , false);/*{{{*/
  is_valid(__LINE__,  "\\)" , "aa"    , false);
  is_valid(__LINE__,  "\\)" , "aaa"   , false);
  is_valid(__LINE__,  "\\)" , "ab"    , false);
  is_valid(__LINE__,  "\\)" , "aba"   , false);
  is_valid(__LINE__,  "\\)" , "\\\\"  , false);
  is_valid(__LINE__,  "\\)" , "\\("   , false);
  is_valid(__LINE__,  "\\)" , "\\)"   , false);
  is_valid(__LINE__,  "\\)" , "\\|"   , false);
  is_valid(__LINE__,  "\\)" , "\\*"   , false);
  is_valid(__LINE__,  "\\)" , "\\@"   , false);
  is_valid(__LINE__,  "\\)" , "a\\\\" , false);
  is_valid(__LINE__,  "\\)" , "a\\("  , false);
  is_valid(__LINE__,  "\\)" , "a\\)"  , false);
  is_valid(__LINE__,  "\\)" , "a\\|"  , false);
  is_valid(__LINE__,  "\\)" , "a\\*"  , false);
  is_valid(__LINE__,  "\\)" , "a\\@"  , false);
  is_valid(__LINE__,  "\\)" , "\\\\a" , false);
  is_valid(__LINE__,  "\\)" , "\\(a"  , false);
  is_valid(__LINE__,  "\\)" , "\\)a"  , false);
  is_valid(__LINE__,  "\\)" , "\\|a"  , false);
  is_valid(__LINE__,  "\\)" , "\\*a"  , false);
  is_valid(__LINE__,  "\\)" , "\\@a"  , false);
  is_valid(__LINE__,  "\\)" , "\\"    , false);
  is_valid(__LINE__,  "\\)" , "("     , false);
  is_valid(__LINE__,  "\\)" , ")"     , true );
  is_valid(__LINE__,  "\\)" , "|"     , false);
  is_valid(__LINE__,  "\\)" , "*"     , false);
  is_valid(__LINE__,  "\\)" , "@"     , false);
  is_valid(__LINE__,  "\\)" , "a\\"   , false);
  is_valid(__LINE__,  "\\)" , "a("    , false);
  is_valid(__LINE__,  "\\)" , "a)"    , false);
  is_valid(__LINE__,  "\\)" , "a|"    , false);
  is_valid(__LINE__,  "\\)" , "a*"    , false);
  is_valid(__LINE__,  "\\)" , "a@"    , false);
  is_valid(__LINE__,  "\\)" , "\\a"   , false);
  is_valid(__LINE__,  "\\)" , "(a"    , false);
  is_valid(__LINE__,  "\\)" , ")a"    , false);
  is_valid(__LINE__,  "\\)" , "|a"    , false);
  is_valid(__LINE__,  "\\)" , "*a"    , false);
  is_valid(__LINE__,  "\\)" , "@a"    , false);

  is_valid(__LINE__, "a\\)" , "a"     , false);
  is_valid(__LINE__, "a\\)" , "aa"    , false);
  is_valid(__LINE__, "a\\)" , "aaa"   , false);
  is_valid(__LINE__, "a\\)" , "ab"    , false);
  is_valid(__LINE__, "a\\)" , "aba"   , false);
  is_valid(__LINE__, "a\\)" , "\\\\"  , false);
  is_valid(__LINE__, "a\\)" , "\\("   , false);
  is_valid(__LINE__, "a\\)" , "\\)"   , false);
  is_valid(__LINE__, "a\\)" , "\\|"   , false);
  is_valid(__LINE__, "a\\)" , "\\*"   , false);
  is_valid(__LINE__, "a\\)" , "\\@"   , false);
  is_valid(__LINE__, "a\\)" , "a\\\\" , false);
  is_valid(__LINE__, "a\\)" , "a\\("  , false);
  is_valid(__LINE__, "a\\)" , "a\\)"  , false);
  is_valid(__LINE__, "a\\)" , "a\\|"  , false);
  is_valid(__LINE__, "a\\)" , "a\\*"  , false);
  is_valid(__LINE__, "a\\)" , "a\\@"  , false);
  is_valid(__LINE__, "a\\)" , "\\\\a" , false);
  is_valid(__LINE__, "a\\)" , "\\(a"  , false);
  is_valid(__LINE__, "a\\)" , "\\)a"  , false);
  is_valid(__LINE__, "a\\)" , "\\|a"  , false);
  is_valid(__LINE__, "a\\)" , "\\*a"  , false);
  is_valid(__LINE__, "a\\)" , "\\@a"  , false);
  is_valid(__LINE__, "a\\)" , "\\"    , false);
  is_valid(__LINE__, "a\\)" , "("     , false);
  is_valid(__LINE__, "a\\)" , ")"     , false);
  is_valid(__LINE__, "a\\)" , "|"     , false);
  is_valid(__LINE__, "a\\)" , "*"     , false);
  is_valid(__LINE__, "a\\)" , "@"     , false);
  is_valid(__LINE__, "a\\)" , "a\\"   , false);
  is_valid(__LINE__, "a\\)" , "a("    , false);
  is_valid(__LINE__, "a\\)" , "a)"    , true );
  is_valid(__LINE__, "a\\)" , "a|"    , false);
  is_valid(__LINE__, "a\\)" , "a*"    , false);
  is_valid(__LINE__, "a\\)" , "a@"    , false);
  is_valid(__LINE__, "a\\)" , "\\a"   , false);
  is_valid(__LINE__, "a\\)" , "(a"    , false);
  is_valid(__LINE__, "a\\)" , ")a"    , false);
  is_valid(__LINE__, "a\\)" , "|a"    , false);
  is_valid(__LINE__, "a\\)" , "*a"    , false);
  is_valid(__LINE__, "a\\)" , "@a"    , false);

  is_valid(__LINE__, "\\)a" , "a"     , false);
  is_valid(__LINE__, "\\)a" , "aa"    , false);
  is_valid(__LINE__, "\\)a" , "aaa"   , false);
  is_valid(__LINE__, "\\)a" , "ab"    , false);
  is_valid(__LINE__, "\\)a" , "aba"   , false);
  is_valid(__LINE__, "\\)a" , "\\\\"  , false);
  is_valid(__LINE__, "\\)a" , "\\("   , false);
  is_valid(__LINE__, "\\)a" , "\\)"   , false);
  is_valid(__LINE__, "\\)a" , "\\|"   , false);
  is_valid(__LINE__, "\\)a" , "\\*"   , false);
  is_valid(__LINE__, "\\)a" , "\\@"   , false);
  is_valid(__LINE__, "\\)a" , "a\\\\" , false);
  is_valid(__LINE__, "\\)a" , "a\\("  , false);
  is_valid(__LINE__, "\\)a" , "a\\)"  , false);
  is_valid(__LINE__, "\\)a" , "a\\|"  , false);
  is_valid(__LINE__, "\\)a" , "a\\*"  , false);
  is_valid(__LINE__, "\\)a" , "a\\@"  , false);
  is_valid(__LINE__, "\\)a" , "\\\\a" , false);
  is_valid(__LINE__, "\\)a" , "\\(a"  , false);
  is_valid(__LINE__, "\\)a" , "\\)a"  , false);
  is_valid(__LINE__, "\\)a" , "\\|a"  , false);
  is_valid(__LINE__, "\\)a" , "\\*a"  , false);
  is_valid(__LINE__, "\\)a" , "\\@a"  , false);
  is_valid(__LINE__, "\\)a" , "\\"    , false);
  is_valid(__LINE__, "\\)a" , "("     , false);
  is_valid(__LINE__, "\\)a" , ")"     , false);
  is_valid(__LINE__, "\\)a" , "|"     , false);
  is_valid(__LINE__, "\\)a" , "*"     , false);
  is_valid(__LINE__, "\\)a" , "@"     , false);
  is_valid(__LINE__, "\\)a" , "a\\"   , false);
  is_valid(__LINE__, "\\)a" , "a("    , false);
  is_valid(__LINE__, "\\)a" , "a)"    , false);
  is_valid(__LINE__, "\\)a" , "a|"    , false);
  is_valid(__LINE__, "\\)a" , "a*"    , false);
  is_valid(__LINE__, "\\)a" , "a@"    , false);
  is_valid(__LINE__, "\\)a" , "\\a"   , false);
  is_valid(__LINE__, "\\)a" , "(a"    , false);
  is_valid(__LINE__, "\\)a" , ")a"    , true );
  is_valid(__LINE__, "\\)a" , "|a"    , false);
  is_valid(__LINE__, "\\)a" , "*a"    , false);
  is_valid(__LINE__, "\\)a" , "@a"    , false);/*}}}*/
  is_valid(__LINE__,  "\\|" , "a"     , false);/*{{{*/
  is_valid(__LINE__,  "\\|" , "aa"    , false);
  is_valid(__LINE__,  "\\|" , "aaa"   , false);
  is_valid(__LINE__,  "\\|" , "ab"    , false);
  is_valid(__LINE__,  "\\|" , "aba"   , false);
  is_valid(__LINE__,  "\\|" , "\\\\"  , false);
  is_valid(__LINE__,  "\\|" , "\\("   , false);
  is_valid(__LINE__,  "\\|" , "\\)"   , false);
  is_valid(__LINE__,  "\\|" , "\\|"   , false);
  is_valid(__LINE__,  "\\|" , "\\*"   , false);
  is_valid(__LINE__,  "\\|" , "\\@"   , false);
  is_valid(__LINE__,  "\\|" , "a\\\\" , false);
  is_valid(__LINE__,  "\\|" , "a\\("  , false);
  is_valid(__LINE__,  "\\|" , "a\\)"  , false);
  is_valid(__LINE__,  "\\|" , "a\\|"  , false);
  is_valid(__LINE__,  "\\|" , "a\\*"  , false);
  is_valid(__LINE__,  "\\|" , "a\\@"  , false);
  is_valid(__LINE__,  "\\|" , "\\\\a" , false);
  is_valid(__LINE__,  "\\|" , "\\(a"  , false);
  is_valid(__LINE__,  "\\|" , "\\)a"  , false);
  is_valid(__LINE__,  "\\|" , "\\|a"  , false);
  is_valid(__LINE__,  "\\|" , "\\*a"  , false);
  is_valid(__LINE__,  "\\|" , "\\@a"  , false);
  is_valid(__LINE__,  "\\|" , "\\"    , false);
  is_valid(__LINE__,  "\\|" , "("     , false);
  is_valid(__LINE__,  "\\|" , ")"     , false);
  is_valid(__LINE__,  "\\|" , "|"     , true );
  is_valid(__LINE__,  "\\|" , "*"     , false);
  is_valid(__LINE__,  "\\|" , "@"     , false);
  is_valid(__LINE__,  "\\|" , "a\\"   , false);
  is_valid(__LINE__,  "\\|" , "a("    , false);
  is_valid(__LINE__,  "\\|" , "a)"    , false);
  is_valid(__LINE__,  "\\|" , "a|"    , false);
  is_valid(__LINE__,  "\\|" , "a*"    , false);
  is_valid(__LINE__,  "\\|" , "a@"    , false);
  is_valid(__LINE__,  "\\|" , "\\a"   , false);
  is_valid(__LINE__,  "\\|" , "(a"    , false);
  is_valid(__LINE__,  "\\|" , ")a"    , false);
  is_valid(__LINE__,  "\\|" , "|a"    , false);
  is_valid(__LINE__,  "\\|" , "*a"    , false);
  is_valid(__LINE__,  "\\|" , "@a"    , false);

  is_valid(__LINE__, "a\\|" , "a"     , false);
  is_valid(__LINE__, "a\\|" , "aa"    , false);
  is_valid(__LINE__, "a\\|" , "aaa"   , false);
  is_valid(__LINE__, "a\\|" , "ab"    , false);
  is_valid(__LINE__, "a\\|" , "aba"   , false);
  is_valid(__LINE__, "a\\|" , "\\\\"  , false);
  is_valid(__LINE__, "a\\|" , "\\("   , false);
  is_valid(__LINE__, "a\\|" , "\\)"   , false);
  is_valid(__LINE__, "a\\|" , "\\|"   , false);
  is_valid(__LINE__, "a\\|" , "\\*"   , false);
  is_valid(__LINE__, "a\\|" , "\\@"   , false);
  is_valid(__LINE__, "a\\|" , "a\\\\" , false);
  is_valid(__LINE__, "a\\|" , "a\\("  , false);
  is_valid(__LINE__, "a\\|" , "a\\)"  , false);
  is_valid(__LINE__, "a\\|" , "a\\|"  , false);
  is_valid(__LINE__, "a\\|" , "a\\*"  , false);
  is_valid(__LINE__, "a\\|" , "a\\@"  , false);
  is_valid(__LINE__, "a\\|" , "\\\\a" , false);
  is_valid(__LINE__, "a\\|" , "\\(a"  , false);
  is_valid(__LINE__, "a\\|" , "\\)a"  , false);
  is_valid(__LINE__, "a\\|" , "\\|a"  , false);
  is_valid(__LINE__, "a\\|" , "\\*a"  , false);
  is_valid(__LINE__, "a\\|" , "\\@a"  , false);
  is_valid(__LINE__, "a\\|" , "\\"    , false);
  is_valid(__LINE__, "a\\|" , "("     , false);
  is_valid(__LINE__, "a\\|" , ")"     , false);
  is_valid(__LINE__, "a\\|" , "|"     , false);
  is_valid(__LINE__, "a\\|" , "*"     , false);
  is_valid(__LINE__, "a\\|" , "@"     , false);
  is_valid(__LINE__, "a\\|" , "a\\"   , false);
  is_valid(__LINE__, "a\\|" , "a("    , false);
  is_valid(__LINE__, "a\\|" , "a)"    , false);
  is_valid(__LINE__, "a\\|" , "a|"    , true );
  is_valid(__LINE__, "a\\|" , "a*"    , false);
  is_valid(__LINE__, "a\\|" , "a@"    , false);
  is_valid(__LINE__, "a\\|" , "\\a"   , false);
  is_valid(__LINE__, "a\\|" , "(a"    , false);
  is_valid(__LINE__, "a\\|" , ")a"    , false);
  is_valid(__LINE__, "a\\|" , "|a"    , false);
  is_valid(__LINE__, "a\\|" , "*a"    , false);
  is_valid(__LINE__, "a\\|" , "@a"    , false);

  is_valid(__LINE__, "\\|a" , "a"     , false);
  is_valid(__LINE__, "\\|a" , "aa"    , false);
  is_valid(__LINE__, "\\|a" , "aaa"   , false);
  is_valid(__LINE__, "\\|a" , "ab"    , false);
  is_valid(__LINE__, "\\|a" , "aba"   , false);
  is_valid(__LINE__, "\\|a" , "\\\\"  , false);
  is_valid(__LINE__, "\\|a" , "\\("   , false);
  is_valid(__LINE__, "\\|a" , "\\)"   , false);
  is_valid(__LINE__, "\\|a" , "\\|"   , false);
  is_valid(__LINE__, "\\|a" , "\\*"   , false);
  is_valid(__LINE__, "\\|a" , "\\@"   , false);
  is_valid(__LINE__, "\\|a" , "a\\\\" , false);
  is_valid(__LINE__, "\\|a" , "a\\("  , false);
  is_valid(__LINE__, "\\|a" , "a\\)"  , false);
  is_valid(__LINE__, "\\|a" , "a\\|"  , false);
  is_valid(__LINE__, "\\|a" , "a\\*"  , false);
  is_valid(__LINE__, "\\|a" , "a\\@"  , false);
  is_valid(__LINE__, "\\|a" , "\\\\a" , false);
  is_valid(__LINE__, "\\|a" , "\\(a"  , false);
  is_valid(__LINE__, "\\|a" , "\\)a"  , false);
  is_valid(__LINE__, "\\|a" , "\\|a"  , false);
  is_valid(__LINE__, "\\|a" , "\\*a"  , false);
  is_valid(__LINE__, "\\|a" , "\\@a"  , false);
  is_valid(__LINE__, "\\|a" , "\\"    , false);
  is_valid(__LINE__, "\\|a" , "("     , false);
  is_valid(__LINE__, "\\|a" , ")"     , false);
  is_valid(__LINE__, "\\|a" , "|"     , false);
  is_valid(__LINE__, "\\|a" , "*"     , false);
  is_valid(__LINE__, "\\|a" , "@"     , false);
  is_valid(__LINE__, "\\|a" , "a\\"   , false);
  is_valid(__LINE__, "\\|a" , "a("    , false);
  is_valid(__LINE__, "\\|a" , "a)"    , false);
  is_valid(__LINE__, "\\|a" , "a|"    , false);
  is_valid(__LINE__, "\\|a" , "a*"    , false);
  is_valid(__LINE__, "\\|a" , "a@"    , false);
  is_valid(__LINE__, "\\|a" , "\\a"   , false);
  is_valid(__LINE__, "\\|a" , "(a"    , false);
  is_valid(__LINE__, "\\|a" , ")a"    , false);
  is_valid(__LINE__, "\\|a" , "|a"    , true );
  is_valid(__LINE__, "\\|a" , "*a"    , false);
  is_valid(__LINE__, "\\|a" , "@a"    , false);/*}}}*/
  is_valid(__LINE__,  "\\*" , "a"     , false);/*{{{*/
  is_valid(__LINE__,  "\\*" , "aa"    , false);
  is_valid(__LINE__,  "\\*" , "aaa"   , false);
  is_valid(__LINE__,  "\\*" , "ab"    , false);
  is_valid(__LINE__,  "\\*" , "aba"   , false);
  is_valid(__LINE__,  "\\*" , "\\\\"  , false);
  is_valid(__LINE__,  "\\*" , "\\("   , false);
  is_valid(__LINE__,  "\\*" , "\\)"   , false);
  is_valid(__LINE__,  "\\*" , "\\|"   , false);
  is_valid(__LINE__,  "\\*" , "\\*"   , false);
  is_valid(__LINE__,  "\\*" , "\\@"   , false);
  is_valid(__LINE__,  "\\*" , "a\\\\" , false);
  is_valid(__LINE__,  "\\*" , "a\\("  , false);
  is_valid(__LINE__,  "\\*" , "a\\)"  , false);
  is_valid(__LINE__,  "\\*" , "a\\|"  , false);
  is_valid(__LINE__,  "\\*" , "a\\*"  , false);
  is_valid(__LINE__,  "\\*" , "a\\@"  , false);
  is_valid(__LINE__,  "\\*" , "\\\\a" , false);
  is_valid(__LINE__,  "\\*" , "\\(a"  , false);
  is_valid(__LINE__,  "\\*" , "\\)a"  , false);
  is_valid(__LINE__,  "\\*" , "\\|a"  , false);
  is_valid(__LINE__,  "\\*" , "\\*a"  , false);
  is_valid(__LINE__,  "\\*" , "\\@a"  , false);
  is_valid(__LINE__,  "\\*" , "\\"    , false);
  is_valid(__LINE__,  "\\*" , "("     , false);
  is_valid(__LINE__,  "\\*" , ")"     , false);
  is_valid(__LINE__,  "\\*" , "|"     , false);
  is_valid(__LINE__,  "\\*" , "*"     , true );
  is_valid(__LINE__,  "\\*" , "@"     , false);
  is_valid(__LINE__,  "\\*" , "a\\"   , false);
  is_valid(__LINE__,  "\\*" , "a("    , false);
  is_valid(__LINE__,  "\\*" , "a)"    , false);
  is_valid(__LINE__,  "\\*" , "a|"    , false);
  is_valid(__LINE__,  "\\*" , "a*"    , false);
  is_valid(__LINE__,  "\\*" , "a@"    , false);
  is_valid(__LINE__,  "\\*" , "\\a"   , false);
  is_valid(__LINE__,  "\\*" , "(a"    , false);
  is_valid(__LINE__,  "\\*" , ")a"    , false);
  is_valid(__LINE__,  "\\*" , "|a"    , false);
  is_valid(__LINE__,  "\\*" , "*a"    , false);
  is_valid(__LINE__,  "\\*" , "@a"    , false);

  is_valid(__LINE__, "a\\*" , "a"     , false);
  is_valid(__LINE__, "a\\*" , "aa"    , false);
  is_valid(__LINE__, "a\\*" , "aaa"   , false);
  is_valid(__LINE__, "a\\*" , "ab"    , false);
  is_valid(__LINE__, "a\\*" , "aba"   , false);
  is_valid(__LINE__, "a\\*" , "\\\\"  , false);
  is_valid(__LINE__, "a\\*" , "\\("   , false);
  is_valid(__LINE__, "a\\*" , "\\)"   , false);
  is_valid(__LINE__, "a\\*" , "\\|"   , false);
  is_valid(__LINE__, "a\\*" , "\\*"   , false);
  is_valid(__LINE__, "a\\*" , "\\@"   , false);
  is_valid(__LINE__, "a\\*" , "a\\\\" , false);
  is_valid(__LINE__, "a\\*" , "a\\("  , false);
  is_valid(__LINE__, "a\\*" , "a\\)"  , false);
  is_valid(__LINE__, "a\\*" , "a\\|"  , false);
  is_valid(__LINE__, "a\\*" , "a\\*"  , false);
  is_valid(__LINE__, "a\\*" , "a\\@"  , false);
  is_valid(__LINE__, "a\\*" , "\\\\a" , false);
  is_valid(__LINE__, "a\\*" , "\\(a"  , false);
  is_valid(__LINE__, "a\\*" , "\\)a"  , false);
  is_valid(__LINE__, "a\\*" , "\\|a"  , false);
  is_valid(__LINE__, "a\\*" , "\\*a"  , false);
  is_valid(__LINE__, "a\\*" , "\\@a"  , false);
  is_valid(__LINE__, "a\\*" , "\\"    , false);
  is_valid(__LINE__, "a\\*" , "("     , false);
  is_valid(__LINE__, "a\\*" , ")"     , false);
  is_valid(__LINE__, "a\\*" , "|"     , false);
  is_valid(__LINE__, "a\\*" , "*"     , false);
  is_valid(__LINE__, "a\\*" , "@"     , false);
  is_valid(__LINE__, "a\\*" , "a\\"   , false);
  is_valid(__LINE__, "a\\*" , "a("    , false);
  is_valid(__LINE__, "a\\*" , "a)"    , false);
  is_valid(__LINE__, "a\\*" , "a|"    , false);
  is_valid(__LINE__, "a\\*" , "a*"    , true );
  is_valid(__LINE__, "a\\*" , "a@"    , false);
  is_valid(__LINE__, "a\\*" , "\\a"   , false);
  is_valid(__LINE__, "a\\*" , "(a"    , false);
  is_valid(__LINE__, "a\\*" , ")a"    , false);
  is_valid(__LINE__, "a\\*" , "|a"    , false);
  is_valid(__LINE__, "a\\*" , "*a"    , false);
  is_valid(__LINE__, "a\\*" , "@a"    , false);

  is_valid(__LINE__, "\\*a" , "a"     , false);
  is_valid(__LINE__, "\\*a" , "aa"    , false);
  is_valid(__LINE__, "\\*a" , "aaa"   , false);
  is_valid(__LINE__, "\\*a" , "ab"    , false);
  is_valid(__LINE__, "\\*a" , "aba"   , false);
  is_valid(__LINE__, "\\*a" , "\\\\"  , false);
  is_valid(__LINE__, "\\*a" , "\\("   , false);
  is_valid(__LINE__, "\\*a" , "\\)"   , false);
  is_valid(__LINE__, "\\*a" , "\\|"   , false);
  is_valid(__LINE__, "\\*a" , "\\*"   , false);
  is_valid(__LINE__, "\\*a" , "\\@"   , false);
  is_valid(__LINE__, "\\*a" , "a\\\\" , false);
  is_valid(__LINE__, "\\*a" , "a\\("  , false);
  is_valid(__LINE__, "\\*a" , "a\\)"  , false);
  is_valid(__LINE__, "\\*a" , "a\\|"  , false);
  is_valid(__LINE__, "\\*a" , "a\\*"  , false);
  is_valid(__LINE__, "\\*a" , "a\\@"  , false);
  is_valid(__LINE__, "\\*a" , "\\\\a" , false);
  is_valid(__LINE__, "\\*a" , "\\(a"  , false);
  is_valid(__LINE__, "\\*a" , "\\)a"  , false);
  is_valid(__LINE__, "\\*a" , "\\|a"  , false);
  is_valid(__LINE__, "\\*a" , "\\*a"  , false);
  is_valid(__LINE__, "\\*a" , "\\@a"  , false);
  is_valid(__LINE__, "\\*a" , "\\"    , false);
  is_valid(__LINE__, "\\*a" , "("     , false);
  is_valid(__LINE__, "\\*a" , ")"     , false);
  is_valid(__LINE__, "\\*a" , "|"     , false);
  is_valid(__LINE__, "\\*a" , "*"     , false);
  is_valid(__LINE__, "\\*a" , "@"     , false);
  is_valid(__LINE__, "\\*a" , "a\\"   , false);
  is_valid(__LINE__, "\\*a" , "a("    , false);
  is_valid(__LINE__, "\\*a" , "a)"    , false);
  is_valid(__LINE__, "\\*a" , "a|"    , false);
  is_valid(__LINE__, "\\*a" , "a*"    , false);
  is_valid(__LINE__, "\\*a" , "a@"    , false);
  is_valid(__LINE__, "\\*a" , "\\a"   , false);
  is_valid(__LINE__, "\\*a" , "(a"    , false);
  is_valid(__LINE__, "\\*a" , ")a"    , false);
  is_valid(__LINE__, "\\*a" , "|a"    , false);
  is_valid(__LINE__, "\\*a" , "*a"    , true );
  is_valid(__LINE__, "\\*a" , "@a"    , false);/*}}}*/
  is_valid(__LINE__,  "\\@" , "a"     , false);/*{{{*/
  is_valid(__LINE__,  "\\@" , "aa"    , false);
  is_valid(__LINE__,  "\\@" , "aaa"   , false);
  is_valid(__LINE__,  "\\@" , "ab"    , false);
  is_valid(__LINE__,  "\\@" , "aba"   , false);
  is_valid(__LINE__,  "\\@" , "\\\\"  , false);
  is_valid(__LINE__,  "\\@" , "\\("   , false);
  is_valid(__LINE__,  "\\@" , "\\)"   , false);
  is_valid(__LINE__,  "\\@" , "\\|"   , false);
  is_valid(__LINE__,  "\\@" , "\\*"   , false);
  is_valid(__LINE__,  "\\@" , "\\@"   , false);
  is_valid(__LINE__,  "\\@" , "a\\\\" , false);
  is_valid(__LINE__,  "\\@" , "a\\("  , false);
  is_valid(__LINE__,  "\\@" , "a\\)"  , false);
  is_valid(__LINE__,  "\\@" , "a\\|"  , false);
  is_valid(__LINE__,  "\\@" , "a\\*"  , false);
  is_valid(__LINE__,  "\\@" , "a\\@"  , false);
  is_valid(__LINE__,  "\\@" , "\\\\a" , false);
  is_valid(__LINE__,  "\\@" , "\\(a"  , false);
  is_valid(__LINE__,  "\\@" , "\\)a"  , false);
  is_valid(__LINE__,  "\\@" , "\\|a"  , false);
  is_valid(__LINE__,  "\\@" , "\\*a"  , false);
  is_valid(__LINE__,  "\\@" , "\\@a"  , false);
  is_valid(__LINE__,  "\\@" , "\\"    , false);
  is_valid(__LINE__,  "\\@" , "("     , false);
  is_valid(__LINE__,  "\\@" , ")"     , false);
  is_valid(__LINE__,  "\\@" , "|"     , false);
  is_valid(__LINE__,  "\\@" , "*"     , false);
  is_valid(__LINE__,  "\\@" , "@"     , true );
  is_valid(__LINE__,  "\\@" , "a\\"   , false);
  is_valid(__LINE__,  "\\@" , "a("    , false);
  is_valid(__LINE__,  "\\@" , "a)"    , false);
  is_valid(__LINE__,  "\\@" , "a|"    , false);
  is_valid(__LINE__,  "\\@" , "a*"    , false);
  is_valid(__LINE__,  "\\@" , "a@"    , false);
  is_valid(__LINE__,  "\\@" , "\\a"   , false);
  is_valid(__LINE__,  "\\@" , "(a"    , false);
  is_valid(__LINE__,  "\\@" , ")a"    , false);
  is_valid(__LINE__,  "\\@" , "|a"    , false);
  is_valid(__LINE__,  "\\@" , "*a"    , false);
  is_valid(__LINE__,  "\\@" , "@a"    , false);

  is_valid(__LINE__, "a\\@" , "a"     , false);
  is_valid(__LINE__, "a\\@" , "aa"    , false);
  is_valid(__LINE__, "a\\@" , "aaa"   , false);
  is_valid(__LINE__, "a\\@" , "ab"    , false);
  is_valid(__LINE__, "a\\@" , "aba"   , false);
  is_valid(__LINE__, "a\\@" , "\\\\"  , false);
  is_valid(__LINE__, "a\\@" , "\\("   , false);
  is_valid(__LINE__, "a\\@" , "\\)"   , false);
  is_valid(__LINE__, "a\\@" , "\\|"   , false);
  is_valid(__LINE__, "a\\@" , "\\*"   , false);
  is_valid(__LINE__, "a\\@" , "\\@"   , false);
  is_valid(__LINE__, "a\\@" , "a\\\\" , false);
  is_valid(__LINE__, "a\\@" , "a\\("  , false);
  is_valid(__LINE__, "a\\@" , "a\\)"  , false);
  is_valid(__LINE__, "a\\@" , "a\\|"  , false);
  is_valid(__LINE__, "a\\@" , "a\\*"  , false);
  is_valid(__LINE__, "a\\@" , "a\\@"  , false);
  is_valid(__LINE__, "a\\@" , "\\\\a" , false);
  is_valid(__LINE__, "a\\@" , "\\(a"  , false);
  is_valid(__LINE__, "a\\@" , "\\)a"  , false);
  is_valid(__LINE__, "a\\@" , "\\|a"  , false);
  is_valid(__LINE__, "a\\@" , "\\*a"  , false);
  is_valid(__LINE__, "a\\@" , "\\@a"  , false);
  is_valid(__LINE__, "a\\@" , "\\"    , false);
  is_valid(__LINE__, "a\\@" , "("     , false);
  is_valid(__LINE__, "a\\@" , ")"     , false);
  is_valid(__LINE__, "a\\@" , "|"     , false);
  is_valid(__LINE__, "a\\@" , "*"     , false);
  is_valid(__LINE__, "a\\@" , "@"     , false);
  is_valid(__LINE__, "a\\@" , "a\\"   , false);
  is_valid(__LINE__, "a\\@" , "a("    , false);
  is_valid(__LINE__, "a\\@" , "a)"    , false);
  is_valid(__LINE__, "a\\@" , "a|"    , false);
  is_valid(__LINE__, "a\\@" , "a*"    , false);
  is_valid(__LINE__, "a\\@" , "a@"    , true );
  is_valid(__LINE__, "a\\@" , "\\a"   , false);
  is_valid(__LINE__, "a\\@" , "(a"    , false);
  is_valid(__LINE__, "a\\@" , ")a"    , false);
  is_valid(__LINE__, "a\\@" , "|a"    , false);
  is_valid(__LINE__, "a\\@" , "*a"    , false);
  is_valid(__LINE__, "a\\@" , "@a"    , false);

  is_valid(__LINE__, "\\@a" , "a"     , false);
  is_valid(__LINE__, "\\@a" , "aa"    , false);
  is_valid(__LINE__, "\\@a" , "aaa"   , false);
  is_valid(__LINE__, "\\@a" , "ab"    , false);
  is_valid(__LINE__, "\\@a" , "aba"   , false);
  is_valid(__LINE__, "\\@a" , "\\\\"  , false);
  is_valid(__LINE__, "\\@a" , "\\("   , false);
  is_valid(__LINE__, "\\@a" , "\\)"   , false);
  is_valid(__LINE__, "\\@a" , "\\|"   , false);
  is_valid(__LINE__, "\\@a" , "\\*"   , false);
  is_valid(__LINE__, "\\@a" , "\\@"   , false);
  is_valid(__LINE__, "\\@a" , "a\\\\" , false);
  is_valid(__LINE__, "\\@a" , "a\\("  , false);
  is_valid(__LINE__, "\\@a" , "a\\)"  , false);
  is_valid(__LINE__, "\\@a" , "a\\|"  , false);
  is_valid(__LINE__, "\\@a" , "a\\*"  , false);
  is_valid(__LINE__, "\\@a" , "a\\@"  , false);
  is_valid(__LINE__, "\\@a" , "\\\\a" , false);
  is_valid(__LINE__, "\\@a" , "\\(a"  , false);
  is_valid(__LINE__, "\\@a" , "\\)a"  , false);
  is_valid(__LINE__, "\\@a" , "\\|a"  , false);
  is_valid(__LINE__, "\\@a" , "\\*a"  , false);
  is_valid(__LINE__, "\\@a" , "\\@a"  , false);
  is_valid(__LINE__, "\\@a" , "\\"    , false);
  is_valid(__LINE__, "\\@a" , "("     , false);
  is_valid(__LINE__, "\\@a" , ")"     , false);
  is_valid(__LINE__, "\\@a" , "|"     , false);
  is_valid(__LINE__, "\\@a" , "*"     , false);
  is_valid(__LINE__, "\\@a" , "@"     , false);
  is_valid(__LINE__, "\\@a" , "a\\"   , false);
  is_valid(__LINE__, "\\@a" , "a("    , false);
  is_valid(__LINE__, "\\@a" , "a)"    , false);
  is_valid(__LINE__, "\\@a" , "a|"    , false);
  is_valid(__LINE__, "\\@a" , "a*"    , false);
  is_valid(__LINE__, "\\@a" , "a@"    , false);
  is_valid(__LINE__, "\\@a" , "\\a"   , false);
  is_valid(__LINE__, "\\@a" , "(a"    , false);
  is_valid(__LINE__, "\\@a" , ")a"    , false);
  is_valid(__LINE__, "\\@a" , "|a"    , false);
  is_valid(__LINE__, "\\@a" , "*a"    , false);
  is_valid(__LINE__, "\\@a" , "@a"    , true );/*}}}*/

  // 長い正規表現
  is_valid(__LINE__, "(a|b)(a|b)(a|b)(a|b)", ""        , false);/*{{{*/
  is_valid(__LINE__, "(a|b)(a|b)(a|b)(a|b)", "aaaa"    , true );
  is_valid(__LINE__, "(a|b)(a|b)(a|b)(a|b)", "abab"    , true );
  is_valid(__LINE__, "(a|b)(a|b)(a|b)(a|b)", "aba"     , false);
  is_valid(__LINE__, "(a|b)(a|b)(a|b)(a|b)", "aaaaa"   , false);
  is_valid(__LINE__, "(a|b|c|d|e|f|g|h)",    "a"       , true );
  is_valid(__LINE__, "(a|b|c|d|e|f|g|h)",    "b"       , true );
  is_valid(__LINE__, "(a|b|c|d|e|f|g|h)",    "h"       , true );
  is_valid(__LINE__, "(a|b|c|d|e|f|g|h)",    "i"       , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , ""  , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "(" , true );
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "|" , true );
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , ")" , true );
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "*" , true );
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "@" , true );
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\", true );
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "a" , true );
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "b" , true );
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "c" , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\("   , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\|"   , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\)"   , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\*"   , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\@"   , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\\\"  , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\\\a" , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\\\b" , false);
  is_valid(__LINE__, "(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\\\c" , false);
  is_valid(__LINE__, "(\\**|\\\\)", ""    , true );
  is_valid(__LINE__, "(\\**|\\\\)", "*"   , true );
  is_valid(__LINE__, "(\\**|\\\\)", "**"  , true );
  is_valid(__LINE__, "(\\**|\\\\)", "***" , true );
  is_valid(__LINE__, "(\\**|\\\\)", "\\"  , true );
  is_valid(__LINE__, "(\\**|\\\\)", "\\\\", false);
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , ""    , true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "a"   , true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "aa"  , true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "b"   , true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "bb"  , true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "ab"  , true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "ba"  , true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "abcd", true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "abca", true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "caca", true );
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "cac*", false);
  is_valid(__LINE__, "((a*|b*)*|(c*|d*))*" , "cac*", false);
  is_valid(__LINE__, "(ab|ab)*"            , ""    , true );
  is_valid(__LINE__, "(ab|ab)*"            , "a"   , false);
  is_valid(__LINE__, "(ab|ab)*"            , "ab"  , true );
  is_valid(__LINE__, "(ab|ab)*"            , "aba" , false);
  is_valid(__LINE__, "(ab|ab)*"            , "abab", true );/*}}}*/

  // 分岐のない(...)のチェック
  is_valid(__LINE__, "(a)"      , ""     , false);/*{{{*/
  is_valid(__LINE__, "(a)"      , "a"    , true );
  is_valid(__LINE__, "(a)"      , "aa"   , false);
  is_valid(__LINE__, "(a)"      , "aaa"  , false);
  is_valid(__LINE__, "(a)"      , "aaaa" , false);
  is_valid(__LINE__, "(aa)"     , ""     , false);
  is_valid(__LINE__, "(aa)"     , "a"    , false);
  is_valid(__LINE__, "(aa)"     , "aa"   , true );
  is_valid(__LINE__, "(aa)"     , "aaa"  , false);
  is_valid(__LINE__, "(aa)"     , "aaaa" , false);
  is_valid(__LINE__, "(ab)"     , ""     , false);
  is_valid(__LINE__, "(ab)"     , "a"    , false);
  is_valid(__LINE__, "(ab)"     , "ab"   , true );
  is_valid(__LINE__, "(ab)"     , "aba"  , false);
  is_valid(__LINE__, "(ab)"     , "abab" , false);
  is_valid(__LINE__, "(a)(a)"   , ""     , false);
  is_valid(__LINE__, "(a)(a)"   , "a"    , false);
  is_valid(__LINE__, "(a)(a)"   , "aa"   , true );
  is_valid(__LINE__, "(a)(a)"   , "aaa"  , false);
  is_valid(__LINE__, "(a)(a)"   , "aaaa" , false);
  is_valid(__LINE__, "(aa)(aa)" , ""     , false);
  is_valid(__LINE__, "(aa)(aa)" , "a"    , false);
  is_valid(__LINE__, "(aa)(aa)" , "aa"   , false);
  is_valid(__LINE__, "(aa)(aa)" , "aaa"  , false);
  is_valid(__LINE__, "(aa)(aa)" , "aaaa" , true );
  is_valid(__LINE__, "(ab)(ab)" , ""     , false);
  is_valid(__LINE__, "(ab)(ab)" , "a"    , false);
  is_valid(__LINE__, "(ab)(ab)" , "ab"   , false);
  is_valid(__LINE__, "(ab)(ab)" , "aba"  , false);
  is_valid(__LINE__, "(ab)(ab)" , "abab" , true );
  is_valid(__LINE__, "(a)*"     , ""     , true );
  is_valid(__LINE__, "(a)*"     , "a"    , true );
  is_valid(__LINE__, "(a)*"     , "aa"   , true );
  is_valid(__LINE__, "(a)*"     , "aaa"  , true );
  is_valid(__LINE__, "(a)*"     , "aaaa" , true );
  is_valid(__LINE__, "(aa)*"    , ""     , true );
  is_valid(__LINE__, "(aa)*"    , "a"    , false);
  is_valid(__LINE__, "(aa)*"    , "aa"   , true );
  is_valid(__LINE__, "(aa)*"    , "aaa"  , false);
  is_valid(__LINE__, "(aa)*"    , "aaaa" , true );
  is_valid(__LINE__, "(ab)*"    , ""     , true );
  is_valid(__LINE__, "(ab)*"    , "a"    , false);
  is_valid(__LINE__, "(ab)*"    , "ab"   , true );
  is_valid(__LINE__, "(ab)*"    , "aba"  , false);
  is_valid(__LINE__, "(ab)*"    , "abab" , true );
  is_valid(__LINE__, "(\\(a)"   , "("    , false);
  is_valid(__LINE__, "(\\(a)"   , "(a"   , true );
  is_valid(__LINE__, "(\\(a)"   , "(aa"  , false);
  is_valid(__LINE__, "(\\(a)"   , "(aaa" , false);
  is_valid(__LINE__, "(\\(a)"   , "(aaaa", false);
  is_valid(__LINE__, "(\\(aa)"  , "("    , false);
  is_valid(__LINE__, "(\\(aa)"  , "(a"   , false);
  is_valid(__LINE__, "(\\(aa)"  , "(aa"  , true );
  is_valid(__LINE__, "(\\(aa)"  , "(aaa" , false);
  is_valid(__LINE__, "(\\(aa)"  , "(aaaa", false);
  is_valid(__LINE__, "(\\(ab)"  , "("    , false);
  is_valid(__LINE__, "(\\(ab)"  , "(a"   , false);
  is_valid(__LINE__, "(\\(ab)"  , "(ab"  , true );
  is_valid(__LINE__, "(\\(ab)"  , "(aba" , false);
  is_valid(__LINE__, "(\\(ab)"  , "(abab", false);
  is_valid(__LINE__, "(a\\()"   , "("    , false);
  is_valid(__LINE__, "(a\\()"   , "a("   , true );
  is_valid(__LINE__, "(a\\()"   , "aa("  , false);
  is_valid(__LINE__, "(a\\()"   , "aaa(" , false);
  is_valid(__LINE__, "(a\\()"   , "aaaa(", false);
  is_valid(__LINE__, "(aa\\()"  , "("    , false);
  is_valid(__LINE__, "(aa\\()"  , "a("   , false);
  is_valid(__LINE__, "(aa\\()"  , "aa("  , true );
  is_valid(__LINE__, "(aa\\()"  , "aaa(" , false);
  is_valid(__LINE__, "(aa\\()"  , "aaaa(", false);
  is_valid(__LINE__, "(ab\\()"  , "("    , false);
  is_valid(__LINE__, "(ab\\()"  , "a("   , false);
  is_valid(__LINE__, "(ab\\()"  , "ab("  , true );
  is_valid(__LINE__, "(ab\\()"  , "aba(" , false);
  is_valid(__LINE__, "(ab\\()"  , "abab(", false);/*}}}*/

  // 部分マッチ。引数の最後2つはis_forwardとis_short
  is_partial_valid(__LINE__, ""       , ""        , false, true , true );/*{{{*/
  is_partial_valid(__LINE__, ""       , "a"       , false, true , true );
  is_partial_valid(__LINE__, ""       , "ab"      , false, true , true );
  is_partial_valid(__LINE__, ""       , "ba"      , false, true , true );
  is_partial_valid(__LINE__, ""       , "bab"     , false, true , true );
  is_partial_valid(__LINE__, ""       , "abab"    , false, true , true );
  is_partial_valid(__LINE__, ""       , "baba"    , false, true , true );
  is_partial_valid(__LINE__, ""       , ""        , false, true , false);
  is_partial_valid(__LINE__, ""       , "a"       , false, true , false);
  is_partial_valid(__LINE__, ""       , "ab"      , false, true , false);
  is_partial_valid(__LINE__, ""       , "ba"      , false, true , false);
  is_partial_valid(__LINE__, ""       , "bab"     , false, true , false);
  is_partial_valid(__LINE__, ""       , "abab"    , false, true , false);
  is_partial_valid(__LINE__, ""       , "baba"    , false, true , false);
  is_partial_valid(__LINE__, ""       , ""        , false, false, true );
  is_partial_valid(__LINE__, ""       , "a"       , false, false, true );
  is_partial_valid(__LINE__, ""       , "ab"      , false, false, true );
  is_partial_valid(__LINE__, ""       , "ba"      , false, false, true );
  is_partial_valid(__LINE__, ""       , "bab"     , false, false, true );
  is_partial_valid(__LINE__, ""       , "abab"    , false, false, true );
  is_partial_valid(__LINE__, ""       , "baba"    , false, false, true );
  is_partial_valid(__LINE__, ""       , ""        , false, false, false);
  is_partial_valid(__LINE__, ""       , "a"       , false, false, false);
  is_partial_valid(__LINE__, ""       , "ab"      , false, false, false);
  is_partial_valid(__LINE__, ""       , "ba"      , false, false, false);
  is_partial_valid(__LINE__, ""       , "bab"     , false, false, false);
  is_partial_valid(__LINE__, ""       , "abab"    , false, false, false);
  is_partial_valid(__LINE__, ""       , "baba"    , false, false, false);

  is_partial_valid(__LINE__, "a"      , ""        , false, true , true );
  is_partial_valid(__LINE__, "a"      , "a"       , true , true , true );
  is_partial_valid(__LINE__, "a"      , "ab"      , true , true , true );
  is_partial_valid(__LINE__, "a"      , "ba"      , false, true , true );
  is_partial_valid(__LINE__, "a"      , "bab"     , false, true , true );
  is_partial_valid(__LINE__, "a"      , "abab"    , true , true , true );
  is_partial_valid(__LINE__, "a"      , "baba"    , false, true , true );
  is_partial_valid(__LINE__, "a"      , ""        , false, true , false);
  is_partial_valid(__LINE__, "a"      , "a"       , true , true , false);
  is_partial_valid(__LINE__, "a"      , "ab"      , true , true , false);
  is_partial_valid(__LINE__, "a"      , "ba"      , false, true , false);
  is_partial_valid(__LINE__, "a"      , "bab"     , false, true , false);
  is_partial_valid(__LINE__, "a"      , "abab"    , true , true , false);
  is_partial_valid(__LINE__, "a"      , "baba"    , false, true , false);
  is_partial_valid(__LINE__, "a"      , ""        , false, false, true );
  is_partial_valid(__LINE__, "a"      , "a"       , true , false, true );
  is_partial_valid(__LINE__, "a"      , "ab"      , false, false, true );
  is_partial_valid(__LINE__, "a"      , "ba"      , true , false, true );
  is_partial_valid(__LINE__, "a"      , "bab"     , false, false, true );
  is_partial_valid(__LINE__, "a"      , "abab"    , false, false, true );
  is_partial_valid(__LINE__, "a"      , "baba"    , true , false, true );
  is_partial_valid(__LINE__, "a"      , ""        , false, false, false);
  is_partial_valid(__LINE__, "a"      , "a"       , true , false, false);
  is_partial_valid(__LINE__, "a"      , "ab"      , false, false, false);
  is_partial_valid(__LINE__, "a"      , "ba"      , true , false, false);
  is_partial_valid(__LINE__, "a"      , "bab"     , false, false, false);
  is_partial_valid(__LINE__, "a"      , "abab"    , false, false, false);
  is_partial_valid(__LINE__, "a"      , "baba"    , true , false, false);

  is_partial_valid(__LINE__, "ab"     , ""        , false, true , true );
  is_partial_valid(__LINE__, "ab"     , "a"       , false, true , true );
  is_partial_valid(__LINE__, "ab"     , "ab"      , true , true , true );
  is_partial_valid(__LINE__, "ab"     , "ba"      , false, true , true );
  is_partial_valid(__LINE__, "ab"     , "aba"     , true , true , true );
  is_partial_valid(__LINE__, "ab"     , "bab"     , false, true , true );
  is_partial_valid(__LINE__, "ab"     , "abab"    , true , true , true );
  is_partial_valid(__LINE__, "ab"     , "baba"    , false, true , true );
  is_partial_valid(__LINE__, "ab"     , ""        , false, true , false);
  is_partial_valid(__LINE__, "ab"     , "a"       , false, true , false);
  is_partial_valid(__LINE__, "ab"     , "ab"      , true , true , false);
  is_partial_valid(__LINE__, "ab"     , "ba"      , false, true , false);
  is_partial_valid(__LINE__, "ab"     , "aba"     , true , true , false);
  is_partial_valid(__LINE__, "ab"     , "bab"     , false, true , false);
  is_partial_valid(__LINE__, "ab"     , "abab"    , true , true , false);
  is_partial_valid(__LINE__, "ab"     , "baba"    , false, true , false);
  is_partial_valid(__LINE__, "ab"     , ""        , false, false, true );
  is_partial_valid(__LINE__, "ab"     , "a"       , false, false, true );
  is_partial_valid(__LINE__, "ab"     , "ab"      , true , false, true );
  is_partial_valid(__LINE__, "ab"     , "ba"      , false, false, true );
  is_partial_valid(__LINE__, "ab"     , "aba"     , false, false, true );
  is_partial_valid(__LINE__, "ab"     , "bab"     , true , false, true );
  is_partial_valid(__LINE__, "ab"     , "abab"    , true , false, true );
  is_partial_valid(__LINE__, "ab"     , "baba"    , false, false, true );
  is_partial_valid(__LINE__, "ab"     , ""        , false, false, false);
  is_partial_valid(__LINE__, "ab"     , "a"       , false, false, false);
  is_partial_valid(__LINE__, "ab"     , "ab"      , true , false, false);
  is_partial_valid(__LINE__, "ab"     , "ba"      , false, false, false);
  is_partial_valid(__LINE__, "ab"     , "aba"     , false, false, false);
  is_partial_valid(__LINE__, "ab"     , "bab"     , true , false, false);
  is_partial_valid(__LINE__, "ab"     , "abab"    , true , false, false);
  is_partial_valid(__LINE__, "ab"     , "baba"    , false, false, false);/*}}}*/

  fprintf(stderr, "STATISTICS: [%d/%d] ARE PASSED\n", correct, question);
  return 0;
}
