#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "../include/pre.h"
#include "../include/node.h"
#include "../include/match.h"

int correct  = 0;
int question = 0;

static bool is_match(const char* regex_str, const char* match_str, const int option);
static void is_valid(const char* regex_str, const char* match_str, const bool answer);
// マッチ関数/*{{{*/
static bool is_match(const char* regex_str, const char* match_str, const int option) {
  char simple_regex[200];
  int current = 0;
  simplify_regex(regex_str, 0, strlen(regex_str), simple_regex, &current, 200);
  simple_regex[current] = '\0';
  NODE node[200];
  regex_to_all_node(simple_regex, node, 200);
  MATCH match[200];

  int step;
  if      (option == 0) step = exact_match(            match_str, node, match, 200);
  else if (option == 1) step = forward_shortest_match( match_str, node, match, 200);
  else if (option == 2) step = forward_longest_match(  match_str, node, match, 200);
  else if (option == 3) step = backward_shortest_match(match_str, node, match, 200);
  else if (option == 4) step = backward_longest_match( match_str, node, match, 200);
  else assert(0);

  bool ret;
  if (step > 0) {
    ret = true;
  } else {
    ret = false;
  }

  return ret;
}
/*}}}*/
// exactチェック関数/*{{{*/
static void is_valid(const char* regex_str, const char* match_str, const bool answer) {
  question++;
  bool trial = is_match(regex_str, match_str, 0); // 0はexact match
  if (trial == answer) {
    // fprintf(stderr, "%04d [\x1b[32mO\x1b[39m] %15s       \"%s\"\n"                , question, regex_str, match_str);
    correct++;
  }
  if (trial != answer) {
    fprintf(stderr, "%04d [\x1b[31mX\x1b[39m] \x1b[41m%15s       \"%s\"\x1b[49m", question, regex_str, match_str);
    if (answer) fprintf(stderr, "  SHOULD BE MATCH BUT RESULT IS UNMATCH.\n");
    else        fprintf(stderr, "  SHOULD BE UNMATCH BUT RESULT IS MATCH.\n");
  }
}/*}}}*/
// partialチェック関数/*{{{*/
static void is_partial_valid(const char* regex_str, const char* match_str, const bool answer, const bool is_forward, const bool is_short) {
  question++;
  const char *partial;
  bool trial;

  if        ( is_forward &&  is_short) {
    partial = "forward  shortest";
    trial = is_match(regex_str, match_str, 1);
  } else if ( is_forward && !is_short) {
    partial = "forward  longest ";
    trial = is_match(regex_str, match_str, 2);
  } else if (!is_forward &&  is_short) {
    partial = "backward shortest";
    trial = is_match(regex_str, match_str, 3);
  } else if (!is_forward && !is_short) {
    partial = "backward longest ";
    trial = is_match(regex_str, match_str, 4);
  } else {
    assert(0);
  }

  if (trial == answer) {
    // fprintf(stderr, "%04d [\x1b[32mO\x1b[39m] (%s) %15s       \"%s\"\n"              , question, partial, regex_str, match_str);
    correct++;
  }
  if (trial != answer) {
    fprintf(stderr, "%04d [\x1b[31mX\x1b[39m] (%s) \x1b[41m%15s       \"%s\"\x1b[49m", question, partial, regex_str, match_str);
    if (answer) fprintf(stderr, "  SHOULD BE MATCH BUT RESULT IS UNMATCH.\n");
    else        fprintf(stderr, "  SHOULD BE UNMATCH BUT RESULT IS MATCH.\n");
  }
}/*}}}*/

int main(void) {
  // 単純な正規表現を徹底的にチェック
  is_valid(""             , ""    , false);/*{{{*/
  is_valid("@"            , ""    , true );
  is_valid("a"            , ""    , false);
  is_valid("(@|@)"        , ""    , true );
  is_valid("(a|@)"        , ""    , true );
  is_valid("(@|a)"        , ""    , true );
  is_valid("(a|a)"        , ""    , false);

  is_valid("@*"           , ""    , true );
  is_valid("a*"           , ""    , true );
  is_valid("(@|@)*"       , ""    , true );
  is_valid("(a|@)*"       , ""    , true );
  is_valid("(@|a)*"       , ""    , true );
  is_valid("(a|a)*"       , ""    , true );

  is_valid("@@"           , ""    , true );
  is_valid("@a"           , ""    , false);
  is_valid("a@"           , ""    , false);
  is_valid("aa"           , ""    , false);
  is_valid("ab"           , ""    , false);
  is_valid("(@|@)(@|@)"   , ""    , true );
  is_valid("(@|@)(a|@)"   , ""    , true );
  is_valid("(@|@)(@|a)"   , ""    , true );
  is_valid("(@|@)(a|a)"   , ""    , false);
  is_valid("(a|@)(@|@)"   , ""    , true );
  is_valid("(a|@)(a|@)"   , ""    , true );
  is_valid("(a|@)(@|a)"   , ""    , true );
  is_valid("(a|@)(a|a)"   , ""    , false);
  is_valid("(@|a)(@|@)"   , ""    , true );
  is_valid("(@|a)(a|@)"   , ""    , true );
  is_valid("(@|a)(@|a)"   , ""    , true );
  is_valid("(@|a)(a|a)"   , ""    , false);
  is_valid("(a|a)(@|@)"   , ""    , false);
  is_valid("(a|a)(a|@)"   , ""    , false);
  is_valid("(a|a)(@|a)"   , ""    , false);
  is_valid("(a|a)(a|a)"   , ""    , false);

  is_valid("@*@"          , ""    , true );
  is_valid("@*a"          , ""    , false);
  is_valid("a*@"          , ""    , true );
  is_valid("a*a"          , ""    , false);
  is_valid("a*b"          , ""    , false);
  is_valid("(@|@)*(@|@)"  , ""    , true );
  is_valid("(@|@)*(a|@)"  , ""    , true );
  is_valid("(@|@)*(@|a)"  , ""    , true );
  is_valid("(@|@)*(a|a)"  , ""    , false);
  is_valid("(a|@)*(@|@)"  , ""    , true );
  is_valid("(a|@)*(a|@)"  , ""    , true );
  is_valid("(a|@)*(@|a)"  , ""    , true );
  is_valid("(a|@)*(a|a)"  , ""    , false);
  is_valid("(@|a)*(@|@)"  , ""    , true );
  is_valid("(@|a)*(a|@)"  , ""    , true );
  is_valid("(@|a)*(@|a)"  , ""    , true );
  is_valid("(@|a)*(a|a)"  , ""    , false);
  is_valid("(a|a)*(@|@)"  , ""    , true );
  is_valid("(a|a)*(a|@)"  , ""    , true );
  is_valid("(a|a)*(@|a)"  , ""    , true );
  is_valid("(a|a)*(a|a)"  , ""    , false);

  is_valid("@@*"          , ""    , true );
  is_valid("@a*"          , ""    , true );
  is_valid("a@*"          , ""    , false);
  is_valid("aa*"          , ""    , false);
  is_valid("ab*"          , ""    , false);
  is_valid("(@|@)(@|@)*"  , ""    , true );
  is_valid("(@|@)(a|@)*"  , ""    , true );
  is_valid("(@|@)(@|a)*"  , ""    , true );
  is_valid("(@|@)(a|a)*"  , ""    , true );
  is_valid("(a|@)(@|@)*"  , ""    , true );
  is_valid("(a|@)(a|@)*"  , ""    , true );
  is_valid("(a|@)(@|a)*"  , ""    , true );
  is_valid("(a|@)(a|a)*"  , ""    , true );
  is_valid("(@|a)(@|@)*"  , ""    , true );
  is_valid("(@|a)(a|@)*"  , ""    , true );
  is_valid("(@|a)(@|a)*"  , ""    , true );
  is_valid("(@|a)(a|a)*"  , ""    , true );
  is_valid("(a|a)(@|@)*"  , ""    , false);
  is_valid("(a|a)(a|@)*"  , ""    , false);
  is_valid("(a|a)(@|a)*"  , ""    , false);
  is_valid("(a|a)(a|a)*"  , ""    , false);

  is_valid("@*@*"         , ""    , true );
  is_valid("@*a*"         , ""    , true );
  is_valid("a*@*"         , ""    , true );
  is_valid("a*a*"         , ""    , true );
  is_valid("a*b*"         , ""    , true );
  is_valid("(@|@)*(@|@)*" , ""    , true );
  is_valid("(@|@)*(a|@)*" , ""    , true );
  is_valid("(@|@)*(@|a)*" , ""    , true );
  is_valid("(@|@)*(a|a)*" , ""    , true );
  is_valid("(a|@)*(@|@)*" , ""    , true );
  is_valid("(a|@)*(a|@)*" , ""    , true );
  is_valid("(a|@)*(@|a)*" , ""    , true );
  is_valid("(a|@)*(a|a)*" , ""    , true );
  is_valid("(@|a)*(@|@)*" , ""    , true );
  is_valid("(@|a)*(a|@)*" , ""    , true );
  is_valid("(@|a)*(@|a)*" , ""    , true );
  is_valid("(@|a)*(a|a)*" , ""    , true );
  is_valid("(a|a)*(@|@)*" , ""    , true );
  is_valid("(a|a)*(a|@)*" , ""    , true );
  is_valid("(a|a)*(@|a)*" , ""    , true );
  is_valid("(a|a)*(a|a)*" , ""    , true );/*}}}*/
  is_valid(""             , "a"   , false);/*{{{*/
  is_valid("@"            , "a"   , false);
  is_valid("a"            , "a"   , true );
  is_valid("(@|@)"        , "a"   , false);
  is_valid("(a|@)"        , "a"   , true );
  is_valid("(@|a)"        , "a"   , true );
  is_valid("(a|a)"        , "a"   , true );

  is_valid("@*"           , "a"   , false);
  is_valid("a*"           , "a"   , true );
  is_valid("(@|@)*"       , "a"   , false);
  is_valid("(a|@)*"       , "a"   , true );
  is_valid("(@|a)*"       , "a"   , true );
  is_valid("(a|a)*"       , "a"   , true );

  is_valid("@@"           , "a"   , false);
  is_valid("@a"           , "a"   , true );
  is_valid("a@"           , "a"   , true );
  is_valid("aa"           , "a"   , false);
  is_valid("ab"           , "a"   , false);
  is_valid("(@|@)(@|@)"   , "a"   , false);
  is_valid("(@|@)(a|@)"   , "a"   , true );
  is_valid("(@|@)(@|a)"   , "a"   , true );
  is_valid("(@|@)(a|a)"   , "a"   , true );
  is_valid("(a|@)(@|@)"   , "a"   , true );
  is_valid("(a|@)(a|@)"   , "a"   , true );
  is_valid("(a|@)(@|a)"   , "a"   , true );
  is_valid("(a|@)(a|a)"   , "a"   , true );
  is_valid("(@|a)(@|@)"   , "a"   , true );
  is_valid("(@|a)(a|@)"   , "a"   , true );
  is_valid("(@|a)(@|a)"   , "a"   , true );
  is_valid("(@|a)(a|a)"   , "a"   , true );
  is_valid("(a|a)(@|@)"   , "a"   , true );
  is_valid("(a|a)(a|@)"   , "a"   , true );
  is_valid("(a|a)(@|a)"   , "a"   , true );
  is_valid("(a|a)(a|a)"   , "a"   , false);

  is_valid("@*@"          , "a"   , false);
  is_valid("@*a"          , "a"   , true );
  is_valid("a*@"          , "a"   , true );
  is_valid("a*a"          , "a"   , true );
  is_valid("a*b"          , "a"   , false);
  is_valid("(@|@)*(@|@)"  , "a"   , false);
  is_valid("(@|@)*(a|@)"  , "a"   , true );
  is_valid("(@|@)*(@|a)"  , "a"   , true );
  is_valid("(@|@)*(a|a)"  , "a"   , true );
  is_valid("(a|@)*(@|@)"  , "a"   , true );
  is_valid("(a|@)*(a|@)"  , "a"   , true );
  is_valid("(a|@)*(@|a)"  , "a"   , true );
  is_valid("(a|@)*(a|a)"  , "a"   , true );
  is_valid("(@|a)*(@|@)"  , "a"   , true );
  is_valid("(@|a)*(a|@)"  , "a"   , true );
  is_valid("(@|a)*(@|a)"  , "a"   , true );
  is_valid("(@|a)*(a|a)"  , "a"   , true );
  is_valid("(a|a)*(@|@)"  , "a"   , true );
  is_valid("(a|a)*(a|@)"  , "a"   , true );
  is_valid("(a|a)*(@|a)"  , "a"   , true );
  is_valid("(a|a)*(a|a)"  , "a"   , true );

  is_valid("@@*"          , "a"   , false);
  is_valid("@a*"          , "a"   , true );
  is_valid("a@*"          , "a"   , true );
  is_valid("aa*"          , "a"   , true );
  is_valid("ab*"          , "a"   , true );
  is_valid("(@|@)(@|@)*"  , "a"   , false);
  is_valid("(@|@)(a|@)*"  , "a"   , true );
  is_valid("(@|@)(@|a)*"  , "a"   , true );
  is_valid("(@|@)(a|a)*"  , "a"   , true );
  is_valid("(a|@)(@|@)*"  , "a"   , true );
  is_valid("(a|@)(a|@)*"  , "a"   , true );
  is_valid("(a|@)(@|a)*"  , "a"   , true );
  is_valid("(a|@)(a|a)*"  , "a"   , true );
  is_valid("(@|a)(@|@)*"  , "a"   , true );
  is_valid("(@|a)(a|@)*"  , "a"   , true );
  is_valid("(@|a)(@|a)*"  , "a"   , true );
  is_valid("(@|a)(a|a)*"  , "a"   , true );
  is_valid("(a|a)(@|@)*"  , "a"   , true );
  is_valid("(a|a)(a|@)*"  , "a"   , true );
  is_valid("(a|a)(@|a)*"  , "a"   , true );
  is_valid("(a|a)(a|a)*"  , "a"   , true );
  is_valid("@*@*"         , "a"   , false);
  is_valid("@*a*"         , "a"   , true );
  is_valid("a*@*"         , "a"   , true );
  is_valid("a*a*"         , "a"   , true );
  is_valid("a*b*"         , "a"   , true );
  is_valid("(@|@)*(@|@)*" , "a"   , false);
  is_valid("(@|@)*(a|@)*" , "a"   , true );
  is_valid("(@|@)*(@|a)*" , "a"   , true );
  is_valid("(@|@)*(a|a)*" , "a"   , true );
  is_valid("(a|@)*(@|@)*" , "a"   , true );
  is_valid("(a|@)*(a|@)*" , "a"   , true );
  is_valid("(a|@)*(@|a)*" , "a"   , true );
  is_valid("(a|@)*(a|a)*" , "a"   , true );
  is_valid("(@|a)*(@|@)*" , "a"   , true );
  is_valid("(@|a)*(a|@)*" , "a"   , true );
  is_valid("(@|a)*(@|a)*" , "a"   , true );
  is_valid("(@|a)*(a|a)*" , "a"   , true );
  is_valid("(a|a)*(@|@)*" , "a"   , true );
  is_valid("(a|a)*(a|@)*" , "a"   , true );
  is_valid("(a|a)*(@|a)*" , "a"   , true );
  is_valid("(a|a)*(a|a)*" , "a"   , true );/*}}}*/
  is_valid(""             , "b"   , false);/*{{{*/
  is_valid("@"            , "b"   , false);
  is_valid("a"            , "b"   , false);
  is_valid("(@|@)"        , "b"   , false);
  is_valid("(a|@)"        , "b"   , false);
  is_valid("(@|a)"        , "b"   , false);
  is_valid("(a|a)"        , "b"   , false);

  is_valid("@*"           , "b"   , false);
  is_valid("a*"           , "b"   , false);
  is_valid("(@|@)*"       , "b"   , false);
  is_valid("(a|@)*"       , "b"   , false);
  is_valid("(@|a)*"       , "b"   , false);
  is_valid("(a|a)*"       , "b"   , false);

  is_valid("@@"           , "b"   , false);
  is_valid("@a"           , "b"   , false);
  is_valid("a@"           , "b"   , false);
  is_valid("aa"           , "b"   , false);
  is_valid("ab"           , "b"   , false);
  is_valid("(@|@)(@|@)"   , "b"   , false);
  is_valid("(@|@)(a|@)"   , "b"   , false);
  is_valid("(@|@)(@|a)"   , "b"   , false);
  is_valid("(@|@)(a|a)"   , "b"   , false);
  is_valid("(a|@)(@|@)"   , "b"   , false);
  is_valid("(a|@)(a|@)"   , "b"   , false);
  is_valid("(a|@)(@|a)"   , "b"   , false);
  is_valid("(a|@)(a|a)"   , "b"   , false);
  is_valid("(@|a)(@|@)"   , "b"   , false);
  is_valid("(@|a)(a|@)"   , "b"   , false);
  is_valid("(@|a)(@|a)"   , "b"   , false);
  is_valid("(@|a)(a|a)"   , "b"   , false);
  is_valid("(a|a)(@|@)"   , "b"   , false);
  is_valid("(a|a)(a|@)"   , "b"   , false);
  is_valid("(a|a)(@|a)"   , "b"   , false);
  is_valid("(a|a)(a|a)"   , "b"   , false);

  is_valid("@*@"          , "b"   , false);
  is_valid("@*a"          , "b"   , false);
  is_valid("a*@"          , "b"   , false);
  is_valid("a*a"          , "b"   , false);
  is_valid("a*b"          , "b"   , true );
  is_valid("(@|@)*(@|@)"  , "b"   , false);
  is_valid("(@|@)*(a|@)"  , "b"   , false);
  is_valid("(@|@)*(@|a)"  , "b"   , false);
  is_valid("(@|@)*(a|a)"  , "b"   , false);
  is_valid("(a|@)*(@|@)"  , "b"   , false);
  is_valid("(a|@)*(a|@)"  , "b"   , false);
  is_valid("(a|@)*(@|a)"  , "b"   , false);
  is_valid("(a|@)*(a|a)"  , "b"   , false);
  is_valid("(@|a)*(@|@)"  , "b"   , false);
  is_valid("(@|a)*(a|@)"  , "b"   , false);
  is_valid("(@|a)*(@|a)"  , "b"   , false);
  is_valid("(@|a)*(a|a)"  , "b"   , false);
  is_valid("(a|a)*(@|@)"  , "b"   , false);
  is_valid("(a|a)*(a|@)"  , "b"   , false);
  is_valid("(a|a)*(@|a)"  , "b"   , false);
  is_valid("(a|a)*(a|a)"  , "b"   , false);

  is_valid("@@*"          , "b"   , false);
  is_valid("@a*"          , "b"   , false);
  is_valid("a@*"          , "b"   , false);
  is_valid("aa*"          , "b"   , false);
  is_valid("ab*"          , "b"   , false);
  is_valid("(@|@)(@|@)*"  , "b"   , false);
  is_valid("(@|@)(a|@)*"  , "b"   , false);
  is_valid("(@|@)(@|a)*"  , "b"   , false);
  is_valid("(@|@)(a|a)*"  , "b"   , false);
  is_valid("(a|@)(@|@)*"  , "b"   , false);
  is_valid("(a|@)(a|@)*"  , "b"   , false);
  is_valid("(a|@)(@|a)*"  , "b"   , false);
  is_valid("(a|@)(a|a)*"  , "b"   , false);
  is_valid("(@|a)(@|@)*"  , "b"   , false);
  is_valid("(@|a)(a|@)*"  , "b"   , false);
  is_valid("(@|a)(@|a)*"  , "b"   , false);
  is_valid("(@|a)(a|a)*"  , "b"   , false);
  is_valid("(a|a)(@|@)*"  , "b"   , false);
  is_valid("(a|a)(a|@)*"  , "b"   , false);
  is_valid("(a|a)(@|a)*"  , "b"   , false);
  is_valid("(a|a)(a|a)*"  , "b"   , false);

  is_valid("@*@*"         , "b"   , false);
  is_valid("@*a*"         , "b"   , false);
  is_valid("a*@*"         , "b"   , false);
  is_valid("a*a*"         , "b"   , false);
  is_valid("a*b*"         , "b"   , true );
  is_valid("(@|@)*(@|@)*" , "b"   , false);
  is_valid("(@|@)*(a|@)*" , "b"   , false);
  is_valid("(@|@)*(@|a)*" , "b"   , false);
  is_valid("(@|@)*(a|a)*" , "b"   , false);
  is_valid("(a|@)*(@|@)*" , "b"   , false);
  is_valid("(a|@)*(a|@)*" , "b"   , false);
  is_valid("(a|@)*(@|a)*" , "b"   , false);
  is_valid("(a|@)*(a|a)*" , "b"   , false);
  is_valid("(@|a)*(@|@)*" , "b"   , false);
  is_valid("(@|a)*(a|@)*" , "b"   , false);
  is_valid("(@|a)*(@|a)*" , "b"   , false);
  is_valid("(@|a)*(a|a)*" , "b"   , false);
  is_valid("(a|a)*(@|@)*" , "b"   , false);
  is_valid("(a|a)*(a|@)*" , "b"   , false);
  is_valid("(a|a)*(@|a)*" , "b"   , false);
  is_valid("(a|a)*(a|a)*" , "b"   , false);/*}}}*/
  is_valid(""             , "aa"  , false);/*{{{*/
  is_valid("@"            , "aa"  , false);
  is_valid("a"            , "aa"  , false);
  is_valid("(@|@)"        , "aa"  , false);
  is_valid("(a|@)"        , "aa"  , false);
  is_valid("(@|a)"        , "aa"  , false);
  is_valid("(a|a)"        , "aa"  , false);

  is_valid("@*"           , "aa"  , false);
  is_valid("a*"           , "aa"  , true );
  is_valid("(@|@)*"       , "aa"  , false);
  is_valid("(a|@)*"       , "aa"  , true );
  is_valid("(@|a)*"       , "aa"  , true );
  is_valid("(a|a)*"       , "aa"  , true );

  is_valid("@@"           , "aa"  , false);
  is_valid("@a"           , "aa"  , false);
  is_valid("a@"           , "aa"  , false);
  is_valid("aa"           , "aa"  , true );
  is_valid("ab"           , "aa"  , false);
  is_valid("(@|@)(@|@)"   , "aa"  , false);
  is_valid("(@|@)(a|@)"   , "aa"  , false);
  is_valid("(@|@)(@|a)"   , "aa"  , false);
  is_valid("(@|@)(a|a)"   , "aa"  , false);
  is_valid("(a|@)(@|@)"   , "aa"  , false);
  is_valid("(a|@)(a|@)"   , "aa"  , true );
  is_valid("(a|@)(@|a)"   , "aa"  , true );
  is_valid("(a|@)(a|a)"   , "aa"  , true );
  is_valid("(@|a)(@|@)"   , "aa"  , false);
  is_valid("(@|a)(a|@)"   , "aa"  , true );
  is_valid("(@|a)(@|a)"   , "aa"  , true );
  is_valid("(@|a)(a|a)"   , "aa"  , true );
  is_valid("(a|a)(@|@)"   , "aa"  , false);
  is_valid("(a|a)(a|@)"   , "aa"  , true );
  is_valid("(a|a)(@|a)"   , "aa"  , true );
  is_valid("(a|a)(a|a)"   , "aa"  , true );

  is_valid("@*@"          , "aa"  , false);
  is_valid("@*a"          , "aa"  , false);
  is_valid("a*@"          , "aa"  , true );
  is_valid("a*a"          , "aa"  , true );
  is_valid("a*b"          , "aa"  , false);
  is_valid("(@|@)*(@|@)"  , "aa"  , false);
  is_valid("(@|@)*(a|@)"  , "aa"  , false);
  is_valid("(@|@)*(@|a)"  , "aa"  , false);
  is_valid("(@|@)*(a|a)"  , "aa"  , false);
  is_valid("(a|@)*(@|@)"  , "aa"  , true );
  is_valid("(a|@)*(a|@)"  , "aa"  , true );
  is_valid("(a|@)*(@|a)"  , "aa"  , true );
  is_valid("(a|@)*(a|a)"  , "aa"  , true );
  is_valid("(@|a)*(@|@)"  , "aa"  , true );
  is_valid("(@|a)*(a|@)"  , "aa"  , true );
  is_valid("(@|a)*(@|a)"  , "aa"  , true );
  is_valid("(@|a)*(a|a)"  , "aa"  , true );
  is_valid("(a|a)*(@|@)"  , "aa"  , true );
  is_valid("(a|a)*(a|@)"  , "aa"  , true );
  is_valid("(a|a)*(@|a)"  , "aa"  , true );
  is_valid("(a|a)*(a|a)"  , "aa"  , true );

  is_valid("@@*"          , "aa"  , false);
  is_valid("@a*"          , "aa"  , true );
  is_valid("a@*"          , "aa"  , false);
  is_valid("aa*"          , "aa"  , true );
  is_valid("ab*"          , "aa"  , false);
  is_valid("(@|@)(@|@)*"  , "aa"  , false);
  is_valid("(@|@)(a|@)*"  , "aa"  , true );
  is_valid("(@|@)(@|a)*"  , "aa"  , true );
  is_valid("(@|@)(a|a)*"  , "aa"  , true );
  is_valid("(a|@)(@|@)*"  , "aa"  , false);
  is_valid("(a|@)(a|@)*"  , "aa"  , true );
  is_valid("(a|@)(@|a)*"  , "aa"  , true );
  is_valid("(a|@)(a|a)*"  , "aa"  , true );
  is_valid("(@|a)(@|@)*"  , "aa"  , false);
  is_valid("(@|a)(a|@)*"  , "aa"  , true );
  is_valid("(@|a)(@|a)*"  , "aa"  , true );
  is_valid("(@|a)(a|a)*"  , "aa"  , true );
  is_valid("(a|a)(@|@)*"  , "aa"  , false);
  is_valid("(a|a)(a|@)*"  , "aa"  , true );
  is_valid("(a|a)(@|a)*"  , "aa"  , true );
  is_valid("(a|a)(a|a)*"  , "aa"  , true );

  is_valid("@*@*"         , "aa"  , false);
  is_valid("@*a*"         , "aa"  , true );
  is_valid("a*@*"         , "aa"  , true );
  is_valid("a*a*"         , "aa"  , true );
  is_valid("a*b*"         , "aa"  , true );
  is_valid("(@|@)*(@|@)*" , "aa"  , false);
  is_valid("(@|@)*(a|@)*" , "aa"  , true );
  is_valid("(@|@)*(@|a)*" , "aa"  , true );
  is_valid("(@|@)*(a|a)*" , "aa"  , true );
  is_valid("(a|@)*(@|@)*" , "aa"  , true );
  is_valid("(a|@)*(a|@)*" , "aa"  , true );
  is_valid("(a|@)*(@|a)*" , "aa"  , true );
  is_valid("(a|@)*(a|a)*" , "aa"  , true );
  is_valid("(@|a)*(@|@)*" , "aa"  , true );
  is_valid("(@|a)*(a|@)*" , "aa"  , true );
  is_valid("(@|a)*(@|a)*" , "aa"  , true );
  is_valid("(@|a)*(a|a)*" , "aa"  , true );
  is_valid("(a|a)*(@|@)*" , "aa"  , true );
  is_valid("(a|a)*(a|@)*" , "aa"  , true );
  is_valid("(a|a)*(@|a)*" , "aa"  , true );
  is_valid("(a|a)*(a|a)*" , "aa"  , true );/*}}}*/
  is_valid(""             , "aaa" , false);/*{{{*/
  is_valid("@"            , "aaa" , false);
  is_valid("a"            , "aaa" , false);
  is_valid("(@|@)"        , "aaa" , false);
  is_valid("(a|@)"        , "aaa" , false);
  is_valid("(@|a)"        , "aaa" , false);
  is_valid("(a|a)"        , "aaa" , false);

  is_valid("@*"           , "aaa" , false);
  is_valid("a*"           , "aaa" , true );
  is_valid("(@|@)*"       , "aaa" , false);
  is_valid("(a|@)*"       , "aaa" , true );
  is_valid("(@|a)*"       , "aaa" , true );
  is_valid("(a|a)*"       , "aaa" , true );

  is_valid("@@"           , "aaa" , false);
  is_valid("@a"           , "aaa" , false);
  is_valid("a@"           , "aaa" , false);
  is_valid("aa"           , "aaa" , false);
  is_valid("ab"           , "aaa" , false);
  is_valid("(@|@)(@|@)"   , "aaa" , false);
  is_valid("(@|@)(a|@)"   , "aaa" , false);
  is_valid("(@|@)(@|a)"   , "aaa" , false);
  is_valid("(@|@)(a|a)"   , "aaa" , false);
  is_valid("(a|@)(@|@)"   , "aaa" , false);
  is_valid("(a|@)(a|@)"   , "aaa" , false);
  is_valid("(a|@)(@|a)"   , "aaa" , false);
  is_valid("(a|@)(a|a)"   , "aaa" , false);
  is_valid("(@|a)(@|@)"   , "aaa" , false);
  is_valid("(@|a)(a|@)"   , "aaa" , false);
  is_valid("(@|a)(@|a)"   , "aaa" , false);
  is_valid("(@|a)(a|a)"   , "aaa" , false);
  is_valid("(a|a)(@|@)"   , "aaa" , false);
  is_valid("(a|a)(a|@)"   , "aaa" , false);
  is_valid("(a|a)(@|a)"   , "aaa" , false);
  is_valid("(a|a)(a|a)"   , "aaa" , false);

  is_valid("@*@"          , "aaa" , false);
  is_valid("@*a"          , "aaa" , false);
  is_valid("a*@"          , "aaa" , true );
  is_valid("a*a"          , "aaa" , true );
  is_valid("a*b"          , "aaa" , false);
  is_valid("(@|@)*(@|@)"  , "aaa" , false);
  is_valid("(@|@)*(a|@)"  , "aaa" , false);
  is_valid("(@|@)*(@|a)"  , "aaa" , false);
  is_valid("(@|@)*(a|a)"  , "aaa" , false);
  is_valid("(a|@)*(@|@)"  , "aaa" , true );
  is_valid("(a|@)*(a|@)"  , "aaa" , true );
  is_valid("(a|@)*(@|a)"  , "aaa" , true );
  is_valid("(a|@)*(a|a)"  , "aaa" , true );
  is_valid("(@|a)*(@|@)"  , "aaa" , true );
  is_valid("(@|a)*(a|@)"  , "aaa" , true );
  is_valid("(@|a)*(@|a)"  , "aaa" , true );
  is_valid("(@|a)*(a|a)"  , "aaa" , true );
  is_valid("(a|a)*(@|@)"  , "aaa" , true );
  is_valid("(a|a)*(a|@)"  , "aaa" , true );
  is_valid("(a|a)*(@|a)"  , "aaa" , true );
  is_valid("(a|a)*(a|a)"  , "aaa" , true );

  is_valid("@@*"          , "aaa" , false);
  is_valid("@a*"          , "aaa" , true );
  is_valid("a@*"          , "aaa" , false);
  is_valid("aa*"          , "aaa" , true );
  is_valid("ab*"          , "aaa" , false);
  is_valid("(@|@)(@|@)*"  , "aaa" , false);
  is_valid("(@|@)(a|@)*"  , "aaa" , true );
  is_valid("(@|@)(@|a)*"  , "aaa" , true );
  is_valid("(@|@)(a|a)*"  , "aaa" , true );
  is_valid("(a|@)(@|@)*"  , "aaa" , false);
  is_valid("(a|@)(a|@)*"  , "aaa" , true );
  is_valid("(a|@)(@|a)*"  , "aaa" , true );
  is_valid("(a|@)(a|a)*"  , "aaa" , true );
  is_valid("(@|a)(@|@)*"  , "aaa" , false);
  is_valid("(@|a)(a|@)*"  , "aaa" , true );
  is_valid("(@|a)(@|a)*"  , "aaa" , true );
  is_valid("(@|a)(a|a)*"  , "aaa" , true );
  is_valid("(a|a)(@|@)*"  , "aaa" , false);
  is_valid("(a|a)(a|@)*"  , "aaa" , true );
  is_valid("(a|a)(@|a)*"  , "aaa" , true );
  is_valid("(a|a)(a|a)*"  , "aaa" , true );

  is_valid("@*@*"         , "aaa" , false);
  is_valid("@*a*"         , "aaa" , true );
  is_valid("a*@*"         , "aaa" , true );
  is_valid("a*a*"         , "aaa" , true );
  is_valid("a*b*"         , "aaa" , true );
  is_valid("(@|@)*(@|@)*" , "aaa" , false);
  is_valid("(@|@)*(a|@)*" , "aaa" , true );
  is_valid("(@|@)*(@|a)*" , "aaa" , true );
  is_valid("(@|@)*(a|a)*" , "aaa" , true );
  is_valid("(a|@)*(@|@)*" , "aaa" , true );
  is_valid("(a|@)*(a|@)*" , "aaa" , true );
  is_valid("(a|@)*(@|a)*" , "aaa" , true );
  is_valid("(a|@)*(a|a)*" , "aaa" , true );
  is_valid("(@|a)*(@|@)*" , "aaa" , true );
  is_valid("(@|a)*(a|@)*" , "aaa" , true );
  is_valid("(@|a)*(@|a)*" , "aaa" , true );
  is_valid("(@|a)*(a|a)*" , "aaa" , true );
  is_valid("(a|a)*(@|@)*" , "aaa" , true );
  is_valid("(a|a)*(a|@)*" , "aaa" , true );
  is_valid("(a|a)*(@|a)*" , "aaa" , true );
  is_valid("(a|a)*(a|a)*" , "aaa" , true );/*}}}*/
  is_valid(""             , "ab"  , false);/*{{{*/
  is_valid("@"            , "ab"  , false);
  is_valid("a"            , "ab"  , false);
  is_valid("(@|@)"        , "ab"  , false);
  is_valid("(a|@)"        , "ab"  , false);
  is_valid("(@|a)"        , "ab"  , false);
  is_valid("(a|a)"        , "ab"  , false);

  is_valid("@*"           , "ab"  , false);
  is_valid("a*"           , "ab"  , false);
  is_valid("(@|@)*"       , "ab"  , false);
  is_valid("(a|@)*"       , "ab"  , false);
  is_valid("(@|a)*"       , "ab"  , false);
  is_valid("(a|a)*"       , "ab"  , false);

  is_valid("@@"           , "ab"  , false);
  is_valid("@a"           , "ab"  , false);
  is_valid("a@"           , "ab"  , false);
  is_valid("aa"           , "ab"  , false);
  is_valid("ab"           , "ab"  , true );
  is_valid("(@|@)(@|@)"   , "ab"  , false);
  is_valid("(@|@)(a|@)"   , "ab"  , false);
  is_valid("(@|@)(@|a)"   , "ab"  , false);
  is_valid("(@|@)(a|a)"   , "ab"  , false);
  is_valid("(a|@)(@|@)"   , "ab"  , false);
  is_valid("(a|@)(a|@)"   , "ab"  , false);
  is_valid("(a|@)(@|a)"   , "ab"  , false);
  is_valid("(a|@)(a|a)"   , "ab"  , false);
  is_valid("(@|a)(@|@)"   , "ab"  , false);
  is_valid("(@|a)(a|@)"   , "ab"  , false);
  is_valid("(@|a)(@|a)"   , "ab"  , false);
  is_valid("(@|a)(a|a)"   , "ab"  , false);
  is_valid("(a|a)(@|@)"   , "ab"  , false);
  is_valid("(a|a)(a|@)"   , "ab"  , false);
  is_valid("(a|a)(@|a)"   , "ab"  , false);
  is_valid("(a|a)(a|a)"   , "ab"  , false);

  is_valid("@*@"          , "ab"  , false);
  is_valid("@*a"          , "ab"  , false);
  is_valid("a*@"          , "ab"  , false);
  is_valid("a*a"          , "ab"  , false);
  is_valid("a*b"          , "ab"  , true );
  is_valid("(@|@)*(@|@)"  , "ab"  , false);
  is_valid("(@|@)*(a|@)"  , "ab"  , false);
  is_valid("(@|@)*(@|a)"  , "ab"  , false);
  is_valid("(@|@)*(a|a)"  , "ab"  , false);
  is_valid("(a|@)*(@|@)"  , "ab"  , false);
  is_valid("(a|@)*(a|@)"  , "ab"  , false);
  is_valid("(a|@)*(@|a)"  , "ab"  , false);
  is_valid("(a|@)*(a|a)"  , "ab"  , false);
  is_valid("(@|a)*(@|@)"  , "ab"  , false);
  is_valid("(@|a)*(a|@)"  , "ab"  , false);
  is_valid("(@|a)*(@|a)"  , "ab"  , false);
  is_valid("(@|a)*(a|a)"  , "ab"  , false);
  is_valid("(a|a)*(@|@)"  , "ab"  , false);
  is_valid("(a|a)*(a|@)"  , "ab"  , false);
  is_valid("(a|a)*(@|a)"  , "ab"  , false);
  is_valid("(a|a)*(a|a)"  , "ab"  , false);

  is_valid("@@*"          , "ab"  , false);
  is_valid("@a*"          , "ab"  , false);
  is_valid("a@*"          , "ab"  , false);
  is_valid("aa*"          , "ab"  , false);
  is_valid("ab*"          , "ab"  , true );
  is_valid("(@|@)(@|@)*"  , "ab"  , false);
  is_valid("(@|@)(a|@)*"  , "ab"  , false);
  is_valid("(@|@)(@|a)*"  , "ab"  , false);
  is_valid("(@|@)(a|a)*"  , "ab"  , false);
  is_valid("(a|@)(@|@)*"  , "ab"  , false);
  is_valid("(a|@)(a|@)*"  , "ab"  , false);
  is_valid("(a|@)(@|a)*"  , "ab"  , false);
  is_valid("(a|@)(a|a)*"  , "ab"  , false);
  is_valid("(@|a)(@|@)*"  , "ab"  , false);
  is_valid("(@|a)(a|@)*"  , "ab"  , false);
  is_valid("(@|a)(@|a)*"  , "ab"  , false);
  is_valid("(@|a)(a|a)*"  , "ab"  , false);
  is_valid("(a|a)(@|@)*"  , "ab"  , false);
  is_valid("(a|a)(a|@)*"  , "ab"  , false);
  is_valid("(a|a)(@|a)*"  , "ab"  , false);
  is_valid("(a|a)(a|a)*"  , "ab"  , false);

  is_valid("@*@*"         , "ab"  , false);
  is_valid("@*a*"         , "ab"  , false);
  is_valid("a*@*"         , "ab"  , false);
  is_valid("a*a*"         , "ab"  , false);
  is_valid("a*b*"         , "ab"  , true );
  is_valid("(@|@)*(@|@)*" , "ab"  , false);
  is_valid("(@|@)*(a|@)*" , "ab"  , false);
  is_valid("(@|@)*(@|a)*" , "ab"  , false);
  is_valid("(@|@)*(a|a)*" , "ab"  , false);
  is_valid("(a|@)*(@|@)*" , "ab"  , false);
  is_valid("(a|@)*(a|@)*" , "ab"  , false);
  is_valid("(a|@)*(@|a)*" , "ab"  , false);
  is_valid("(a|@)*(a|a)*" , "ab"  , false);
  is_valid("(@|a)*(@|@)*" , "ab"  , false);
  is_valid("(@|a)*(a|@)*" , "ab"  , false);
  is_valid("(@|a)*(@|a)*" , "ab"  , false);
  is_valid("(@|a)*(a|a)*" , "ab"  , false);
  is_valid("(a|a)*(@|@)*" , "ab"  , false);
  is_valid("(a|a)*(a|@)*" , "ab"  , false);
  is_valid("(a|a)*(@|a)*" , "ab"  , false);
  is_valid("(a|a)*(a|a)*" , "ab"  , false);/*}}}*/
  is_valid(""             , "ba"  , false);/*{{{*/
  is_valid("@"            , "ba"  , false);
  is_valid("a"            , "ba"  , false);
  is_valid("(@|@)"        , "ba"  , false);
  is_valid("(a|@)"        , "ba"  , false);
  is_valid("(@|a)"        , "ba"  , false);
  is_valid("(a|a)"        , "ba"  , false);

  is_valid("@*"           , "ba"  , false);
  is_valid("a*"           , "ba"  , false);
  is_valid("(@|@)*"       , "ba"  , false);
  is_valid("(a|@)*"       , "ba"  , false);
  is_valid("(@|a)*"       , "ba"  , false);
  is_valid("(a|a)*"       , "ba"  , false);

  is_valid("@@"           , "ba"  , false);
  is_valid("@a"           , "ba"  , false);
  is_valid("a@"           , "ba"  , false);
  is_valid("aa"           , "ba"  , false);
  is_valid("ab"           , "ba"  , false);
  is_valid("(@|@)(@|@)"   , "ba"  , false);
  is_valid("(@|@)(a|@)"   , "ba"  , false);
  is_valid("(@|@)(@|a)"   , "ba"  , false);
  is_valid("(@|@)(a|a)"   , "ba"  , false);
  is_valid("(a|@)(@|@)"   , "ba"  , false);
  is_valid("(a|@)(a|@)"   , "ba"  , false);
  is_valid("(a|@)(@|a)"   , "ba"  , false);
  is_valid("(a|@)(a|a)"   , "ba"  , false);
  is_valid("(@|a)(@|@)"   , "ba"  , false);
  is_valid("(@|a)(a|@)"   , "ba"  , false);
  is_valid("(@|a)(@|a)"   , "ba"  , false);
  is_valid("(@|a)(a|a)"   , "ba"  , false);
  is_valid("(a|a)(@|@)"   , "ba"  , false);
  is_valid("(a|a)(a|@)"   , "ba"  , false);
  is_valid("(a|a)(@|a)"   , "ba"  , false);
  is_valid("(a|a)(a|a)"   , "ba"  , false);

  is_valid("@*@"          , "ba"  , false);
  is_valid("@*a"          , "ba"  , false);
  is_valid("a*@"          , "ba"  , false);
  is_valid("a*a"          , "ba"  , false);
  is_valid("a*b"          , "ba"  , false);
  is_valid("(@|@)*(@|@)"  , "ba"  , false);
  is_valid("(@|@)*(a|@)"  , "ba"  , false);
  is_valid("(@|@)*(@|a)"  , "ba"  , false);
  is_valid("(@|@)*(a|a)"  , "ba"  , false);
  is_valid("(a|@)*(@|@)"  , "ba"  , false);
  is_valid("(a|@)*(a|@)"  , "ba"  , false);
  is_valid("(a|@)*(@|a)"  , "ba"  , false);
  is_valid("(a|@)*(a|a)"  , "ba"  , false);
  is_valid("(@|a)*(@|@)"  , "ba"  , false);
  is_valid("(@|a)*(a|@)"  , "ba"  , false);
  is_valid("(@|a)*(@|a)"  , "ba"  , false);
  is_valid("(@|a)*(a|a)"  , "ba"  , false);
  is_valid("(a|a)*(@|@)"  , "ba"  , false);
  is_valid("(a|a)*(a|@)"  , "ba"  , false);
  is_valid("(a|a)*(@|a)"  , "ba"  , false);
  is_valid("(a|a)*(a|a)"  , "ba"  , false);

  is_valid("@@*"          , "ba"  , false);
  is_valid("@a*"          , "ba"  , false);
  is_valid("a@*"          , "ba"  , false);
  is_valid("aa*"          , "ba"  , false);
  is_valid("ab*"          , "ba"  , false);
  is_valid("(@|@)(@|@)*"  , "ba"  , false);
  is_valid("(@|@)(a|@)*"  , "ba"  , false);
  is_valid("(@|@)(@|a)*"  , "ba"  , false);
  is_valid("(@|@)(a|a)*"  , "ba"  , false);
  is_valid("(a|@)(@|@)*"  , "ba"  , false);
  is_valid("(a|@)(a|@)*"  , "ba"  , false);
  is_valid("(a|@)(@|a)*"  , "ba"  , false);
  is_valid("(a|@)(a|a)*"  , "ba"  , false);
  is_valid("(@|a)(@|@)*"  , "ba"  , false);
  is_valid("(@|a)(a|@)*"  , "ba"  , false);
  is_valid("(@|a)(@|a)*"  , "ba"  , false);
  is_valid("(@|a)(a|a)*"  , "ba"  , false);
  is_valid("(a|a)(@|@)*"  , "ba"  , false);
  is_valid("(a|a)(a|@)*"  , "ba"  , false);
  is_valid("(a|a)(@|a)*"  , "ba"  , false);
  is_valid("(a|a)(a|a)*"  , "ba"  , false);

  is_valid("@*@*"         , "ba"  , false);
  is_valid("@*a*"         , "ba"  , false);
  is_valid("a*@*"         , "ba"  , false);
  is_valid("a*a*"         , "ba"  , false);
  is_valid("a*b*"         , "ba"  , false);
  is_valid("(@|@)*(@|@)*" , "ba"  , false);
  is_valid("(@|@)*(a|@)*" , "ba"  , false);
  is_valid("(@|@)*(@|a)*" , "ba"  , false);
  is_valid("(@|@)*(a|a)*" , "ba"  , false);
  is_valid("(a|@)*(@|@)*" , "ba"  , false);
  is_valid("(a|@)*(a|@)*" , "ba"  , false);
  is_valid("(a|@)*(@|a)*" , "ba"  , false);
  is_valid("(a|@)*(a|a)*" , "ba"  , false);
  is_valid("(@|a)*(@|@)*" , "ba"  , false);
  is_valid("(@|a)*(a|@)*" , "ba"  , false);
  is_valid("(@|a)*(@|a)*" , "ba"  , false);
  is_valid("(@|a)*(a|a)*" , "ba"  , false);
  is_valid("(a|a)*(@|@)*" , "ba"  , false);
  is_valid("(a|a)*(a|@)*" , "ba"  , false);
  is_valid("(a|a)*(@|a)*" , "ba"  , false);
  is_valid("(a|a)*(a|a)*" , "ba"  , false);/*}}}*/

  // エスケープシーケンス
  is_valid( "\\\\", "a"     , false);/*{{{*/
  is_valid( "\\\\", "aa"    , false);
  is_valid( "\\\\", "aaa"   , false);
  is_valid( "\\\\", "ab"    , false);
  is_valid( "\\\\", "aba"   , false);
  is_valid( "\\\\", "\\\\"  , false);
  is_valid( "\\\\", "\\("   , false);
  is_valid( "\\\\", "\\)"   , false);
  is_valid( "\\\\", "\\|"   , false);
  is_valid( "\\\\", "\\*"   , false);
  is_valid( "\\\\", "\\@"   , false);
  is_valid( "\\\\", "a\\\\" , false);
  is_valid( "\\\\", "a\\("  , false);
  is_valid( "\\\\", "a\\)"  , false);
  is_valid( "\\\\", "a\\|"  , false);
  is_valid( "\\\\", "a\\*"  , false);
  is_valid( "\\\\", "a\\@"  , false);
  is_valid( "\\\\", "\\(a"  , false);
  is_valid( "\\\\", "\\)a"  , false);
  is_valid( "\\\\", "\\|a"  , false);
  is_valid( "\\\\", "\\*a"  , false);
  is_valid( "\\\\", "\\@a"  , false);
  is_valid( "\\\\", "\\"    , true );
  is_valid( "\\\\", "("     , false);
  is_valid( "\\\\", ")"     , false);
  is_valid( "\\\\", "|"     , false);
  is_valid( "\\\\", "*"     , false);
  is_valid( "\\\\", "@"     , false);
  is_valid( "\\\\", "a\\"   , false);
  is_valid( "\\\\", "a("    , false);
  is_valid( "\\\\", "a)"    , false);
  is_valid( "\\\\", "a|"    , false);
  is_valid( "\\\\", "a*"    , false);
  is_valid( "\\\\", "a@"    , false);
  is_valid( "\\\\", "(a"    , false);
  is_valid( "\\\\", ")a"    , false);
  is_valid( "\\\\", "|a"    , false);
  is_valid( "\\\\", "*a"    , false);
  is_valid( "\\\\", "@a"    , false);

  is_valid("a\\\\", "a"     , false);
  is_valid("a\\\\", "aa"    , false);
  is_valid("a\\\\", "aaa"   , false);
  is_valid("a\\\\", "ab"    , false);
  is_valid("a\\\\", "aba"   , false);
  is_valid("a\\\\", "\\\\"  , false);
  is_valid("a\\\\", "\\("   , false);
  is_valid("a\\\\", "\\)"   , false);
  is_valid("a\\\\", "\\|"   , false);
  is_valid("a\\\\", "\\*"   , false);
  is_valid("a\\\\", "\\@"   , false);
  is_valid("a\\\\", "a\\\\" , false);
  is_valid("a\\\\", "a\\("  , false);
  is_valid("a\\\\", "a\\)"  , false);
  is_valid("a\\\\", "a\\|"  , false);
  is_valid("a\\\\", "a\\*"  , false);
  is_valid("a\\\\", "a\\@"  , false);
  is_valid("a\\\\", "\\\\a" , false);
  is_valid("a\\\\", "\\(a"  , false);
  is_valid("a\\\\", "\\)a"  , false);
  is_valid("a\\\\", "\\|a"  , false);
  is_valid("a\\\\", "\\*a"  , false);
  is_valid("a\\\\", "\\@a"  , false);
  is_valid("a\\\\", "\\"    , false);
  is_valid("a\\\\", "("     , false);
  is_valid("a\\\\", ")"     , false);
  is_valid("a\\\\", "|"     , false);
  is_valid("a\\\\", "*"     , false);
  is_valid("a\\\\", "@"     , false);
  is_valid("a\\\\", "a\\"   , true );
  is_valid("a\\\\", "a("    , false);
  is_valid("a\\\\", "a)"    , false);
  is_valid("a\\\\", "a|"    , false);
  is_valid("a\\\\", "a*"    , false);
  is_valid("a\\\\", "a@"    , false);
  is_valid("a\\\\", "\\a"   , false);
  is_valid("a\\\\", "(a"    , false);
  is_valid("a\\\\", ")a"    , false);
  is_valid("a\\\\", "|a"    , false);
  is_valid("a\\\\", "*a"    , false);
  is_valid("a\\\\", "@a"    , false);

  is_valid("\\\\a", "a"     , false);
  is_valid("\\\\a", "aa"    , false);
  is_valid("\\\\a", "aaa"   , false);
  is_valid("\\\\a", "ab"    , false);
  is_valid("\\\\a", "aba"   , false);
  is_valid("\\\\a", "\\\\"  , false);
  is_valid("\\\\a", "\\("   , false);
  is_valid("\\\\a", "\\)"   , false);
  is_valid("\\\\a", "\\|"   , false);
  is_valid("\\\\a", "\\*"   , false);
  is_valid("\\\\a", "\\@"   , false);
  is_valid("\\\\a", "a\\\\" , false);
  is_valid("\\\\a", "a\\("  , false);
  is_valid("\\\\a", "a\\)"  , false);
  is_valid("\\\\a", "a\\|"  , false);
  is_valid("\\\\a", "a\\*"  , false);
  is_valid("\\\\a", "a\\@"  , false);
  is_valid("\\\\a", "\\\\a" , false);
  is_valid("\\\\a", "\\(a"  , false);
  is_valid("\\\\a", "\\)a"  , false);
  is_valid("\\\\a", "\\|a"  , false);
  is_valid("\\\\a", "\\*a"  , false);
  is_valid("\\\\a", "@a"    , false);
  is_valid("\\\\a", "\\"    , false);
  is_valid("\\\\a", "("     , false);
  is_valid("\\\\a", ")"     , false);
  is_valid("\\\\a", "|"     , false);
  is_valid("\\\\a", "*"     , false);
  is_valid("\\\\a", "@"     , false);
  is_valid("\\\\a", "a\\"   , false);
  is_valid("\\\\a", "a("    , false);
  is_valid("\\\\a", "a)"    , false);
  is_valid("\\\\a", "a|"    , false);
  is_valid("\\\\a", "a*"    , false);
  is_valid("\\\\a", "a@"    , false);
  is_valid("\\\\a", "\\a"   , true );
  is_valid("\\\\a", "(a"    , false);
  is_valid("\\\\a", ")a"    , false);
  is_valid("\\\\a", "|a"    , false);
  is_valid("\\\\a", "*a"    , false);
  is_valid("\\\\a", "@a"    , false);/*}}}*/
  is_valid( "\\(" , "a"     , false);/*{{{*/
  is_valid( "\\(" , "aa"    , false);
  is_valid( "\\(" , "aaa"   , false);
  is_valid( "\\(" , "ab"    , false);
  is_valid( "\\(" , "aba"   , false);
  is_valid( "\\(" , "\\\\"  , false);
  is_valid( "\\(" , "\\("   , false);
  is_valid( "\\(" , "\\)"   , false);
  is_valid( "\\(" , "\\|"   , false);
  is_valid( "\\(" , "\\*"   , false);
  is_valid( "\\(" , "\\@"   , false);
  is_valid( "\\(" , "a\\\\" , false);
  is_valid( "\\(" , "a\\("  , false);
  is_valid( "\\(" , "a\\)"  , false);
  is_valid( "\\(" , "a\\|"  , false);
  is_valid( "\\(" , "a\\*"  , false);
  is_valid( "\\(" , "a\\@"  , false);
  is_valid( "\\(" , "\\\\a" , false);
  is_valid( "\\(" , "\\(a"  , false);
  is_valid( "\\(" , "\\)a"  , false);
  is_valid( "\\(" , "\\|a"  , false);
  is_valid( "\\(" , "\\*a"  , false);
  is_valid( "\\(" , "\\@a"  , false);
  is_valid( "\\(" , "\\"    , false);
  is_valid( "\\(" , "("     , true );
  is_valid( "\\(" , ")"     , false);
  is_valid( "\\(" , "|"     , false);
  is_valid( "\\(" , "*"     , false);
  is_valid( "\\(" , "@"     , false);
  is_valid( "\\(" , "a\\"   , false);
  is_valid( "\\(" , "a("    , false);
  is_valid( "\\(" , "a)"    , false);
  is_valid( "\\(" , "a|"    , false);
  is_valid( "\\(" , "a*"    , false);
  is_valid( "\\(" , "a@"    , false);
  is_valid( "\\(" , "\\a"   , false);
  is_valid( "\\(" , "(a"    , false);
  is_valid( "\\(" , ")a"    , false);
  is_valid( "\\(" , "|a"    , false);
  is_valid( "\\(" , "*a"    , false);
  is_valid( "\\(" , "@a"    , false);

  is_valid("a\\(" , "a"     , false);
  is_valid("a\\(" , "aa"    , false);
  is_valid("a\\(" , "aaa"   , false);
  is_valid("a\\(" , "ab"    , false);
  is_valid("a\\(" , "aba"   , false);
  is_valid("a\\(" , "\\\\"  , false);
  is_valid("a\\(" , "\\("   , false);
  is_valid("a\\(" , "\\)"   , false);
  is_valid("a\\(" , "\\|"   , false);
  is_valid("a\\(" , "\\*"   , false);
  is_valid("a\\(" , "\\@"   , false);
  is_valid("a\\(" , "a\\\\" , false);
  is_valid("a\\(" , "a\\("  , false);
  is_valid("a\\(" , "a\\)"  , false);
  is_valid("a\\(" , "a\\|"  , false);
  is_valid("a\\(" , "a\\*"  , false);
  is_valid("a\\(" , "a\\@"  , false);
  is_valid("a\\(" , "\\\\a" , false);
  is_valid("a\\(" , "\\(a"  , false);
  is_valid("a\\(" , "\\)a"  , false);
  is_valid("a\\(" , "\\|a"  , false);
  is_valid("a\\(" , "\\*a"  , false);
  is_valid("a\\(" , "\\@a"  , false);
  is_valid("a\\(" , "\\"    , false);
  is_valid("a\\(" , "("     , false);
  is_valid("a\\(" , ")"     , false);
  is_valid("a\\(" , "|"     , false);
  is_valid("a\\(" , "*"     , false);
  is_valid("a\\(" , "@"     , false);
  is_valid("a\\(" , "a\\"   , false);
  is_valid("a\\(" , "a("    , true );
  is_valid("a\\(" , "a)"    , false);
  is_valid("a\\(" , "a|"    , false);
  is_valid("a\\(" , "a*"    , false);
  is_valid("a\\(" , "a@"    , false);
  is_valid("a\\(" , "\\a"   , false);
  is_valid("a\\(" , "(a"    , false);
  is_valid("a\\(" , ")a"    , false);
  is_valid("a\\(" , "|a"    , false);
  is_valid("a\\(" , "*a"    , false);
  is_valid("a\\(" , "@a"    , false);

  is_valid("\\(a" , "a"     , false);
  is_valid("\\(a" , "aa"    , false);
  is_valid("\\(a" , "aaa"   , false);
  is_valid("\\(a" , "ab"    , false);
  is_valid("\\(a" , "aba"   , false);
  is_valid("\\(a" , "\\\\"  , false);
  is_valid("\\(a" , "\\("   , false);
  is_valid("\\(a" , "\\)"   , false);
  is_valid("\\(a" , "\\|"   , false);
  is_valid("\\(a" , "\\*"   , false);
  is_valid("\\(a" , "\\@"   , false);
  is_valid("\\(a" , "a\\\\" , false);
  is_valid("\\(a" , "a\\("  , false);
  is_valid("\\(a" , "a\\)"  , false);
  is_valid("\\(a" , "a\\|"  , false);
  is_valid("\\(a" , "a\\*"  , false);
  is_valid("\\(a" , "a\\@"  , false);
  is_valid("\\(a" , "\\\\a" , false);
  is_valid("\\(a" , "\\(a"  , false);
  is_valid("\\(a" , "\\)a"  , false);
  is_valid("\\(a" , "\\|a"  , false);
  is_valid("\\(a" , "\\*a"  , false);
  is_valid("\\(a" , "\\@a"  , false);
  is_valid("\\(a" , "\\"    , false);
  is_valid("\\(a" , "("     , false);
  is_valid("\\(a" , ")"     , false);
  is_valid("\\(a" , "|"     , false);
  is_valid("\\(a" , "*"     , false);
  is_valid("\\(a" , "@"     , false);
  is_valid("\\(a" , "a\\"   , false);
  is_valid("\\(a" , "a("    , false);
  is_valid("\\(a" , "a)"    , false);
  is_valid("\\(a" , "a|"    , false);
  is_valid("\\(a" , "a*"    , false);
  is_valid("\\(a" , "a@"    , false);
  is_valid("\\(a" , "\\a"   , false);
  is_valid("\\(a" , "(a"    , true );
  is_valid("\\(a" , ")a"    , false);
  is_valid("\\(a" , "|a"    , false);
  is_valid("\\(a" , "*a"    , false);
  is_valid("\\(a" , "@a"    , false);/*}}}*/
  is_valid( "\\)" , "a"     , false);/*{{{*/
  is_valid( "\\)" , "aa"    , false);
  is_valid( "\\)" , "aaa"   , false);
  is_valid( "\\)" , "ab"    , false);
  is_valid( "\\)" , "aba"   , false);
  is_valid( "\\)" , "\\\\"  , false);
  is_valid( "\\)" , "\\("   , false);
  is_valid( "\\)" , "\\)"   , false);
  is_valid( "\\)" , "\\|"   , false);
  is_valid( "\\)" , "\\*"   , false);
  is_valid( "\\)" , "\\@"   , false);
  is_valid( "\\)" , "a\\\\" , false);
  is_valid( "\\)" , "a\\("  , false);
  is_valid( "\\)" , "a\\)"  , false);
  is_valid( "\\)" , "a\\|"  , false);
  is_valid( "\\)" , "a\\*"  , false);
  is_valid( "\\)" , "a\\@"  , false);
  is_valid( "\\)" , "\\\\a" , false);
  is_valid( "\\)" , "\\(a"  , false);
  is_valid( "\\)" , "\\)a"  , false);
  is_valid( "\\)" , "\\|a"  , false);
  is_valid( "\\)" , "\\*a"  , false);
  is_valid( "\\)" , "\\@a"  , false);
  is_valid( "\\)" , "\\"    , false);
  is_valid( "\\)" , "("     , false);
  is_valid( "\\)" , ")"     , true );
  is_valid( "\\)" , "|"     , false);
  is_valid( "\\)" , "*"     , false);
  is_valid( "\\)" , "@"     , false);
  is_valid( "\\)" , "a\\"   , false);
  is_valid( "\\)" , "a("    , false);
  is_valid( "\\)" , "a)"    , false);
  is_valid( "\\)" , "a|"    , false);
  is_valid( "\\)" , "a*"    , false);
  is_valid( "\\)" , "a@"    , false);
  is_valid( "\\)" , "\\a"   , false);
  is_valid( "\\)" , "(a"    , false);
  is_valid( "\\)" , ")a"    , false);
  is_valid( "\\)" , "|a"    , false);
  is_valid( "\\)" , "*a"    , false);
  is_valid( "\\)" , "@a"    , false);

  is_valid("a\\)" , "a"     , false);
  is_valid("a\\)" , "aa"    , false);
  is_valid("a\\)" , "aaa"   , false);
  is_valid("a\\)" , "ab"    , false);
  is_valid("a\\)" , "aba"   , false);
  is_valid("a\\)" , "\\\\"  , false);
  is_valid("a\\)" , "\\("   , false);
  is_valid("a\\)" , "\\)"   , false);
  is_valid("a\\)" , "\\|"   , false);
  is_valid("a\\)" , "\\*"   , false);
  is_valid("a\\)" , "\\@"   , false);
  is_valid("a\\)" , "a\\\\" , false);
  is_valid("a\\)" , "a\\("  , false);
  is_valid("a\\)" , "a\\)"  , false);
  is_valid("a\\)" , "a\\|"  , false);
  is_valid("a\\)" , "a\\*"  , false);
  is_valid("a\\)" , "a\\@"  , false);
  is_valid("a\\)" , "\\\\a" , false);
  is_valid("a\\)" , "\\(a"  , false);
  is_valid("a\\)" , "\\)a"  , false);
  is_valid("a\\)" , "\\|a"  , false);
  is_valid("a\\)" , "\\*a"  , false);
  is_valid("a\\)" , "\\@a"  , false);
  is_valid("a\\)" , "\\"    , false);
  is_valid("a\\)" , "("     , false);
  is_valid("a\\)" , ")"     , false);
  is_valid("a\\)" , "|"     , false);
  is_valid("a\\)" , "*"     , false);
  is_valid("a\\)" , "@"     , false);
  is_valid("a\\)" , "a\\"   , false);
  is_valid("a\\)" , "a("    , false);
  is_valid("a\\)" , "a)"    , true );
  is_valid("a\\)" , "a|"    , false);
  is_valid("a\\)" , "a*"    , false);
  is_valid("a\\)" , "a@"    , false);
  is_valid("a\\)" , "\\a"   , false);
  is_valid("a\\)" , "(a"    , false);
  is_valid("a\\)" , ")a"    , false);
  is_valid("a\\)" , "|a"    , false);
  is_valid("a\\)" , "*a"    , false);
  is_valid("a\\)" , "@a"    , false);

  is_valid("\\)a" , "a"     , false);
  is_valid("\\)a" , "aa"    , false);
  is_valid("\\)a" , "aaa"   , false);
  is_valid("\\)a" , "ab"    , false);
  is_valid("\\)a" , "aba"   , false);
  is_valid("\\)a" , "\\\\"  , false);
  is_valid("\\)a" , "\\("   , false);
  is_valid("\\)a" , "\\)"   , false);
  is_valid("\\)a" , "\\|"   , false);
  is_valid("\\)a" , "\\*"   , false);
  is_valid("\\)a" , "\\@"   , false);
  is_valid("\\)a" , "a\\\\" , false);
  is_valid("\\)a" , "a\\("  , false);
  is_valid("\\)a" , "a\\)"  , false);
  is_valid("\\)a" , "a\\|"  , false);
  is_valid("\\)a" , "a\\*"  , false);
  is_valid("\\)a" , "a\\@"  , false);
  is_valid("\\)a" , "\\\\a" , false);
  is_valid("\\)a" , "\\(a"  , false);
  is_valid("\\)a" , "\\)a"  , false);
  is_valid("\\)a" , "\\|a"  , false);
  is_valid("\\)a" , "\\*a"  , false);
  is_valid("\\)a" , "\\@a"  , false);
  is_valid("\\)a" , "\\"    , false);
  is_valid("\\)a" , "("     , false);
  is_valid("\\)a" , ")"     , false);
  is_valid("\\)a" , "|"     , false);
  is_valid("\\)a" , "*"     , false);
  is_valid("\\)a" , "@"     , false);
  is_valid("\\)a" , "a\\"   , false);
  is_valid("\\)a" , "a("    , false);
  is_valid("\\)a" , "a)"    , false);
  is_valid("\\)a" , "a|"    , false);
  is_valid("\\)a" , "a*"    , false);
  is_valid("\\)a" , "a@"    , false);
  is_valid("\\)a" , "\\a"   , false);
  is_valid("\\)a" , "(a"    , false);
  is_valid("\\)a" , ")a"    , true );
  is_valid("\\)a" , "|a"    , false);
  is_valid("\\)a" , "*a"    , false);
  is_valid("\\)a" , "@a"    , false);/*}}}*/
  is_valid( "\\|" , "a"     , false);/*{{{*/
  is_valid( "\\|" , "aa"    , false);
  is_valid( "\\|" , "aaa"   , false);
  is_valid( "\\|" , "ab"    , false);
  is_valid( "\\|" , "aba"   , false);
  is_valid( "\\|" , "\\\\"  , false);
  is_valid( "\\|" , "\\("   , false);
  is_valid( "\\|" , "\\)"   , false);
  is_valid( "\\|" , "\\|"   , false);
  is_valid( "\\|" , "\\*"   , false);
  is_valid( "\\|" , "\\@"   , false);
  is_valid( "\\|" , "a\\\\" , false);
  is_valid( "\\|" , "a\\("  , false);
  is_valid( "\\|" , "a\\)"  , false);
  is_valid( "\\|" , "a\\|"  , false);
  is_valid( "\\|" , "a\\*"  , false);
  is_valid( "\\|" , "a\\@"  , false);
  is_valid( "\\|" , "\\\\a" , false);
  is_valid( "\\|" , "\\(a"  , false);
  is_valid( "\\|" , "\\)a"  , false);
  is_valid( "\\|" , "\\|a"  , false);
  is_valid( "\\|" , "\\*a"  , false);
  is_valid( "\\|" , "\\@a"  , false);
  is_valid( "\\|" , "\\"    , false);
  is_valid( "\\|" , "("     , false);
  is_valid( "\\|" , ")"     , false);
  is_valid( "\\|" , "|"     , true );
  is_valid( "\\|" , "*"     , false);
  is_valid( "\\|" , "@"     , false);
  is_valid( "\\|" , "a\\"   , false);
  is_valid( "\\|" , "a("    , false);
  is_valid( "\\|" , "a)"    , false);
  is_valid( "\\|" , "a|"    , false);
  is_valid( "\\|" , "a*"    , false);
  is_valid( "\\|" , "a@"    , false);
  is_valid( "\\|" , "\\a"   , false);
  is_valid( "\\|" , "(a"    , false);
  is_valid( "\\|" , ")a"    , false);
  is_valid( "\\|" , "|a"    , false);
  is_valid( "\\|" , "*a"    , false);
  is_valid( "\\|" , "@a"    , false);

  is_valid("a\\|" , "a"     , false);
  is_valid("a\\|" , "aa"    , false);
  is_valid("a\\|" , "aaa"   , false);
  is_valid("a\\|" , "ab"    , false);
  is_valid("a\\|" , "aba"   , false);
  is_valid("a\\|" , "\\\\"  , false);
  is_valid("a\\|" , "\\("   , false);
  is_valid("a\\|" , "\\)"   , false);
  is_valid("a\\|" , "\\|"   , false);
  is_valid("a\\|" , "\\*"   , false);
  is_valid("a\\|" , "\\@"   , false);
  is_valid("a\\|" , "a\\\\" , false);
  is_valid("a\\|" , "a\\("  , false);
  is_valid("a\\|" , "a\\)"  , false);
  is_valid("a\\|" , "a\\|"  , false);
  is_valid("a\\|" , "a\\*"  , false);
  is_valid("a\\|" , "a\\@"  , false);
  is_valid("a\\|" , "\\\\a" , false);
  is_valid("a\\|" , "\\(a"  , false);
  is_valid("a\\|" , "\\)a"  , false);
  is_valid("a\\|" , "\\|a"  , false);
  is_valid("a\\|" , "\\*a"  , false);
  is_valid("a\\|" , "\\@a"  , false);
  is_valid("a\\|" , "\\"    , false);
  is_valid("a\\|" , "("     , false);
  is_valid("a\\|" , ")"     , false);
  is_valid("a\\|" , "|"     , false);
  is_valid("a\\|" , "*"     , false);
  is_valid("a\\|" , "@"     , false);
  is_valid("a\\|" , "a\\"   , false);
  is_valid("a\\|" , "a("    , false);
  is_valid("a\\|" , "a)"    , false);
  is_valid("a\\|" , "a|"    , true );
  is_valid("a\\|" , "a*"    , false);
  is_valid("a\\|" , "a@"    , false);
  is_valid("a\\|" , "\\a"   , false);
  is_valid("a\\|" , "(a"    , false);
  is_valid("a\\|" , ")a"    , false);
  is_valid("a\\|" , "|a"    , false);
  is_valid("a\\|" , "*a"    , false);
  is_valid("a\\|" , "@a"    , false);

  is_valid("\\|a" , "a"     , false);
  is_valid("\\|a" , "aa"    , false);
  is_valid("\\|a" , "aaa"   , false);
  is_valid("\\|a" , "ab"    , false);
  is_valid("\\|a" , "aba"   , false);
  is_valid("\\|a" , "\\\\"  , false);
  is_valid("\\|a" , "\\("   , false);
  is_valid("\\|a" , "\\)"   , false);
  is_valid("\\|a" , "\\|"   , false);
  is_valid("\\|a" , "\\*"   , false);
  is_valid("\\|a" , "\\@"   , false);
  is_valid("\\|a" , "a\\\\" , false);
  is_valid("\\|a" , "a\\("  , false);
  is_valid("\\|a" , "a\\)"  , false);
  is_valid("\\|a" , "a\\|"  , false);
  is_valid("\\|a" , "a\\*"  , false);
  is_valid("\\|a" , "a\\@"  , false);
  is_valid("\\|a" , "\\\\a" , false);
  is_valid("\\|a" , "\\(a"  , false);
  is_valid("\\|a" , "\\)a"  , false);
  is_valid("\\|a" , "\\|a"  , false);
  is_valid("\\|a" , "\\*a"  , false);
  is_valid("\\|a" , "\\@a"  , false);
  is_valid("\\|a" , "\\"    , false);
  is_valid("\\|a" , "("     , false);
  is_valid("\\|a" , ")"     , false);
  is_valid("\\|a" , "|"     , false);
  is_valid("\\|a" , "*"     , false);
  is_valid("\\|a" , "@"     , false);
  is_valid("\\|a" , "a\\"   , false);
  is_valid("\\|a" , "a("    , false);
  is_valid("\\|a" , "a)"    , false);
  is_valid("\\|a" , "a|"    , false);
  is_valid("\\|a" , "a*"    , false);
  is_valid("\\|a" , "a@"    , false);
  is_valid("\\|a" , "\\a"   , false);
  is_valid("\\|a" , "(a"    , false);
  is_valid("\\|a" , ")a"    , false);
  is_valid("\\|a" , "|a"    , true );
  is_valid("\\|a" , "*a"    , false);
  is_valid("\\|a" , "@a"    , false);/*}}}*/
  is_valid( "\\*" , "a"     , false);/*{{{*/
  is_valid( "\\*" , "aa"    , false);
  is_valid( "\\*" , "aaa"   , false);
  is_valid( "\\*" , "ab"    , false);
  is_valid( "\\*" , "aba"   , false);
  is_valid( "\\*" , "\\\\"  , false);
  is_valid( "\\*" , "\\("   , false);
  is_valid( "\\*" , "\\)"   , false);
  is_valid( "\\*" , "\\|"   , false);
  is_valid( "\\*" , "\\*"   , false);
  is_valid( "\\*" , "\\@"   , false);
  is_valid( "\\*" , "a\\\\" , false);
  is_valid( "\\*" , "a\\("  , false);
  is_valid( "\\*" , "a\\)"  , false);
  is_valid( "\\*" , "a\\|"  , false);
  is_valid( "\\*" , "a\\*"  , false);
  is_valid( "\\*" , "a\\@"  , false);
  is_valid( "\\*" , "\\\\a" , false);
  is_valid( "\\*" , "\\(a"  , false);
  is_valid( "\\*" , "\\)a"  , false);
  is_valid( "\\*" , "\\|a"  , false);
  is_valid( "\\*" , "\\*a"  , false);
  is_valid( "\\*" , "\\@a"  , false);
  is_valid( "\\*" , "\\"    , false);
  is_valid( "\\*" , "("     , false);
  is_valid( "\\*" , ")"     , false);
  is_valid( "\\*" , "|"     , false);
  is_valid( "\\*" , "*"     , true );
  is_valid( "\\*" , "@"     , false);
  is_valid( "\\*" , "a\\"   , false);
  is_valid( "\\*" , "a("    , false);
  is_valid( "\\*" , "a)"    , false);
  is_valid( "\\*" , "a|"    , false);
  is_valid( "\\*" , "a*"    , false);
  is_valid( "\\*" , "a@"    , false);
  is_valid( "\\*" , "\\a"   , false);
  is_valid( "\\*" , "(a"    , false);
  is_valid( "\\*" , ")a"    , false);
  is_valid( "\\*" , "|a"    , false);
  is_valid( "\\*" , "*a"    , false);
  is_valid( "\\*" , "@a"    , false);

  is_valid("a\\*" , "a"     , false);
  is_valid("a\\*" , "aa"    , false);
  is_valid("a\\*" , "aaa"   , false);
  is_valid("a\\*" , "ab"    , false);
  is_valid("a\\*" , "aba"   , false);
  is_valid("a\\*" , "\\\\"  , false);
  is_valid("a\\*" , "\\("   , false);
  is_valid("a\\*" , "\\)"   , false);
  is_valid("a\\*" , "\\|"   , false);
  is_valid("a\\*" , "\\*"   , false);
  is_valid("a\\*" , "\\@"   , false);
  is_valid("a\\*" , "a\\\\" , false);
  is_valid("a\\*" , "a\\("  , false);
  is_valid("a\\*" , "a\\)"  , false);
  is_valid("a\\*" , "a\\|"  , false);
  is_valid("a\\*" , "a\\*"  , false);
  is_valid("a\\*" , "a\\@"  , false);
  is_valid("a\\*" , "\\\\a" , false);
  is_valid("a\\*" , "\\(a"  , false);
  is_valid("a\\*" , "\\)a"  , false);
  is_valid("a\\*" , "\\|a"  , false);
  is_valid("a\\*" , "\\*a"  , false);
  is_valid("a\\*" , "\\@a"  , false);
  is_valid("a\\*" , "\\"    , false);
  is_valid("a\\*" , "("     , false);
  is_valid("a\\*" , ")"     , false);
  is_valid("a\\*" , "|"     , false);
  is_valid("a\\*" , "*"     , false);
  is_valid("a\\*" , "@"     , false);
  is_valid("a\\*" , "a\\"   , false);
  is_valid("a\\*" , "a("    , false);
  is_valid("a\\*" , "a)"    , false);
  is_valid("a\\*" , "a|"    , false);
  is_valid("a\\*" , "a*"    , true );
  is_valid("a\\*" , "a@"    , false);
  is_valid("a\\*" , "\\a"   , false);
  is_valid("a\\*" , "(a"    , false);
  is_valid("a\\*" , ")a"    , false);
  is_valid("a\\*" , "|a"    , false);
  is_valid("a\\*" , "*a"    , false);
  is_valid("a\\*" , "@a"    , false);

  is_valid("\\*a" , "a"     , false);
  is_valid("\\*a" , "aa"    , false);
  is_valid("\\*a" , "aaa"   , false);
  is_valid("\\*a" , "ab"    , false);
  is_valid("\\*a" , "aba"   , false);
  is_valid("\\*a" , "\\\\"  , false);
  is_valid("\\*a" , "\\("   , false);
  is_valid("\\*a" , "\\)"   , false);
  is_valid("\\*a" , "\\|"   , false);
  is_valid("\\*a" , "\\*"   , false);
  is_valid("\\*a" , "\\@"   , false);
  is_valid("\\*a" , "a\\\\" , false);
  is_valid("\\*a" , "a\\("  , false);
  is_valid("\\*a" , "a\\)"  , false);
  is_valid("\\*a" , "a\\|"  , false);
  is_valid("\\*a" , "a\\*"  , false);
  is_valid("\\*a" , "a\\@"  , false);
  is_valid("\\*a" , "\\\\a" , false);
  is_valid("\\*a" , "\\(a"  , false);
  is_valid("\\*a" , "\\)a"  , false);
  is_valid("\\*a" , "\\|a"  , false);
  is_valid("\\*a" , "\\*a"  , false);
  is_valid("\\*a" , "\\@a"  , false);
  is_valid("\\*a" , "\\"    , false);
  is_valid("\\*a" , "("     , false);
  is_valid("\\*a" , ")"     , false);
  is_valid("\\*a" , "|"     , false);
  is_valid("\\*a" , "*"     , false);
  is_valid("\\*a" , "@"     , false);
  is_valid("\\*a" , "a\\"   , false);
  is_valid("\\*a" , "a("    , false);
  is_valid("\\*a" , "a)"    , false);
  is_valid("\\*a" , "a|"    , false);
  is_valid("\\*a" , "a*"    , false);
  is_valid("\\*a" , "a@"    , false);
  is_valid("\\*a" , "\\a"   , false);
  is_valid("\\*a" , "(a"    , false);
  is_valid("\\*a" , ")a"    , false);
  is_valid("\\*a" , "|a"    , false);
  is_valid("\\*a" , "*a"    , true );
  is_valid("\\*a" , "@a"    , false);/*}}}*/
  is_valid( "\\@" , "a"     , false);/*{{{*/
  is_valid( "\\@" , "aa"    , false);
  is_valid( "\\@" , "aaa"   , false);
  is_valid( "\\@" , "ab"    , false);
  is_valid( "\\@" , "aba"   , false);
  is_valid( "\\@" , "\\\\"  , false);
  is_valid( "\\@" , "\\("   , false);
  is_valid( "\\@" , "\\)"   , false);
  is_valid( "\\@" , "\\|"   , false);
  is_valid( "\\@" , "\\*"   , false);
  is_valid( "\\@" , "\\@"   , false);
  is_valid( "\\@" , "a\\\\" , false);
  is_valid( "\\@" , "a\\("  , false);
  is_valid( "\\@" , "a\\)"  , false);
  is_valid( "\\@" , "a\\|"  , false);
  is_valid( "\\@" , "a\\*"  , false);
  is_valid( "\\@" , "a\\@"  , false);
  is_valid( "\\@" , "\\\\a" , false);
  is_valid( "\\@" , "\\(a"  , false);
  is_valid( "\\@" , "\\)a"  , false);
  is_valid( "\\@" , "\\|a"  , false);
  is_valid( "\\@" , "\\*a"  , false);
  is_valid( "\\@" , "\\@a"  , false);
  is_valid( "\\@" , "\\"    , false);
  is_valid( "\\@" , "("     , false);
  is_valid( "\\@" , ")"     , false);
  is_valid( "\\@" , "|"     , false);
  is_valid( "\\@" , "*"     , false);
  is_valid( "\\@" , "@"     , true );
  is_valid( "\\@" , "a\\"   , false);
  is_valid( "\\@" , "a("    , false);
  is_valid( "\\@" , "a)"    , false);
  is_valid( "\\@" , "a|"    , false);
  is_valid( "\\@" , "a*"    , false);
  is_valid( "\\@" , "a@"    , false);
  is_valid( "\\@" , "\\a"   , false);
  is_valid( "\\@" , "(a"    , false);
  is_valid( "\\@" , ")a"    , false);
  is_valid( "\\@" , "|a"    , false);
  is_valid( "\\@" , "*a"    , false);
  is_valid( "\\@" , "@a"    , false);

  is_valid("a\\@" , "a"     , false);
  is_valid("a\\@" , "aa"    , false);
  is_valid("a\\@" , "aaa"   , false);
  is_valid("a\\@" , "ab"    , false);
  is_valid("a\\@" , "aba"   , false);
  is_valid("a\\@" , "\\\\"  , false);
  is_valid("a\\@" , "\\("   , false);
  is_valid("a\\@" , "\\)"   , false);
  is_valid("a\\@" , "\\|"   , false);
  is_valid("a\\@" , "\\*"   , false);
  is_valid("a\\@" , "\\@"   , false);
  is_valid("a\\@" , "a\\\\" , false);
  is_valid("a\\@" , "a\\("  , false);
  is_valid("a\\@" , "a\\)"  , false);
  is_valid("a\\@" , "a\\|"  , false);
  is_valid("a\\@" , "a\\*"  , false);
  is_valid("a\\@" , "a\\@"  , false);
  is_valid("a\\@" , "\\\\a" , false);
  is_valid("a\\@" , "\\(a"  , false);
  is_valid("a\\@" , "\\)a"  , false);
  is_valid("a\\@" , "\\|a"  , false);
  is_valid("a\\@" , "\\*a"  , false);
  is_valid("a\\@" , "\\@a"  , false);
  is_valid("a\\@" , "\\"    , false);
  is_valid("a\\@" , "("     , false);
  is_valid("a\\@" , ")"     , false);
  is_valid("a\\@" , "|"     , false);
  is_valid("a\\@" , "*"     , false);
  is_valid("a\\@" , "@"     , false);
  is_valid("a\\@" , "a\\"   , false);
  is_valid("a\\@" , "a("    , false);
  is_valid("a\\@" , "a)"    , false);
  is_valid("a\\@" , "a|"    , false);
  is_valid("a\\@" , "a*"    , false);
  is_valid("a\\@" , "a@"    , true );
  is_valid("a\\@" , "\\a"   , false);
  is_valid("a\\@" , "(a"    , false);
  is_valid("a\\@" , ")a"    , false);
  is_valid("a\\@" , "|a"    , false);
  is_valid("a\\@" , "*a"    , false);
  is_valid("a\\@" , "@a"    , false);

  is_valid("\\@a" , "a"     , false);
  is_valid("\\@a" , "aa"    , false);
  is_valid("\\@a" , "aaa"   , false);
  is_valid("\\@a" , "ab"    , false);
  is_valid("\\@a" , "aba"   , false);
  is_valid("\\@a" , "\\\\"  , false);
  is_valid("\\@a" , "\\("   , false);
  is_valid("\\@a" , "\\)"   , false);
  is_valid("\\@a" , "\\|"   , false);
  is_valid("\\@a" , "\\*"   , false);
  is_valid("\\@a" , "\\@"   , false);
  is_valid("\\@a" , "a\\\\" , false);
  is_valid("\\@a" , "a\\("  , false);
  is_valid("\\@a" , "a\\)"  , false);
  is_valid("\\@a" , "a\\|"  , false);
  is_valid("\\@a" , "a\\*"  , false);
  is_valid("\\@a" , "a\\@"  , false);
  is_valid("\\@a" , "\\\\a" , false);
  is_valid("\\@a" , "\\(a"  , false);
  is_valid("\\@a" , "\\)a"  , false);
  is_valid("\\@a" , "\\|a"  , false);
  is_valid("\\@a" , "\\*a"  , false);
  is_valid("\\@a" , "\\@a"  , false);
  is_valid("\\@a" , "\\"    , false);
  is_valid("\\@a" , "("     , false);
  is_valid("\\@a" , ")"     , false);
  is_valid("\\@a" , "|"     , false);
  is_valid("\\@a" , "*"     , false);
  is_valid("\\@a" , "@"     , false);
  is_valid("\\@a" , "a\\"   , false);
  is_valid("\\@a" , "a("    , false);
  is_valid("\\@a" , "a)"    , false);
  is_valid("\\@a" , "a|"    , false);
  is_valid("\\@a" , "a*"    , false);
  is_valid("\\@a" , "a@"    , false);
  is_valid("\\@a" , "\\a"   , false);
  is_valid("\\@a" , "(a"    , false);
  is_valid("\\@a" , ")a"    , false);
  is_valid("\\@a" , "|a"    , false);
  is_valid("\\@a" , "*a"    , false);
  is_valid("\\@a" , "@a"    , true );/*}}}*/

  // 長い正規表現
  is_valid("(a|b)(a|b)(a|b)(a|b)", ""        , false);/*{{{*/
  is_valid("(a|b)(a|b)(a|b)(a|b)", "aaaa"    , true );
  is_valid("(a|b)(a|b)(a|b)(a|b)", "abab"    , true );
  is_valid("(a|b)(a|b)(a|b)(a|b)", "aba"     , false);
  is_valid("(a|b)(a|b)(a|b)(a|b)", "aaaaa"   , false);
  is_valid("(a|b|c|d|e|f|g|h)",    "a"       , true );
  is_valid("(a|b|c|d|e|f|g|h)",    "b"       , true );
  is_valid("(a|b|c|d|e|f|g|h)",    "h"       , true );
  is_valid("(a|b|c|d|e|f|g|h)",    "i"       , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , ""  , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "(" , true );
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "|" , true );
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , ")" , true );
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "*" , true );
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "@" , true );
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\", true );
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "a" , true );
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "b" , true );
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "c" , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\("   , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\|"   , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\)"   , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\*"   , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\@"   , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\\\"  , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\\\a" , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\\\b" , false);
  is_valid("(\\(|\\||\\)|\\*|\\@|\\\\|a|b)"  , "\\\\c" , false);
  is_valid("(\\**|\\\\)", ""    , true );
  is_valid("(\\**|\\\\)", "*"   , true );
  is_valid("(\\**|\\\\)", "**"  , true );
  is_valid("(\\**|\\\\)", "***" , true );
  is_valid("(\\**|\\\\)", "\\"  , true );
  is_valid("(\\**|\\\\)", "\\\\", false);
  is_valid("((a*|b*)*|(c*|d*))*" , ""    , true );
  is_valid("((a*|b*)*|(c*|d*))*" , "a"   , true );
  is_valid("((a*|b*)*|(c*|d*))*" , "aa"  , true );
  is_valid("((a*|b*)*|(c*|d*))*" , "b"   , true );
  is_valid("((a*|b*)*|(c*|d*))*" , "bb"  , true );
  is_valid("((a*|b*)*|(c*|d*))*" , "ab"  , true );
  is_valid("((a*|b*)*|(c*|d*))*" , "ba"  , true );
  is_valid("((a*|b*)*|(c*|d*))*" , "abcd", true );
  is_valid("((a*|b*)*|(c*|d*))*" , "abca", true );
  is_valid("((a*|b*)*|(c*|d*))*" , "caca", true );
  is_valid("((a*|b*)*|(c*|d*))*" , "cac*", false);
  is_valid("((a*|b*)*|(c*|d*))*" , "cac*", false);
  is_valid("(ab|ab)*"            , ""    , true );
  is_valid("(ab|ab)*"            , "a"   , false);
  is_valid("(ab|ab)*"            , "ab"  , true );
  is_valid("(ab|ab)*"            , "aba" , false);
  is_valid("(ab|ab)*"            , "abab", true );/*}}}*/

  // 分岐のない(...)のチェック
  is_valid("(a)"      , ""     , false);/*{{{*/
  is_valid("(a)"      , "a"    , true );
  is_valid("(a)"      , "aa"   , false);
  is_valid("(a)"      , "aaa"  , false);
  is_valid("(a)"      , "aaaa" , false);
  is_valid("(aa)"     , ""     , false);
  is_valid("(aa)"     , "a"    , false);
  is_valid("(aa)"     , "aa"   , true );
  is_valid("(aa)"     , "aaa"  , false);
  is_valid("(aa)"     , "aaaa" , false);
  is_valid("(ab)"     , ""     , false);
  is_valid("(ab)"     , "a"    , false);
  is_valid("(ab)"     , "ab"   , true );
  is_valid("(ab)"     , "aba"  , false);
  is_valid("(ab)"     , "abab" , false);
  is_valid("(a)(a)"   , ""     , false);
  is_valid("(a)(a)"   , "a"    , false);
  is_valid("(a)(a)"   , "aa"   , true );
  is_valid("(a)(a)"   , "aaa"  , false);
  is_valid("(a)(a)"   , "aaaa" , false);
  is_valid("(aa)(aa)" , ""     , false);
  is_valid("(aa)(aa)" , "a"    , false);
  is_valid("(aa)(aa)" , "aa"   , false);
  is_valid("(aa)(aa)" , "aaa"  , false);
  is_valid("(aa)(aa)" , "aaaa" , true );
  is_valid("(ab)(ab)" , ""     , false);
  is_valid("(ab)(ab)" , "a"    , false);
  is_valid("(ab)(ab)" , "ab"   , false);
  is_valid("(ab)(ab)" , "aba"  , false);
  is_valid("(ab)(ab)" , "abab" , true );
  is_valid("(a)*"     , ""     , true );
  is_valid("(a)*"     , "a"    , true );
  is_valid("(a)*"     , "aa"   , true );
  is_valid("(a)*"     , "aaa"  , true );
  is_valid("(a)*"     , "aaaa" , true );
  is_valid("(aa)*"    , ""     , true );
  is_valid("(aa)*"    , "a"    , false);
  is_valid("(aa)*"    , "aa"   , true );
  is_valid("(aa)*"    , "aaa"  , false);
  is_valid("(aa)*"    , "aaaa" , true );
  is_valid("(ab)*"    , ""     , true );
  is_valid("(ab)*"    , "a"    , false);
  is_valid("(ab)*"    , "ab"   , true );
  is_valid("(ab)*"    , "aba"  , false);
  is_valid("(ab)*"    , "abab" , true );
  is_valid("(\\(a)"   , "("    , false);
  is_valid("(\\(a)"   , "(a"   , true );
  is_valid("(\\(a)"   , "(aa"  , false);
  is_valid("(\\(a)"   , "(aaa" , false);
  is_valid("(\\(a)"   , "(aaaa", false);
  is_valid("(\\(aa)"  , "("    , false);
  is_valid("(\\(aa)"  , "(a"   , false);
  is_valid("(\\(aa)"  , "(aa"  , true );
  is_valid("(\\(aa)"  , "(aaa" , false);
  is_valid("(\\(aa)"  , "(aaaa", false);
  is_valid("(\\(ab)"  , "("    , false);
  is_valid("(\\(ab)"  , "(a"   , false);
  is_valid("(\\(ab)"  , "(ab"  , true );
  is_valid("(\\(ab)"  , "(aba" , false);
  is_valid("(\\(ab)"  , "(abab", false);
  is_valid("(a\\()"   , "("    , false);
  is_valid("(a\\()"   , "a("   , true );
  is_valid("(a\\()"   , "aa("  , false);
  is_valid("(a\\()"   , "aaa(" , false);
  is_valid("(a\\()"   , "aaaa(", false);
  is_valid("(aa\\()"  , "("    , false);
  is_valid("(aa\\()"  , "a("   , false);
  is_valid("(aa\\()"  , "aa("  , true );
  is_valid("(aa\\()"  , "aaa(" , false);
  is_valid("(aa\\()"  , "aaaa(", false);
  is_valid("(ab\\()"  , "("    , false);
  is_valid("(ab\\()"  , "a("   , false);
  is_valid("(ab\\()"  , "ab("  , true );
  is_valid("(ab\\()"  , "aba(" , false);
  is_valid("(ab\\()"  , "abab(", false);/*}}}*/

  // 部分マッチ。引数の最後2つはis_forwardとis_short
  is_partial_valid(""       , ""        , false, true , true );/*{{{*/
  is_partial_valid(""       , "a"       , false, true , true );
  is_partial_valid(""       , "ab"      , false, true , true );
  is_partial_valid(""       , "ba"      , false, true , true );
  is_partial_valid(""       , "bab"     , false, true , true );
  is_partial_valid(""       , ""        , false, true , false);
  is_partial_valid(""       , "a"       , false, true , false);
  is_partial_valid(""       , "ab"      , false, true , false);
  is_partial_valid(""       , "ba"      , false, true , false);
  is_partial_valid(""       , "bab"     , false, true , false);
  is_partial_valid(""       , ""        , false, false, true );
  is_partial_valid(""       , "a"       , false, false, true );
  is_partial_valid(""       , "ab"      , false, false, true );
  is_partial_valid(""       , "ba"      , false, false, true );
  is_partial_valid(""       , "bab"     , false, false, true );
  is_partial_valid(""       , ""        , false, false, false);
  is_partial_valid(""       , "a"       , false, false, false);
  is_partial_valid(""       , "ab"      , false, false, false);
  is_partial_valid(""       , "ba"      , false, false, false);
  is_partial_valid(""       , "bab"     , false, false, false);

  is_partial_valid("a"      , ""        , false, true , true );
  is_partial_valid("a"      , "a"       , true , true , true );
  is_partial_valid("a"      , "ab"      , true , true , true );
  is_partial_valid("a"      , "ba"      , false, true , true );
  is_partial_valid("a"      , "bab"     , false, true , true );
  is_partial_valid("a"      , ""        , false, true , false);
  is_partial_valid("a"      , "a"       , true , true , false);
  is_partial_valid("a"      , "ab"      , true , true , false);
  is_partial_valid("a"      , "ba"      , false, true , false);
  is_partial_valid("a"      , "bab"     , false, true , false);
  is_partial_valid("a"      , ""        , false, false, true );
  is_partial_valid("a"      , "a"       , true , false, true );
  is_partial_valid("a"      , "ab"      , false, false, true );
  is_partial_valid("a"      , "ba"      , true , false, true );
  is_partial_valid("a"      , "bab"     , false, false, true );
  is_partial_valid("a"      , ""        , false, false, false);
  is_partial_valid("a"      , "a"       , true , false, false);
  is_partial_valid("a"      , "ab"      , false, false, false);
  is_partial_valid("a"      , "ba"      , true , false, false);
  is_partial_valid("a"      , "bab"     , false, false, false);

  is_partial_valid("ab"     , ""        , false, true , true );
  is_partial_valid("ab"     , "a"       , false, true , true );
  is_partial_valid("ab"     , "ab"      , true , true , true );
  is_partial_valid("ab"     , "ba"      , false, true , true );
  is_partial_valid("ab"     , "aba"     , true , true , true );
  is_partial_valid("ab"     , "bab"     , false, true , true );
  is_partial_valid("ab"     , ""        , false, true , false);
  is_partial_valid("ab"     , "a"       , false, true , false);
  is_partial_valid("ab"     , "ab"      , true , true , false);
  is_partial_valid("ab"     , "ba"      , false, true , false);
  is_partial_valid("ab"     , "aba"     , true , true , false);
  is_partial_valid("ab"     , "bab"     , false, true , false);
  is_partial_valid("ab"     , ""        , false, false, true );
  is_partial_valid("ab"     , "a"       , false, false, true );
  is_partial_valid("ab"     , "ab"      , true , false, true );
  is_partial_valid("ab"     , "ba"      , false, false, true );
  is_partial_valid("ab"     , "aba"     , false, false, true );
  is_partial_valid("ab"     , "bab"     , true , false, true );
  is_partial_valid("ab"     , ""        , false, false, false);
  is_partial_valid("ab"     , "a"       , false, false, false);
  is_partial_valid("ab"     , "ab"      , true , false, false);
  is_partial_valid("ab"     , "ba"      , false, false, false);
  is_partial_valid("ab"     , "aba"     , false, false, false);
  is_partial_valid("ab"     , "bab"     , true , false, false);/*}}}*/

  fprintf(stderr, "STATISTICS: [%d/%d] ARE PASSED\n", correct, question);
  return 0;
}
